#!/usr/bin/perl -T
#
# Bulgarian translation by Veselin Slavov, vess@btc.net, 2002/04/02
# Bulgarian alphabet encoded by windows-1251
#

$lang_charset = 'windows-1251';

%lang_folders =
   (
   INBOX => 'Входящи',
   'saved-messages' => 'Записани',
   'sent-mail'      => 'Изпратени',
   'saved-drafts'   => 'Чернови',
   'mail-trash'     => 'Кошче',
   DELETE => '--ИЗТРИЙ--'
   );

%lang_sortlabels =
   (
   status      => 'статус (първо непрочетени)',
   date        => 'дата (първо новите)',
   date_rev    => 'дата (първо старите)',
   sender      => 'подател (първо новите)',
   sender_rev  => 'подател (първо старите)',
   subject     => 'тема (първо новите)',
   subject_rev => 'тема (първо старите)',
   size        => 'размер (първо големите)',
   size_rev    => 'размер (първо малките)'
   );

%lang_prioritylabels =
   (
   normal      => 'нормален',
   urgent      => 'спешно',
   'non-urgent'=> 'не е спешно'
   );

%lang_withoriglabels =
   (
   at_beginning => 'в началото',
   at_end      => 'в края',
   none        => 'няма'
   );

%lang_receiptlabels =
   (
   ask => 'Питай за потвърждение',
   yes => 'Да',
   no  => 'Не'
   );

%lang_timelabels =
   (
     10 => '10 минути',
     30 => '30 минути',
     60 => '60 минути',
    120 => '2 часа',
    180 => '3 часа',
    360 => '6 часа',
    720 => '12 часа',
   1440 => '24 часа'
   );

%lang_text =
   (  
   login      => 'Вход',
   clear      => 'Изчисти',
   changepwd  => 'Смяна на парола',
   viewhistory=> 'Хронология',
   of         => 'от',
   messages   => 'съобщения',
   unread     => 'непрочетени',
   nomessages => 'Няма съобщения',
   composenew => 'Създаване на ново съобщение',
   refresh    => 'Опресняване',
   userprefs  => 'Потребителски настройки',
   addressbook=> 'Книга с адреси',
   folders    => 'Папки',
   emptytrash => 'Изпразни кошчето',
   forever    => 'Завинаги',
   userdef    => 'Дефинирано от потребителя',
   logout     => 'Изход',
   page       => 'Страница',
   msgcopyconf=> '\'Моля потвърдете за копиране\'',
   copy       => 'Копирай',
   msgmoveconf=> '\'Моля потвърдете за преместване\'',
   move       => 'Премести',
   markasread => 'Маркирано като прочетено',
   markasunread => 'Маркирано като непрочетено',
   dateformat => 'Формат за датата',
   date       => 'Дата',
   recipient  => 'Получател',
   sender     => 'Подател',
   subject    => 'Тема',
   thread     => 'Свързани',
   size       => 'Размер',
   backto     => 'Назад към',
   reply      => 'Отговори',
   replyall   => 'Отговори на всички',
   forward    => 'Препрати',
   forwardasatt=>'Препрати като прикачен',
   printfriendly=> 'Приготви за печат',
   from       => 'От',
   replyto    => 'Отговори на',
   to         => 'До',
   cc         => 'Копие до',
   bcc        => 'Скрито копие',
   simplehead => 'Без детайли',
   allhead    => 'Детайли',
   simpleattmode => 'Без детайли за прикачени',
   allattmode    => 'Детайли за прикачени',
   attachment => 'Прикачени',
   type       => 'Тип',
   filename   => 'Име на файла',
   encoding   => 'Кодиране',
   description=> 'Описание',
   download   => 'Дръпни',
   thisispartialmsg => 'Това е част от съобщение',
   msgrebuild => 'Преподреждане на съобщението',
   editdraft  => 'Редакция чернова',
   savedraft  => 'Запис чернова',
   send       => 'Изпращане',
   about      => 'About',
   close      => 'Close',
   cancel     => 'Откажи',
   continue   => 'Продължи',
   loginagain => 'Влез отново',
   exit       => 'Изход',
   for        => 'за',
   yourname   => 'Вашето име',
   save       => 'Запис',
   add        => 'Добавяне',
   folderrenprop => '\'Моля въведете ново име за тази папка\'',
   rename     => 'Смени името',
   folderdelconf => '\'Потвърди за изтриването на папката заедно със съдържанието й!\'',
   chkindex    => 'Проверка на индекса',
   folderchkindexconf => '\'Искате ли да проверите индекса на тази папка?\'',
   reindex    => 'Нов индекс',
   folderreindexconf => '\'Сигурни ли сте, че искате да реиндексирате тази папка?\'',
   total      => 'Общо',
   delete     => 'Изтрий',
   reserve    => 'Запази',
   clearadd   => 'Да изтрия ли всички адреси',
   importadd  => 'Запомни адреса',
   exportadd  => 'Запис на адреси',
   import     => 'Прочети',
   addmod     => 'Добавяне/Редакция',
   modify     => 'Редакция',
   abooktitle => 'Книга с адреси',
   abook      => 'КНИГА С АДРЕСИ',
   name       => 'Име',
   email      => 'Адрес',
   note       => 'Забележка',
   group      => 'Група',
   quota_hit  => 'ОГРАНИЧЕНИЕ',
   usage      => 'Използване',
   editfroms  => 'Редакция на собствения адрес',
   pop3book   => 'POP3 Настройки',
   retr_pop3s => 'Прочитане на POP3 поща',
   filterbook => 'Настройка на филтрите',
   include    => 'Съдържа',
   exclude    => 'Не съдържа',
   smtprelay  => 'SMTP Relay',
   header     => 'Заглавка',
   body       => 'Текст',
   attfilename=> 'Прикачен файл',
   all        => 'Всички',
   enable     => 'активен',
   disable    => 'неактивн',
   filtered   => 'Филтриране',
   blockrelay => 'Блокирай SMTP Relay',
   blockemail => 'Блокирай поща',
   read       => 'Прочети',
   yourmsg    => 'Вашето съобщение',
   delivered  => 'Изпратено',
   wasreadon1 => 'е прочетено на',
   wasreadon2 => '.',
   globaladdressbook => 'Главна адресна книга',
   globalfilterrule => 'Чернови за филтри',
   readonly   => 'Само за четене',
   textcontent=> 'Съдържание',
   search     => 'Търсене',
   spellcheck => 'Проверка правописа',
   checkagain => 'Провери отново',
   finishchecking => 'Край на проверката',
   manuallyfix=> 'Ръчна поправка'
   );

%lang_err = (
            has_illegal_chars => 'съдържа непозволени символи!',
            couldnt_open      => 'Невъзможно отваряне',
            couldnt_locksh    => 'Невъзможно маркиране за четене на',
            couldnt_lock      => 'Невъзможно маркиране за писане на',
            couldnt_seek      => 'Не е намерено началото на',
            couldnt_close     => 'Невъзможно затваряне',
            disallowed_pop3   => 'Отхвърлен POP3 сървър',
            disallowed_client => 'Проблем при свързването от',
            disallowed_receiverdomain => 'Невъзможно изпращането на поща до този адрес',
            norootlogin       => 'Влизането като root не е позволено.',
            shouldnt_move_here=> 'Не местете съобщението тук!',
            destination_folder=> 'Папка цел',
            doesnt_exist      => 'не съществува!',
            foldername_long   => 'Името на папката трябва да е с по-мьлко от 16 символа!',
            folder_with_name  => 'Папка с това име',
            already_exists    => 'вече съществува!',
            cant_create_folder=> 'Папката не може да бъде създадена!',
            under_indexing    => 'в процес на индексиране, опитайте по късно',
            abook_invalid     => 'За съжаление не е запесан от Microsoft Outlook Express 5 в CSV формат. Чрез текстов редактор се уверете, че записите са със синтаксис "Име,E-mail адрес", върнете се',
            back              => 'назад',
            tryagain          => 'и опитайте отново.',
            abook_toobig      => 'За съжаление сте достигнали лимита си за адресна книга. Моля върнете се',
            cant_create_dir   => 'Невъзможно е създаването на личната Ви папка!',
            folder_hitquota   => 'Достигнахте лимита си, поради което пристигналите съобщения няма да бъдат обслужвани.  Невъзможно е местенето на съобщения никъде, освен в Кошчето, откъдето ще бъдат изтрити.  Върнете се изтрийте, ненужните съобщения или изпразнете кошчето и опитайте пак.',
            att_overlimit     => 'За съжаление превишавате лимита за прикачени файлове, който е',
            inv_msg_op        => 'Непозволена операция за съобщението',
            inv_sessid        => 'Достъпът отказан - проблем с БИСКВИТКИТЕ!',
            no_endpart        => 'Липсващ край',
            part_missing      => 'Липсващи части',
            rebuild_fmterr    => 'Грешка при форматиране',
            rebuild_sizeerr   => 'Проблем  размера',
            user_not_exist    => 'несъществуващ потребител',
            func_notsupported => 'неподържана операция',
            auth_syserr       => 'системна гришка при регистрация',
            param_fmterr      => 'грешен форматиращ параметър',
            pwd_incorrect     => 'грешна парола',
            network_server_error => 'грешка при свързване със сървъра',
            sendmail_error    => 'Проблем при изпращане на съобщението.  Моля проверете за грешки и опитайте пак.'
            );

1;
