#!/usr/bin/perl -T

# Catalan translation by Jordi Vidal, st.AT.e-puntcom.com
# charset: iso-8859-1

%lang_folders =
   (
   INBOX => 'ENTRADA',
   'saved-messages' => 'GUARDATS',
   'sent-mail'      => 'ENVIATS',
   'saved-drafts'   => 'ESBORRANYS',
   'mail-trash'     => 'PAPERERA',
   'all'            => 'All',
   DELETE => '--ESBORRAR--'
   );

%lang_sortlabels =
   (
   status      => 'Estat (Primer els no llegits)',
   date        => 'Data (Primer els nous)',
   date_rev    => 'Data (Primer els vells)',
   sender      => 'Qui ho envia (Primer els nous)',
   sender_rev  => 'Qui ho envia (Primer els vells)',
   subject     => 'Títol (Primer els nous)',
   subject_rev => 'Títol (Primer els vells)',
   size        => 'Mida (Primer els grans)',
   size_rev    => 'Mida (Primer els petits)'
   );

%lang_prioritylabels =
   (
   normal      => 'Normal',
   urgent      => 'Urgent',
   'non-urgent'=> 'No Urgent'
   );

%lang_withoriglabels =
   (
   at_beginning => 'a l´inici',
   at_end      => 'al final',
   none        => 'cap'
   );

%lang_receiptlabels =
   (
   ask => 'Pregunta-ho',
   yes => 'Si',
   no  => 'No'
   );

%lang_timelabels =
   (
     10 => '10 minuts',
     30 => '30 minuts',
     60 => '60 minuts',
    120 => '2 hores',
    180 => '3 hores',
    360 => '6 hores',
    720 => '12 hores',
   1440 => '24 hores'
   );

%lang_advsearchlabels =
   (
   contains    => 'contains',
   notcontains => 'does not contain',
   is          => 'is',
   isnot       => 'is not',
   startswith  => 'starts with',
   endswith    => 'ends with',
   regexp      => 'matches regexp(insensitive)',
   );

%lang_calendar = 
   (
   yearview  => 'Yearview',
   monthview => 'Monthview',
   weekview  => 'Weekview',
   dayview   => 'Dayview'
   );

%lang_month =
   (
   1  => 'January',
   2  => 'February',
   3  => 'March',
   4  => 'April',
   5  => 'May',
   6  => 'June',
   7  => 'July',
   8  => 'August',
   9  => 'September',
   10 => 'October',
   11 => 'November',
   12 => 'December'
   );

%lang_wday =
   (
   0 => 'Sunday',
   1 => 'Monday',
   2 => 'Tuesday',
   3 => 'Wednesday',
   4 => 'Thursday',
   5 => 'Friday',
   6 => 'Saturday'
   );

%lang_wday_abbrev =
   (
   week => 'WK',
   0 => 'S',
   1 => 'M',
   2 => 'T',
   3 => 'W',
   4 => 'T',
   5 => 'F',
   6 => 'S'
   );

%lang_order =
   (
   1 => '1st',
   2 => '2nd',
   3 => '3rd',
   4 => '4th',
   5 => 'last'
   );

%lang_text =
   (
   login      => 'Entrar',
   clear      => 'Esborrar',
   point      => 'Point',
   pixel      => 'Pixel',
   changepwd  => 'Canvia de Clau',
   viewhistory=> 'Mirar l´historial',
   of         => 'de',
   messages   => 'missatges',
   unread     => 'no llegit',
   nomessages => 'Carpeta buida',
   composenew => 'Enviar un nou missatge',
   refresh    => 'Actualitzar',
   userprefs  => 'Preferències personals',
   addressbook=> 'Llibre d´adreces',
   folders    => 'Carpetes',
   emptytrash => 'Paperera buida',
   totrash    => 'Envia a la paperera',
   forever    => 'Per sempre',
   userdef    => 'Definit per l`usuari',
   logout     => 'Sortir',
   page       => 'Pàgina',
   msgcopyconf=> '\'Està segur de voler copiar els missatges seleccionats?\'',
   copy       => 'Copiar',
   msgmoveconf=> '\'Està segur de moure els missatges seleccionats?\'',
   move       => 'Moure',
   markasread => 'Marcar com a llegit',
   markasunread => 'Marcar com a no llegit',
   dateformat => 'format de la data',
   date       => 'Data',
   recipient  => 'Per a',
   sender     => 'Qui ho envia',
   subject    => 'Títol',
   thread     => 'fil',
   size       => 'Mida',
   backto     => 'Tornar a',
   reply      => 'Contestar',
   replyall   => 'Contestar a tots',
   forward    => 'Reenviar',
   forwardasatt=>'Reenviar com a afegit',
   printfriendly=> 'Fàcil d´imprimir',
   from       => 'De',
   replyto    => 'Contestar a',
   to         => 'Per a',
   cc         => 'CC (còpia)',
   bcc        => 'CCO (còpia amagada)',
   simplehead => 'Capçalera simple',
   allhead    => 'Veure tota la capçalera',
   simpleattmode => 'Afegits senzills ',
   allattmode    => 'Veure tots els afegits',
   attachment => 'Arxius adjunts',
   type       => 'Tipus',
   filename   => 'Arxiu',
   encoding   => 'Codificant',
   description=> 'Descripció',
   download   => 'Descarregar',
   thisispartialmsg => 'Això es una part del missatge.',
   msgrebuild => 'Reconstrucció del missatge',
   editdraft  => 'Editar l´esborrany',
   savedraft  => 'Guardar l´esborrany',
   send       => 'Enviar',
   about      => 'Versió',
   close      => 'Tancar',
   cancel     => 'Cancel.lar',
   continue   => 'Continuar',
   loginagain => 'Tornar a entrar',
   exit       => 'sortir',
   for        => 'PER A',
   yourname   => 'El seu nom i cognom',
   save       => 'Guardar',
   add        => 'Afegir',
   folderrenprop => '\'Introdueixi un nou nom a aquesta carpeta\'',
   rename     => 'Tornat a anomenar',
   folderdelconf => '\'Està segur d´esborrar aquesta carpeta i el seu contingut?\'',
   markread   => 'MarkRead',
   foldermarkreadconf => '\'Are you going to mark read on all messages in this folder?\'',
   chkindex   => 'Comprovar els index',
   folderchkindexconf => '\'Segur que vols comprovar la carpeta?\'',
   reindex    => 'ReIndexar',
   folderreindexconf => '\'Segur que vols reindexar la carpeta?\'',
   total      => 'Total',
   delete     => 'Esborrar',
   reserve    => 'Reservar',
   clearadd   => 'Esborrar totes les adreces',
   importadd  => 'Importar  adreces',
   exportadd  => 'Exportar adreces',
   import     => 'Importar',
   addmod     => 'Afegir/Modificar',
   modify     => 'Modificar',
   abooktitle => 'Llibreta d´adreces',
   abook      => 'LLIBRETA D´ADRECES',
   name       => 'Nom',
   email      => 'Correul',
   note       => 'Nota',
   group      => 'Grup',
   quota_hit  => 'MÀXIMA MIDA PERMESA',
   usage      => 'Ús',
   tzmap      => 'World timezone map',
   editfroms  => 'Editar les adreces personals',
   pop3book   => 'Configuració POP3',
   retr_pop3s => 'Obtindre correu POP3',
   filterbook => 'Configuració dels filtres de correu',
   include    => 'que inclou',
   exclude    => 'que exclou',
   smtprelay  => 'Relé SMTP',
   header     => 'capçalera',
   body       => 'Cos',
   attfilename=> 'Nom del fitxer afegit',
   all        => 'Tot',
   enable     => 'Activar',
   disable    => 'Desactivar',
   filtered   => 'Filtrat',
   blockrelay => 'Bloquejar el relé SMTP',
   blockemail => 'Bloquejar correu',
   read       => 'Llegir',
   yourmsg    => 'El seu missatge',
   delivered  => 'Lliurat',
   wasreadon1 => 'Fou llegit el',
   wasreadon2 => '.',
   globaladdressbook => 'Llibre global d´adreces',
   globalfilterrule => 'Mesures de filtre globals',
   readonly   => 'Només lectura',
   textcontent=> 'Contingut del text',
   search     => 'Cercar',
   advsearch  => 'Advanced search',
   folder     => 'Folder',
   nofoldersel=> 'No Folder selected',
   showall    => 'Show All',
   spellcheck => 'Corregir ortografia',
   checkagain => 'Tornar-ho a revisar',
   finishchecking => 'Acabar la correcció',
   manuallyfix=> 'Arreglar-ho a mà',
   calendar   => 'Calendar',
   am         => 'am',
   pm         => 'pm',
   calfmt_year          => 'Year @@@YEAR@@@',
   calfmt_yearmonth     => '@@@MONTH_STR@@@ @@@YEAR@@@',
   calfmt_yearmonthday  => '@@@MONTH_STR@@@ @@@DAY@@@ @@@YEAR@@@',
   calfmt_yearmonthdaywday => '@@@MONTH_STR@@@ @@@DAY@@@ @@@YEAR@@@ @@@WEEKDAY_STR@@@',
   calfmt_hourminampm => '@@@HOURMIN@@@ @@@AMPM@@@',
   none       => 'None',
   moreitems  => 'more items',
   multieditconf => 'This item was added for multiple dates.\\nEditing it will change the item for all dates.\\nContinue with Edit?',
   multidelconf  => 'This item was added for multiple dates.\\nDeleting it will delete the item for all dates.\\nContinue with Delete?',
   ed         => 'Ed',
   del        => 'Del',
   noitemforthisday => 'No items for this day',
   today_only               => 'Today\'s date only',
   the_wday_of_thismonth    => 'The',
   the_wday_of_thismonth2   => 'of the month',
   every_wday_of_thismonth  => 'Every',
   every_wday_of_thismonth2 => 'this month'
   );

%lang_err =
   (
   has_illegal_chars => 'té caràcters il.legals!',
   couldnt_open      => 'No ho puc obrir',
   couldnt_locksh    => 'No puc bloquejar-ho en lectura',
   couldnt_lock      => 'No puc bloquejar-ho d´escriptura',
   couldnt_seek      => 'No puc trobar l´inici de',
   couldnt_close     => 'No ho puc tancar',
   disallowed_pop3   => 'Rebutjat pel servidor POP3 ',
   disallowed_client => 'No es pot connectar des d´aquest client',
   disallowed_receiverdomain => 'No pot enviar un correu a aquesta adreça',
   norootlogin       => 'Ho sento, accés a ROOT negat per  seguretat.',
   shouldnt_move_here=> 'No hauria de moure missatges fins aquí!',
   destination_folder=> 'Carpeta de destí',
   doesnt_exist      => 'no existeix!',
   foldername_long   => 'El nom de carpeta no pot ser de més de 16 caràcters!',
   folder_with_name  => 'La carpeta amb el nom',
   already_exists    => 'existeix!',
   cant_create_folder=> 'No puc crear la carpeta!',
   under_indexing    => 's´està indexant, provi-ho després',
   abook_invalid     => 'Ho sento, aquest arxiu no sembla un llibre d´adreces exportat des d´Outlook Express 5 en format CSV.  Assegureu-vos de veure´l en un editor de texts i que la primera línia sigui "Nombre,Dirección E-mail"',
   back              => 'enrera',
   tryagain          => 'i torni-ho a intentar.',
   abook_toobig      => 'Ho sento, ha excedit la mida límit per la seva llibreta d´adreces. ',
   cant_create_dir   => 'No puc crear el seu directori d´usuari!',
   folder_hitquota   => 'Ho sento, ha arribat al límit de quota i no puc guardar més missatges en cap carpeta. Només pot moure els missatges a la carpeta PAPERERA, i esborrar-los.',
   att_overlimit     => 'Ho sento, la mida del seu arxiu supera el límit permès, el qual és de',
   inv_msg_op        => 'Operació no vàlida pel missatge',
   inv_sessid        => 'La seva petició no inclou la corresponent GALETA Identificativa -- accés denegat!',
   no_endpart        => 'La part final no s´ha trobat',
   part_missing      => 'Algunes part s´han perdut',
   rebuild_fmterr    => 'error de format en el nou missatge',
   rebuild_sizeerr   => 'error de tamany al missatge nou',
   user_not_exist    => 'l´usuari no existeix',
   func_notsupported => 'Funció no suportada',
   auth_syserr       => 'Error d´autenticació',
   param_fmterr      => 'Error en el format dels paràmetres',
   pwd_incorrect     => 'Clau incorrecta',
   network_server_error => 'error de xarxa del servidor',
   sendmail_error    => 'Hi ha hagut un problema enviant el seu missatge. Vagi enrera, comprovi el missatge, i intenti-ho un altre cop.',
   at_char_not_allowed => 'The @ character is not allowed in this field.  Press browser back button and try again',
   badnum_in_days => 'bad number in consecutive days field'
   );

1;
