#!/usr/bin/perl -T

$lang_charset = 'iso-8859-1';

%lang_folders =
   (
   INBOX => 'ENTRADA',
   'saved-messages' => 'GUARDATS',
   'sent-mail'      => 'ENVIATS',
   'saved-drafts'   => 'ESBORRANYS',
   'mail-trash'     => 'PAPERERA',
   DELETE => '--ESBORRAR--'
   );

%lang_sortlabels =
   (
   status      => 'Estat (Primer els no llegits)',
   date        => 'Data (Primer els nous)',
   date_rev    => 'Data (Primer els vells)',
   sender      => 'Qui ho envia (Primer els nous)',
   sender_rev  => 'Qui ho envia (Primer els vells)',
   subject     => 'Títol (Primer els nous)',
   subject_rev => 'Títol (Primer els vells)',
   size        => 'Mida (Primer els grans)',
   size_rev    => 'Mida (Primer els petits)'
   );

%lang_prioritylabels =
   (
   normal      => 'Normal',
   urgent      => 'Urgent',
   'non-urgent'=> 'No Urgent'
   );

%lang_withoriglabels =
   (
   at_beginning => 'a l´inici',
   at_end      => 'al final',
   none        => 'cap'
   );

%lang_receiptlabels =
   (
   ask => 'Ask to confirm',
   yes => 'Yes',
   no  => 'No'
   );

%lang_timelabels =
   (
     10 => '10 minutes',
     30 => '30 minutes',
     60 => '60 minutes',
    120 => '2 hours',
    180 => '3 hours',
    360 => '6 hours',
    720 => '12 hours',
   1440 => '24 hours'
   );

%lang_text =
   (  
   login      => 'Entrar',
   clear      => 'Esborrar',
   changepwd  => 'Canvia de Clau',
   viewhistory=> 'Mirar l´historial',
   of         => 'de',
   messages   => 'missatges',
   unread     => 'no llegit',
   nomessages => 'Carpeta buida',
   composenew => 'Enviar un nou missatge',
   refresh    => 'Actualitzar',
   userprefs  => 'Preferències personals',
   addressbook=> 'Llibre d´adreces',
   folders    => 'Carpetes',
   emptytrash => 'Paperera buida',
   forever    => 'Per sempre',
   userdef    => 'Definit per l`usuari',
   logout     => 'Sortir',
   page       => 'Pàgina',
   msgcopyconf=> '\'Està segur de voler copiar els missatges seleccionats?\'',
   copy       => 'Copiar',
   msgmoveconf=> '\'Està segur de moure els missatges seleccionats?\'',
   move       => 'Moure',
   markasread => 'Marcar com a llegit',
   markasunread => 'Mark com a no llegit',
   dateformat => 'format de la data',
   date       => 'Data',
   recipient  => 'Per a',
   sender     => 'Qui ho envia',
   subject    => 'Títol',
   thread     => 'fil',
   size       => 'Mida',
   backto     => 'Tornar a',
   reply      => 'Contestar',
   replyall   => 'Contestar a tots',
   forward    => 'Reenviar',
   forwardasatt=>'Reenviar com a afegit',
   printfriendly=> 'Print friendly',
   from       => 'De',
   replyto    => 'Contestar a',
   to         => 'Per a',
   cc         => 'CC (còpia)',
   bcc        => 'CCO (còpia amagada)',
   simplehead => 'Capçalera simple',
   allhead    => 'Veure tota la capçalera',
   simpleattmode => 'Afegits senzills ',
   allattmode    => 'Veure tots els afegits',
   attachment => 'Arxius adjunts',
   type       => 'Tipus',
   filename   => 'Arxiu',
   encoding   => 'Codificant',
   description=> 'Description',
   download   => 'Descarregar',
   thisispartialmsg => 'Això es una part del missatge.',
   msgrebuild => 'Reconstrucció del missatge',
   editdraft  => 'Editar l´esborrany',
   savedraft  => 'Guardar l´esborrany',
   send       => 'Enviar',
   about      => 'About',
   close      => 'Close',
   cancel     => 'Cancel.lar',
   continue   => 'Continuar',
   loginagain => 'Login again',
   exit       => 'sortir',
   for        => 'PER A',
   yourname   => 'El seu nom i cognom',
   save       => 'Guardar',
   add        => 'Afegir',
   folderrenprop => '\'Introdueixi un nou nom a aquesta carpeta\'',
   rename     => 'Tornat a anomenar',
   folderdelconf => '\'Està segur d´esborrar aquesta carpeta i el seu contingut?\'',
   chkindex    => 'CheckIndex',
   folderchkindexconf => '\'Are you going to check the index of this folder?\'',
   reindex    => 'ReIndex',
   folderreindexconf => '\'Are you sure you want to reindex this folder?\'',
   total      => 'Total',
   delete     => 'Esborrar',
   reserve    => 'Reservar',
   clearadd   => 'Esborrar totes les adreces',
   importadd  => 'Importar  adreces',
   exportadd  => 'Exportar adreces',
   import     => 'Importar',
   addmod     => 'Afegir/Modificar',
   modify     => 'Modificar',
   abooktitle => 'Llibreta d´adreces',
   abook      => 'LLIBRETA D´ADRECES',
   name       => 'Nom',
   email      => 'Correul',
   note       => 'Nota',
   group      => 'Grup',
   quota_hit  => 'MÀXIMA MIDA PERMESA',
   usage      => 'Ús',
   editfroms  => 'Editar les adreces personals',
   pop3book   => 'Configuració POP3',
   retr_pop3s => 'Obtindre correu POP3',
   filterbook => 'Configuració dels filtres de correu',
   include    => 'que inclou',
   exclude    => 'que exclou',
   smtprelay  => 'Relé SMTP',
   header     => 'capçalera',
   body       => 'Cos',
   attfilename=> 'Nom del fitxer afegit',
   all        => 'Tot',
   enable     => 'Activar',
   disable    => 'Desactivar',
   filtered   => 'Filtered',
   blockrelay => 'Bloquejar el relé SMTP',
   blockemail => 'Bloquejar correu',
   read       => 'Llegir',
   yourmsg    => 'El seu missatge',
   delivered  => 'Lliurat',
   wasreadon1 => 'Fou llegit el',
   wasreadon2 => '.',
   globaladdressbook => 'Llibre global d´adreces',
   globalfilterrule => 'Mesures de filtre globals',
   readonly   => 'Només lectura',
   textcontent=> 'Contingut del text',
   search     => 'Cercar',
   spellcheck => 'Corregir ortografia',
   checkagain => 'Tornar-ho a revisar',
   finishchecking => 'Acabar la correcció',
   manuallyfix=> 'Arreglar-ho a mà'
   );

%lang_err = (
            has_illegal_chars => 'té caràcters il.legals!',
            couldnt_open      => 'No ho puc obrir',
            couldnt_locksh    => 'No puc bloquejar-ho en lectura',
            couldnt_lock      => 'No puc bloquejar-ho d´escriptura',
            couldnt_seek      => 'No puc trobar l´inici de',
            couldnt_close     => 'No ho puc tancar',
            disallowed_pop3   => 'Rebutjat pel servidor POP3 ',
            disallowed_client => 'You are not allowed to connect from this client',
            disallowed_receiverdomain => 'You are not allowed to send message to this email address',
            norootlogin       => 'Ho sento, accés a ROOT negat per  seguretat.',
            shouldnt_move_here=> 'No hauria de moure missatges fins aquí!',
            destination_folder=> 'Carpeta de destí',
            doesnt_exist      => 'no existeix!',
            foldername_long   => 'El nom de carpeta no pot ser de més de 16 caràcters!',
            folder_with_name  => 'La carpeta amb el nom',
            already_exists    => 'existeix!',
            cant_create_folder=> 'No puc crear la carpeta!',
            under_indexing    => 's´està indexant, provi-ho després',
            abook_invalid     => 'Ho sento, aquest arxiu no sembla un llibre d´adreces exportat des
d´Outlook Express 5 en format CSV.  Assegureu-vos de veure´l en un editor de texts i que la primera línia sigui "Nombre,Dirección E-mail"',
            back              => 'enrera',
            tryagain          => 'i torni-ho a intentar.',
            abook_toobig      => 'Ho sento, ha excedit la mida límit per la seva llibreta d´adreces. ',
            cant_create_dir   => 'No puc crear el seu directori d´usuari!',
            folder_hitquota   => 'Ho sento, ha arribat al límit de quota i no puc guardar
més missatges en cap carpeta. Només pot moure els missatges a la carpeta PAPERERA, i esborrar-los.',
            att_overlimit     => 'Ho sento, la mida del seu arxiu supera el límit permès, el qual
és de',
            inv_msg_op        => 'Operació no vàlida pel missatge',
            inv_sessid        => 'La seva petició no inclou la corresponent GALETA Identificativa -- accés denegat!',
            no_endpart        => 'La part final no s´ha trobat',
            part_missing      => 'Algunes part s´han perdut',
            rebuild_fmterr    => 'error de format en el nou missatge',
            rebuild_sizeerr   => 'error de tamany al missatge nou',
            user_not_exist    => 'l´usuari no existeix',
            func_notsupported => 'Funció no suportada',
            auth_syserr       => 'Error d´autenticació',
            param_fmterr      => 'Error en el format dels paràmetres',
            pwd_incorrect     => 'Clau incorrecta',
            network_server_error => 'error de xarxa del servidor',
            sendmail_error    => 'Hi ha hagut un problema enviant el seu missatge. Vagi enrera, comprovi el missatge, i intenti-ho un altre cop.'
            );

1;
