#!/usr/bin/perl -T

# Czech translation by Michal Drapak, michal@stavlib.hiedu.cz, 2001-NOV-8
#           changes by Jan Bilik, jan@bilik.org, 2002-JUN-6
# charset: iso-8859-2

%lang_folders =
   (
   INBOX => 'Pøijaté',
   'saved-messages' => 'Ulo¾ené',
   'sent-mail'      => 'Odeslané',
   'saved-drafts'   => 'Rozepsané',
   'mail-trash'     => 'Ko¹',
   'all'            => 'All',
   DELETE => '--SMAZAT--'
   );

%lang_sortlabels =
   (
   status      => 'Øadit podle stavu (Nepøeètené první)',
   date        => 'Øadit podle data (Nejnovìj¹í první)',
   date_rev    => 'Øadit podle data (Nejstar¹í první)',
   sender      => 'Øadit podle odesilatele (Nejnovìj¹í první)',
   sender_rev  => 'Øadit podle odesilatele (Nejstar¹í první)',
   subject     => 'Øadit podle pøedmìtu (Nejnovìj¹í první)',
   subject_rev => 'Øadit podle pøedmìtu (Nejstar¹í první)',
   size        => 'Øadit podle velikosti (Nejdel¹í první)',
   size_rev    => 'Øadit podle velikosti (Nejkrat¹í první)'
   );

%lang_prioritylabels =
   (
   normal      => 'Bì¾ná',
   urgent      => 'Vysoká',
   'non-urgent'=> 'Nízká'
   );

%lang_withoriglabels =
   (
   at_beginning => 'Na zaèátek',
   at_end      => 'Na konec',
   none        => 'Nevkládat'
   );

%lang_receiptlabels =
   (
   ask => 'Zeptat se',
   yes => 'Ano',
   no  => 'Ne'
   );

%lang_timelabels =
   (
     10 => '10 minut',
     30 => '30 minut',
     60 => '60 minut',
    120 => '2 hodiny',
    180 => '3 hodiny',
    360 => '6 hodin',
    720 => '12 hodin',
   1440 => '24 hodin'
   );

%lang_advsearchlabels =
   (
   contains    => 'contains',
   notcontains => 'does not contain',
   is          => 'is',
   isnot       => 'is not',
   startswith  => 'starts with',
   endswith    => 'ends with',
   regexp      => 'matches regexp(insensitive)',
   );

%lang_calendar = 
   (
   yearview  => 'Yearview',
   monthview => 'Monthview',
   weekview  => 'Weekview',
   dayview   => 'Dayview'
   );

%lang_month =
   (
   1  => 'January',
   2  => 'February',
   3  => 'March',
   4  => 'April',
   5  => 'May',
   6  => 'June',
   7  => 'July',
   8  => 'August',
   9  => 'September',
   10 => 'October',
   11 => 'November',
   12 => 'December'
   );

%lang_wday =
   (
   0 => 'Sunday',
   1 => 'Monday',
   2 => 'Tuesday',
   3 => 'Wednesday',
   4 => 'Thursday',
   5 => 'Friday',
   6 => 'Saturday'
   );

%lang_wday_abbrev =
   (
   week => 'WK',
   0 => 'S',
   1 => 'M',
   2 => 'T',
   3 => 'W',
   4 => 'T',
   5 => 'F',
   6 => 'S'
   );

%lang_order =
   (
   1 => '1st',
   2 => '2nd',
   3 => '3rd',
   4 => '4th',
   5 => 'last'
   );

%lang_text =
   (
   login      => 'Pøihlásit',
   clear      => 'Smazat',
   point      => 'Bodù',
   pixel      => 'Pixelù',
   changepwd  => 'Zmìna hesla',
   viewhistory=> 'Zobraz historii',
   of         => 'z',
   messages   => 'zpráv',
   unread     => 'nepøeètených',
   nomessages => '®ádné zprávy',
   composenew => 'Napsat novou zprávu',
   refresh    => 'Obnovit',
   userprefs  => 'U¾ivatelské nastavení',
   addressbook=> 'Adresáø',
   folders    => 'Správa slo¾ek',
   emptytrash => 'Vysypat Ko¹',
   totrash    => 'Pøesunout do Ko¹e',
   forever    => 'Napoøád',
   userdef    => 'U¾iv.def.',
   logout     => 'Odhlásit',
   page       => 'Strana',
   msgcopyconf=> '\'Jste si jisti, ¾e chcete zkopírovat vybrané zprávy?\'',
   copy       => 'Kopírovat',
   msgmoveconf=> '\'Jste si jisti ¾e chcete pøesunout vybrané zprávy?\'',
   move       => 'Pøesunout',
   markasread => 'Oznaèit jako pøeèteno',
   markasunread => 'Oznaèit jako nepøeèteno',
   dateformat => 'Formát datumu',
   date       => 'Datum',
   recipient  => 'Pøíjemce',
   sender     => 'Odesílatel',
   subject    => 'Pøedmìt',
   thread     => 'Vlákno',
   size       => 'Velikost',
   backto     => 'Zpìt',
   reply      => 'Odpovìdìt',
   replyall   => 'Odpovìdìt v¹em',
   forward    => 'Poslat dál',
   forwardasatt=>'Poslat jako pøílohu',
   printfriendly=> 'Formát pro tisk',
   from       => 'Od',
   replyto    => 'Kam odpovídat (pokud má být pro odpovìï pou¾ita jiná adresa) ',
   to         => 'Komu',
   cc         => 'Kopie',
   bcc        => 'Slepá kopie',
   simplehead => 'Zkrácené záhlaví',
   allhead    => 'Celé záhlaví',
   simpleattmode => 'Jednoduchá pøíloha',
   allattmode    => 'V¹echny pøílohy',
   attachment => 'Pøíloha',
   type       => 'Typ',
   filename   => 'Jméno souboru',
   encoding   => 'Kódování',
   description=> 'Popis',
   download   => 'Ulo¾it do souboru',
   thisispartialmsg => 'Tato zpráva se skládá z více èástí.',
   msgrebuild => 'Zrekonstruovat zprávu',
   editdraft  => 'Edituj rozepsané',
   savedraft  => 'Ulo¾ rozepsané',
   send       => 'Poslat',
   about      => 'O systému',
   close      => 'Zavøít',
   cancel     => 'Zru¹it',
   continue   => 'Pokraèovat',
   loginagain => 'Nové pøihlá¹ení',
   exit       => 'Konec',
   for        => 'u¾ivatele',
   yourname   => 'Va¹e jméno',
   save       => 'Ulo¾it',
   add        => 'Pøidat',
   folderrenprop => '\'Prosím vlo¾te nové jméno slo¾ky\'',
   rename     => 'Pøejmenovat',
   folderdelconf => '\'Jste si jisti, ¾e chcete smazat tuto slo¾ku vèetnì jejího obsahu?\'',
   markread   => 'Oznaèit jako pøeètené',
   foldermarkreadconf => '\'Chcete oznaèit v¹echny zprávy v této slo¾ce jako pøeètené?\'',
   chkindex   => 'Zkontrolovat index',
   folderchkindexconf => '\'Chcete zkontrolovat index této slo¾ky?\'',
   reindex    => 'Novì indexovat',
   folderreindexconf => '\'Jste si jist, ¾e chcete reindexovat tuto slo¾ku?\'',
   total      => 'Celkovì',
   delete     => 'Smazat',
   reserve    => 'Ponechat na serveru',
   clearadd   => 'Vymazat celý adresáø',
   importadd  => 'Pøidat do adresáøe',
   exportadd  => 'Exportovat adresáø',
   import     => 'Import',
   addmod     => 'Pøidat/Zmìnit',
   modify     => 'Zmìnit',
   abooktitle => 'Adresáø',
   abook      => 'ADRESÁØ',
   name       => 'Jméno',
   email      => 'E-mail',
   note       => 'Poznámka',
   group      => 'Skupina',
   quota_hit  => 'Vrchol kvóty',
   usage      => 'Vyu¾ití',
   tzmap      => 'World timezone map',
   editfroms  => 'Správa vlastních e-mailových adres',
   pop3book   => 'Správa POP3 úètù',
   retr_pop3s => 'Stáhnout po¹tu z POP3 úètù',
   filterbook => 'Definice filtrù po¹ty',
   include    => 'Vèetnì',
   exclude    => 'Mimo',
   smtprelay  => 'Zdrojový SMTP server',
   header     => 'Záhlaví',
   body       => 'Tìlo',
   attfilename=> 'Jméno soboru pøílohy',
   all        => 'V¹e',
   enable     => 'Aktivní',
   disable    => 'Neaktivní',
   filtered   => 'Filtrováno',
   blockrelay => 'Blokovat zdrojový SMTP server',
   blockemail => 'Blokovat adresu',
   read       => 'Pøeèteno',
   yourmsg    => 'Va¹e zpráva',
   delivered  => 'Doruèena',
   wasreadon1 => 'byla pøeètena',
   wasreadon2 => '.',
   globaladdressbook => 'Globální adresáø',
   globalfilterrule => 'Globální pravidla filtrování',
   readonly   => 'Jen pro ètení',
   textcontent=> 'Obsah textu',
   search     => 'Hledání',
   advsearch  => 'Advanced search',
   folder     => 'Folder',
   nofoldersel=> 'No Folder selected',
   showall    => 'Show All',
   spellcheck => 'Pravopis',
   checkagain => 'Pokraèovat v kontrole',
   finishchecking => 'Ukonèit kontrolu',
   manuallyfix=> 'Opravit ruènì',
   calendar   => 'Calendar',
   am         => 'am',
   pm         => 'pm',
   calfmt_year          => 'Year @@@YEAR@@@',
   calfmt_yearmonth     => '@@@MONTH_STR@@@ @@@YEAR@@@',
   calfmt_yearmonthday  => '@@@MONTH_STR@@@ @@@DAY@@@ @@@YEAR@@@',
   calfmt_yearmonthdaywday => '@@@MONTH_STR@@@ @@@DAY@@@ @@@YEAR@@@ @@@WEEKDAY_STR@@@',
   calfmt_hourminampm => '@@@HOURMIN@@@ @@@AMPM@@@',
   none       => 'None',
   moreitems  => 'more items',
   multieditconf => 'This item was added for multiple dates.\\nEditing it will change the item for all dates.\\nContinue with Edit?',
   multidelconf  => 'This item was added for multiple dates.\\nDeleting it will delete the item for all dates.\\nContinue with Delete?',
   ed         => 'Ed',
   del        => 'Del',
   noitemforthisday => 'No items for this day',
   today_only               => 'Today\'s date only',
   the_wday_of_thismonth    => 'The',
   the_wday_of_thismonth2   => 'of the month',
   every_wday_of_thismonth  => 'Every',
   every_wday_of_thismonth2 => 'this month'
   );

%lang_err =
   (
   has_illegal_chars => 'má nepovolené znaky!',
   couldnt_open      => 'Nepodaøilo se otevøít',
   couldnt_locksh    => 'Nepodaøilo se otevøít pro ètení',
   couldnt_lock      => 'Nepodaøilo se otevøít pro zápis',
   couldnt_seek      => 'Nepodaøilo se pøejít na zaèátek',
   couldnt_close     => 'Nelze zavøít',
   disallowed_pop3   => 'Nepovolený POP3 server',
   disallowed_client => 'Nemáte oprávnìní pøipojit se z tohoto klienta',
   disallowed_receiverdomain => 'Nemáte oprávnìní poslat zprávu na tuto adresu',
   norootlogin       => 'Pøihlá¹ení k úètu root není z bezpeènostních dùvodù povoleno.',
   shouldnt_move_here=> 'Sem byste se nemìli pokou¹et pøesouvat zprávy!',
   destination_folder=> 'Cílová slo¾ka',
   doesnt_exist      => 'neexistuje!',
   foldername_long   => 'Jméno slo¾ky nemù¾e pøesáhnout 16 znakù!',
   folder_with_name  => 'Slo¾ka s tímto názvem',
   already_exists    => 'ji¾ existuje!',
   cant_create_folder=> 'Slo¾ku nelze vytvoøit!',
   under_indexing    => 'je¹tì stále probíhá indexování, zkuste znovu pozdìji',
   abook_invalid     => 'Zdá se, ¾e tento soubor není slo¾kou adresáøe, exportované z Microsoft Outlook Express 5 jako soubor .CSV. Otevøete ho v textovém editoru a ujistìte se, ¾e první øádek má formát: "Name,E-mail Address" a poté pokraèujte.',
   back              => 'zpìt',
   tryagain          => 'a zkuste operaci opakovat.',
   abook_toobig      => 'Touto operací by do¹lo k pøekroèení kapacitního limitu Va¹eho adresáøe.',
   cant_create_dir   => 'Nelze vytvoøit Va¹i u¾ivatelskou slo¾ku!',
   folder_hitquota   => 'Dosáhli jste vrcholu kvóty a ¾ádná dal¹í zpráva ji¾ nemù¾e být do ¾ádné ze slo¾ek ulo¾ena. Nebudete moci pøesunout zprávu do jiné slo¾ky kromì Ko¹e, kde je mo¾no ji smazat. Sma¾te nìkteré zprávy nebo vyprázdnìte Ko¹ a zk uste operaci opakovat.',
   att_overlimit     => 'Velikost pøílohy pøekroèila kapacitní limit, který je',
   inv_msg_op        => 'Neplatná operace pro zprávu',
   inv_sessid        => 'Vá¹ po¾adavek neobsahoval odpovídající session ID cookie - pøístup odepøen!',
   no_endpart        => 'Závìreèná èást nenalezena',
   part_missing      => 'Nìkterá z èástí chybìla',
   rebuild_fmterr    => 'Nesprávný formát nové zprávy',
   rebuild_sizeerr   => 'Nesprávná velikost nové zprávy',
   user_not_exist    => 'U¾ivatel neexistuje',
   func_notsupported => 'Funkce není podporována',
   auth_syserr       => 'Chyba ovìøovacího systému',
   param_fmterr      => 'Chybný formát parametru',
   pwd_incorrect     => 'Chybné heslo',
   network_server_error => 'Sí»ová chyba serveru',
   sendmail_error    => 'Do¹lo k chybì pøi odesílání Va¹í zprávy. Stisknìte ve Va¹em prohlí¾eèi\'tlaèítko zpìt, zkontrolujte zprávu, a zkuste ji odeslat znovu.',
   at_char_not_allowed => 'The @ character is not allowed in this field.  Press browser back button and try again',
   badnum_in_days => 'bad number in consecutive days field'
   );

1;
