#!/usr/bin/perl -T

# Danish translation by Frank, frank.AT.post12.tele.dk
# charset: iso-8859-1

%lang_folders =
   (
   INBOX => 'Indbakke',
   'saved-messages' => 'Gemt mail',
   'sent-mail'      => 'Sendt mail',
   'saved-drafts'   => 'Kladder',
   'mail-trash'     => 'Papirkurv',
   'all'            => 'Alle',
   DELETE => '--Slet permanent--'
   );

%lang_sortlabels =
   (
   status      => 'Status (Ulæst mail først)',
   date        => 'Dato (Nyeste først)',
   date_rev    => 'Dato (Ældste først)',
   sender      => 'Afsender (Nyeste først)',
   sender_rev  => 'Afsender (Ældste først)',
   subject     => 'Emne (Nyeste først)',
   subject_rev => 'Emne (Ældste først)',
   size        => 'Størrelse (Den største først)',
   size_rev    => 'Størrelse (Den mindste først)'
   );

%lang_prioritylabels =
   (
   normal      => 'Normal',
   urgent      => 'Høj',
   'non-urgent'=> 'Lav'
   );

%lang_withoriglabels =
   (
   at_beginning => 'i starten',
   at_end      => 'i slutningen',
   none        => 'undlad'
   );

%lang_receiptlabels =
   (
   ask => 'Bekræft',
   yes => 'Ja',
   no  => 'Nej'
   );

%lang_timelabels =
   (
     10 => '10 minutter',
     30 => '30 minutter',
     60 => '60 minutter',
    120 => '2 timer',
    180 => '3 timer',
    360 => '6 timer',
    720 => '12 timer',
   1440 => '24 timer'
   );

%lang_advsearchlabels =
   (
   contains    => 'indeholder',
   notcontains => 'indeholder ikke',
   is          => 'er',
   isnot       => 'er ikke',
   startswith  => 'starter med',
   endswith    => 'ender på',
   regexp      => 'matcher regexp. (store og små bogstaver)',
   );

%lang_calendar = 
   (
   yearview  => 'Års oversigt',
   monthview => 'Måneds oversigt',
   weekview  => 'Uge oversigt',
   dayview   => 'Dags oversigt'
   );

%lang_month =
   (
   1  => 'Januar',
   2  => 'Februar',
   3  => 'Marts',
   4  => 'April',
   5  => 'Maj',
   6  => 'Juni',
   7  => 'Juli',
   8  => 'August',
   9  => 'September',
   10 => 'Oktober',
   11 => 'November',
   12 => 'December'
   );

%lang_wday =
   (
   0 => 'Søndag',
   1 => 'Mandag',
   2 => 'Tirsdag',
   3 => 'Onsdag',
   4 => 'Torsdag',
   5 => 'Fredag',
   6 => 'Lørdag'
   );

%lang_wday_abbrev =
   (
   week => 'Uge',
   0 => 'S',
   1 => 'M',
   2 => 'T',
   3 => 'O',
   4 => 'T',
   5 => 'F',
   6 => 'L'
   );

%lang_order =
   (
   1 => 'første',
   2 => 'anden',
   3 => 'tredie',
   4 => 'fjerde',
   5 => 'sidste'
   );

%lang_text =
   (
   login      => 'Log ind',
   clear      => 'Ryd',
   point      => 'punkt',
   pixel      => 'Pixel',
   changepwd  => 'Ændre adgangskode',
   viewhistory=> 'Vis historik',
   of         => 'af',
   messages   => 'mails',
   unread     => 'ulæste',
   nomessages => 'Ingen mails',
   composenew => 'Skriv ny mail',
   refresh    => 'Opdater',
   userprefs  => 'Standard indstillinger',
   addressbook=> 'Adressebog',
   folders    => 'Mappe oversigt',
   emptytrash => 'Tøm papirkurven',
   totrash    => 'Flyt til papirkurv',
   forever    => 'Aldrig',
   userdef    => 'Bruger defineret',
   logout     => 'Afslut webmail',
   page       => 'Side',
   msgcopyconf=> '\'Er du sikker på du vil kopiere de(n) valgte mails?\'',
   copy       => 'Kopier',
   msgmoveconf=> '\'Er du sikker på, at du vil flytte de(n) valgte mails?\'',
   move       => 'Flyt',
   markasread => 'Marker som læst',
   markasunread => 'Marker som ulæst',
   dateformat => 'Dato format',
   date       => 'Dato',
   recipient  => 'Modtager',
   sender     => 'Afsender',
   subject    => 'Emne',
   thread     => 'Tråd',
   size       => 'Størrelse',
   backto     => 'Tilbage til',
   reply      => 'Svar',
   replyall   => 'Svar alle',
   forward    => 'Videresend',
   forwardasatt=>'Videresend som vedhæftet fil',
   printfriendly=> 'Vis printer venlig udgave',
   from       => 'Fra',
   replyto    => 'Svar til',
   to         => 'Til',
   cc         => 'CC',
   bcc        => 'BCC',
   simplehead => 'Vis kort brevhoved',
   allhead    => 'Vis alle linier i brevhoved',
   simpleattmode => 'Simpel vedhæng',
   allattmode    => 'Alle vedhæng',
   attachment => 'Vedhæft fil',
   type       => 'Type',
   filename   => 'Filnavn',
   encoding   => 'Encoding',
   description=> 'Beskrivelse',
   download   => 'Gem',
   thisispartialmsg => 'Dette er en del af en mail.',
   msgrebuild => 'Besked genopbygget',
   editdraft  => 'Rediger kladde',
   savedraft  => 'Gem kladde',
   send       => 'Send mail',
   about      => 'Om',
   close      => 'Luk',
   cancel     => 'Fortryd',
   continue   => 'Fortsæt',
   loginagain => 'Log ind igen',
   exit       => 'Luk browser',
   for        => 'for',
   yourname   => 'Dit navn',
   save       => 'Gem',
   add        => 'Tilføj',
   folderrenprop => '\'Skriv venligst navnet på folderen\'',
   rename     => 'Omdøb',
   folderdelconf => '\'Er du sikker på, at du vil slette denne mappe og hele dens indhold?\'',
   markread   => 'Marker som læst',
   foldermarkreadconf => '\'Are you going to mark read on all messages in this folder?\'',
   chkindex   => 'Kontroller indeks',
   folderchkindexconf => '\'Vil du have indeks i denne folder kontrolleret?\'',
   reindex    => 'Genindekser',
   folderreindexconf => '\'Er du sikker på du vil genindeksere denne folder?\'',
   total      => 'Total',
   delete     => 'Slet',
   reserve    => 'Efterlad',
   clearadd   => 'Slet alle mailadresser',
   importadd  => 'Importer mailadresser til adressebog',
   exportadd  => 'Exporter mailadresser',
   import     => 'Importer',
   addmod     => 'Tilføj/Rediger',
   modify     => 'Rediger',
   abooktitle => 'Adressebog',
   abook      => 'ADRESSEBOG',
   name       => 'Navn',
   email      => 'Email',
   note       => 'Notat',
   group      => 'Gruppe',
   quota_hit  => 'ADVARSEL, din postkasse er fuld',
   usage      => 'ADVARSEL, din postkasse er snart fuld, du benytter nu:',
   tzmap      => 'Verdenskort med tidszoner',
   editfroms  => 'Rediger personlige mailadresser',
   pop3book   => 'Opsæt mail afhentning fra ekstern POP3 server',
   retr_pop3s => 'Hent mail fra ekstern POP3 server',
   filterbook => 'Filterregler',
   include    => 'Indeholder',
   exclude    => 'Indeholder IKKE',
   smtprelay  => 'SMTP server',
   header     => 'Brevhoved',
   body       => 'Brevtekst',
   attfilename=> 'Filnavn',
   all        => 'Alle felter',
   enable     => 'Aktiver',
   disable    => 'Deaktiver',
   filtered   => 'Filtreret',
   blockrelay => 'Bloker SMTP Server:',
   blockemail => 'Bloker mailadressen:',
   read       => 'Læst',
   yourmsg    => 'Din besked',
   delivered  => 'Leveret',
   wasreadon1 => 'blev læst d.',
   wasreadon2 => '.',
   globaladdressbook => 'GLOBAL ADRESSEBOG',
   globalfilterrule => 'GLOBALE FILTERREGLER',
   readonly   => 'Skrive beskyttet',
   textcontent=> 'Tekst indhold',
   search     => 'Søg',
   advsearch  => 'Avanceret søgning',
   folder     => 'Folder',
   nofoldersel=> 'Du skal vælge mindst én folder at søge i',
   showall    => 'Show All',
   spellcheck => 'Stavekontrol',
   checkagain => 'Check igen',
   finishchecking => 'Afslut stavekontrol',
   manuallyfix=> 'Manual rettelse',
   calendar   => 'Kalender',
   am         => 'am',
   pm         => 'pm',
   calfmt_year          => 'År @@@YEAR@@@',
   calfmt_yearmonth     => '@@@MONTH_STR@@@ @@@YEAR@@@',
   calfmt_yearmonthday  => '@@@DAY@@@ @@@MONTH_STR@@@ @@@YEAR@@@',
   calfmt_yearmonthdaywday => '@@@WEEKDAY_STR@@@ @@@DAY@@@ @@@MONTH_STR@@@ @@@YEAR@@@',
   calfmt_hourminampm => '@@@HOURMIN@@@ @@@AMPM@@@',
   none       => 'Hele dagen',
   moreitems  => 'more items',
   multieditconf => 'Dette er en tilbagevendende aftale. Ændringer af denne\\naftale, vil også ændre alle de tilbagevendende aftaler.\\nØnsker du at fortsætte?',
   multidelconf  => 'Dette er en tilbagevendende aftale. Hvis du sletter denne\\naftale, sletter du også de tilbagevendende aftaler.\\nØnsker du at fortsætte?',
   ed         => 'Rediger',
   del        => 'Slet',
   noitemforthisday => 'Ingen aftaler i dag',
   today_only               => 'Kun dags dato',
   the_wday_of_thismonth    => 'Den',
   the_wday_of_thismonth2   => 'i hver måned',
   every_wday_of_thismonth  => 'Hver',
   every_wday_of_thismonth2 => 'i denne måned'
   );

%lang_err =
   (
   has_illegal_chars => 'indeholder ugyldige tegn!',
   couldnt_open      => 'Kunne ikke åbne',
   couldnt_locksh    => 'Kunne ikke låse filen før læsning',
   couldnt_lock      => 'Kunne ikke låse',
   couldnt_seek      => 'Kunne ikke søge til starten af',
   couldnt_close     => 'Kunne ikke lukke',
   disallowed_pop3   => 'Ugyldig POP3 server',
   disallowed_client => 'Du har ikke tilladelse til at forbinde fra denne pc',
   disallowed_receiverdomain => 'Du har ikke tilladelse til at sende mail til denne mailadresse',
   norootlogin       => 'Beklager, rootlogin er slået fra af sikkerheds hensyn.',
   shouldnt_move_here=> 'Du kan ikke flytte mails hertil!',
   destination_folder=> 'Destinationsmappe',
   doesnt_exist      => 'findes ikke!',
   foldername_long   => 'Mappenavne kan ikke være længere end 16 tegn!',
   folder_with_name  => 'En mappe ved navn',
   already_exists    => 'eksisterer allerede!',
   cant_create_folder=> 'Kan ikke oprette mappe!',
   under_indexing    => 'er igang med at indeksere, prøv venligst senere',
   abook_invalid     => 'Denne fil ser desværre ikke ud til at være en adressebog fra Microsoft Outlook Express 5 i CSV-format. Check i en teksteditor, at den første linie starter med "Name, mailaddress", og gå ',
   back              => 'tilbage',
   tryagain          => 'og forsøg igen.',
   abook_toobig      => 'Dette vil gøre din adressebog større end tilladt. Gå',
   cant_create_dir   => 'Kan ikke oprette mappen!',
   folder_hitquota   => 'Beklager, du har brugt mere plads end tilladt, og der kan ikke gemmes flere mails. Du er nødt til at rydde op. Det er kun muligt at flyttet til papirkurven, hvor de vil blive slettet. Gå tilbage, slet nogle mails eller tøm papirkurven, og forsøg igen.',
   att_overlimit     => 'Dine vedhæftede filer er større end tilladt',
   inv_msg_op        => 'Ugyldig handling for besked',
   inv_sessid        => 'Din forespørgsel indeholdt ikke et gyldigt sessions ID - Ingen adgang!',
   no_endpart        => 'Slut besked ikke fundet',
   part_missing      => 'Flere dele blev ikke fundet',
   rebuild_fmterr    => 'Ny besked formatteret forkert',
   rebuild_sizeerr   => 'Ny besked størrelse passer ikke',
   user_not_exist    => 'bruger findes ikke',
   func_notsupported => 'funktion er ikke supporteret',
   auth_syserr       => 'godkendelse af systemet fejlede',
   param_fmterr      => 'parameter format fejlede',
   pwd_incorrect     => 'Ugyldig brugernavn eller adgangskode',
   network_server_error => 'server netværks fejl',
   sendmail_error    => 'Beklager, der skete en fejl ved afsendelse af din mail. Tryk Tilbage i din browser og prøv igen.',
   at_char_not_allowed => 'Du kan ikke benyttet @ i dette felt. Tryk på tilbage i din browser og prøv igen.',
   badnum_in_days => 'ugyldigt antal dage, for tilbagevendende aftale'
   );

1;
