#!/usr/bin/perl -T

# German translation by Andreas Roedl, flood.AT.flood-net.de
#                       Christian Schoepplein, mail.AT.schoeppi.net
# charset: iso-8859-1

%lang_folders =
   (
   INBOX => 'EINGANG',
   'saved-messages' => 'GESICHERT',
   'sent-mail'      => 'GESENDET',
   'saved-drafts'   => 'ENTWÜRFE',
   'mail-trash'     => 'PAPIERKORB',
   DELETE => '--LÖSCHEN--'
   );

%lang_sortlabels =
   (
   status      => 'Status (ungelesene zuerst)',
   date        => 'Datum (neueste zuerst)',
   date_rev    => 'Datum (älteste zuerst)',
   sender      => 'Absender (neueste zuerst)',
   sender_rev  => 'Absender (älteste zuerst)',
   subject     => 'Betreff (neueste zuerst)',
   subject_rev => 'Betreff (älteste zuerst)',
   size        => 'Größe (größte zuerst)',
   size_rev    => 'Größe (kleinste zuerst)'
   );

%lang_prioritylabels =
   (
   normal      => 'Normal',
   urgent      => 'Dringend',
   'non-urgent'=> 'Nicht dringend'
   );

%lang_withoriglabels =
   (
   at_beginning => 'Am Anfang der Nachricht',
   at_end      => 'Am Ende der Nachricht',
   none        => 'Nicht'
   );

%lang_receiptlabels =
   (
   ask => 'Nachfragen',
   yes => 'Ja',
   no  => 'Nein'
   );

%lang_timelabels =
   (
     10 => '10 Minuten',
     30 => '30 Minuten',
     60 => '60 Minuten',
    120 => '2 Stunden',
    180 => '3 Stunden',
    360 => '6 Stunden',
    720 => '12 Stunden',
   1440 => '24 Stunden'
   );

%lang_advsearchlabels =
   (
   contains    => 'beinhaltet',
   notcontains => 'beinhaltet nicht',
   is          => 'ist',
   isnot       => 'ist nicht',
   startswith  => 'beginnt mit',
   endswith    => 'endet mit',
   regexp      => 'gleicht Regexp',
   );

%lang_calendar = 
   (
   yearview  => 'Jahresübersicht',
   monthview => 'Monatsübersicht',
   weekview  => 'Wochenübersicht',
   dayview   => 'Tagesübersicht'
   );

%lang_month =
   (
   1  => 'Januar',
   2  => 'Februar',
   3  => 'März',
   4  => 'April',
   5  => 'Mai',
   6  => 'Juni',
   7  => 'Juli',
   8  => 'August',
   9  => 'September',
   10 => 'Oktober',
   11 => 'November',
   12 => 'Dezember'
   );

%lang_wday =
   (
   0 => 'Sonntag',
   1 => 'Montag',
   2 => 'Dienstag',
   3 => 'Mittwoch',
   4 => 'Donnerstag',
   5 => 'Freitag',
   6 => 'Samstag'
   );

%lang_wday_abbrev =
   (
   week => 'WK',
   0 => 'So',
   1 => 'Mo',
   2 => 'Di',
   3 => 'Mi',
   4 => 'Do',
   5 => 'Fr',
   6 => 'Sa'
   );

%lang_order =
   (
   1 => '1.',
   2 => '2.',
   3 => '3.',
   4 => '4.',
   5 => 'letzte'
   );

%lang_text =
   (
   login      => 'Anmelden',
   clear      => 'Löschen',
   point      => 'Point',
   pixel      => 'Pixel',
   changepwd  => 'Kennwort ändern',
   viewhistory=> 'Benutzerstatistik ansehen',
   of         => 'von',
   messages   => 'Nachrichten',
   unread     => 'ungelesen',
   nomessages => 'Keine Nachrichten',
   composenew => 'Neue Nachricht',
   refresh    => 'Aktualisieren',
   userprefs  => 'Benutzer Einstellungen',
   addressbook=> 'Adressbuch',
   folders    => 'Ordner Optionen',
   emptytrash => 'Papierkorb leeren',
   totrash    => 'In Papierkorb verschieben',
   forever    => 'für immer',
   userdef    => 'Benutzerdefiniert',
   logout     => 'Abmelden',
   page       => 'Seite',
   msgcopyconf=> '\'Sind Sie sicher, dass Sie die markierte(n) Nachricht(en) kopieren möchten?\'',
   copy       => 'Kopieren',
   msgmoveconf=> '\'Sind Sie sicher, dass Sie die markierte(n) Nachricht(en) verschieben möchten?\'',
   move       => 'Verschieben',
   markasread => 'Als gelesen markieren',
   markasunread => 'Als ungelesen markieren',
   dateformat => 'Datumsformat',
   date       => 'Datum',
   recipient  => 'Empfänger',
   sender     => 'Absender',
   subject    => 'Betreff',
   thread     => 'Diskusionsfaden',
   size       => 'Größe',
   backto     => 'Zurück zu',
   reply      => 'Antworten',
   replyall   => 'Allen Antworten',
   forward    => 'Weiterleiten',
   forwardasatt=>'Weiterleiten als Anhang',
   printfriendly=> 'Version zum Drucken',
   from       => 'Von',
   replyto    => 'Antwort-an',
   to         => 'An',
   cc         => 'CC',
   bcc        => 'BCC',
   simplehead => 'Kurzer Vorspann',
   allhead    => 'Originalvorspann',
   simpleattmode => 'Einfache Anhänge',
   allattmode    => 'Alle Anhänge',
   attachment => 'Anhang',
   type       => 'Typ',
   filename   => 'Dateiname',
   encoding   => 'Format',
   description=> 'Beschreibung',
   download   => 'Herunterladen',
   thisispartialmsg => 'Dies ist eine unvollständige Nachricht.',
   msgrebuild => 'Nachricht reformatieren',
   editdraft  => 'Entwurf bearbeiten',
   savedraft  => 'Entwurf speichern',
   send       => 'Senden',
   about      => 'Info',
   close      => 'Schließen',
   cancel     => 'Abbrechen',
   continue   => 'Weiter',
   loginagain => 'Erneut anmelden',
   exit       => 'Schließen',
   for        => 'FÜR',
   yourname   => 'Ihr Name',
   save       => 'Speichern',
   add        => 'Neu',
   folderrenprop => '\'Bitte geben Sie einen neuen Namen für diesen Ordner ein\'',
   rename     => 'Umbenennen',
   folderdelconf => '\'Sind Sie sicher, dass Sie diesen Ordner mit all seinen Inhalten löschen möchten?\'',
   markread   => 'Als gelesen markieren',
   foldermarkreadconf => '\'Möchten Sie wirklich alle Nachrichten in diesen Order als gelesen markieren?\'',
   chkindex   => 'Index prüfen',
   folderchkindexconf => '\'Soll der Index dieses Ordners überpüft werden?\'',
   reindex    => 'Reindizieren',
   folderreindexconf => '\'Sollen die Nachrichten dieses Ordners reindiziert werden?\'',
   total      => 'Gesamt',
   delete     => 'Löschen',
   reserve    => 'Reservieren',
   clearadd   => 'Alle Einträge löschen',
   importadd  => 'Adressbuch importieren',
   exportadd  => 'Adressbuch exportieren',
   import     => 'Importieren',
   addmod     => 'Neu/Bearbeiten',
   modify     => 'Bearbeiten',
   abooktitle => 'Adressbuch',
   abook      => 'ADRESSBUCH',
   name       => 'Name',
   email      => 'Email',
   note       => 'Anmerkung',
   group      => 'Gruppe',
   quota_hit  => 'SPEICHERPLATZLIMIT ÜBERSCHRITTEN',
   usage      => 'Verwendung',
   tzmap      => 'Zeitzonenkarte',
   editfroms  => 'Persönliche Email-Adressen bearbeiten',
   pop3book   => 'Postfächer bearbeiten',
   retr_pop3s => 'Nachrichten abholen',
   filterbook => 'Mail Filter Einstellungen',
   include    => 'inklusiv',
   exclude    => 'exklusiv',
   smtprelay  => 'SMTP Relay',
   header     => 'Vorspann',
   body       => 'Inhalt',
   attfilename=> 'Anhang',
   all        => 'Alles',
   enable     => 'aktivieren',
   disable    => 'deaktivieren',
   filtered   => 'Gefiltert',
   blockrelay => 'SMTP Relay blockieren',
   blockemail => 'Email-Adresse blockieren',
   read       => 'Gelesen',
   yourmsg    => 'Ihre Nachricht',
   delivered  => 'gesendet',
   wasreadon1 => 'wurde gelesen am',
   wasreadon2 => '.',
   globaladdressbook => 'Globales Adressbuch',
   globalfilterrule => 'Globale Filterregel',
   readonly   => 'Nur lesbar',
   textcontent=> 'Inhalt',
   search     => 'Suchen',
   advsearch  => 'Erweiterte Suche',
   folder     => 'Ordner',
   nofoldersel=> 'Kein Ordner gewählt',
   showall    => 'Alle anzeigen',
   spellcheck => 'Rechtschreibprüfung',
   checkagain => 'Erneut prüfen',
   finishchecking => 'Prüfung beenden',
   manuallyfix=> 'Manuell ändern',
   calendar   => 'Kalender',
   am         => 'am',
   pm         => 'pm',
   calfmt_year          => 'Jahr @@@YEAR@@@',
   calfmt_yearmonth     => '@@@MONTH_STR@@@ @@@YEAR@@@',
   calfmt_yearmonthday  => '@@@DAY@@@ @@@MONTH_STR@@@ @@@YEAR@@@',
   calfmt_yearmonthdaywday => '@@@DAY@@@ @@@MONTH_STR@@@ @@@YEAR@@@ @@@WEEKDAY_STR@@@',
   calfmt_hourminampm => '@@@HOURMIN@@@ @@@AMPM@@@',
   none       => 'Nichts',
   moreitems  => 'Weitere Einträge',
   multieditconf => 'Dieser Eintrag wurde für mehr als nur einen Tag angelegt.\\nDie erneute Bearbeitung wird sich auf alle diesen Eintrag zugeordneten Tage auswirken.\\nBearbeitung fortsetzen?',
   multidelconf  => 'Dieser Eintrag wurde für mehr als nur einen Tag angelegt.\\nDas Löschen dieses Eintrags wird sich auf alle diesen Eintrag zugeordneten Tage auswirken.\\nLöschen fortsetzen?',
   ed         => 'Edit',
   del        => 'Löschen',
   noitemforthisday => 'Kein Eintrag für diesen Tag',
   today_only               => 'Nur für diesen tag',
   the_wday_of_thismonth    => 'Für den @@@ORDER@@@ @@@WDAY@@@ dieses Monats',
   every_wday_of_thismonth  => 'Für jeden @@@WDAY@@@ dieses Monats'
   );

%lang_err =
   (
   has_illegal_chars => 'enthält unzulässige Zeichen',
   couldnt_open      => 'Fehler beim Öffnen der Datei',
   couldnt_locksh    => 'Fehler beim Sperren der Datei',
   couldnt_lock      => 'Fehler beim Schreiben der Datei',
   couldnt_seek      => 'Fehler beim Lesen der Datei',
   couldnt_close     => 'Fehler beim Schließen der Datei',
   disallowed_pop3   => 'Gesperrter POP3 Server',
   disallowed_clientip => 'Von dieser IP-Adresse aus ist der Zugriff nicht erlaubt',
   disallowed_receiverdomain => 'Emails an diese Domain sind nicht erlaubt',
   norootlogin       => 'Der Zugang für root ist aus Sicherheitsgründen deaktiviert!',
   shouldnt_move_here=> 'Sie können keine Nachrichten in diesen Ordner verschieben!',
   destination_folder=> 'Ziel Ordner',
   doesnt_exist      => 'existiert nicht!',
   foldername_long   => 'Der Ordnername darf maximal 16 Zeichen lang sein!',
   folder_with_name  => 'Ein Ordner mit dem Namen',
   already_exists    => 'existiert bereits!',
   cant_create_folder=> 'Fehler beim Erstellen des Ordners',
   under_indexing    => 'Indizierung - Bitte versuchen Sie es später nochmal.',
   abook_invalid     => 'Diese Datei scheint kein gültiges Outlook Express 5 CVS Format zu haben. Stellen Sie sicher, dass die erste Zeile der Datei "Name,E-mail Adresse" lautet. Gehen Sie dann',
   back              => 'zurück',
   tryagain          => 'und versuchen Sie es noch einmal',
   abook_toobig      => 'Diese Aktion würde die maximale Größe Ihres Adressbuches überschreiten. Versuchen Sie Speicherplatz frei zu machen. Gehen Sie dann',
   cant_create_dir   => 'Fehler beim Erstellen Ihres Benutzerverzeichnisses!',
   folder_hitquota   => 'Sie haben Ihr Speicherplatzlimit überschritten. Sie können keine weiteren Nachrichten mehr in Ihren Ordnern speichern. Nachrichten die in den Papierkorb verschoben werden, werden jetzt direkt gelöscht! Versuchen Sie ein paar Nachrichten zu löschen oder Ihren Papierkorb zu leeren um wieder mehr Speicherplatz zu Verfügung zu haben.',
   att_overlimit     => 'Der Dateianhang überschreitet die zugelassene Maximalgröße von',
   inv_msg_op        => 'Aktion für diese Nachricht nicht möglich',
   inv_sessid        => 'Ihre Anfrage enthält keine gültige Sitzungskennung -- Zugriff verweigert!',
   no_endpart        => 'End part nicht gefunden',
   part_missing      => 'Einige Teile wurden nicht gefunden',
   rebuild_fmterr    => 'Fehler mit neuem Nachrichtenformat',
   rebuild_sizeerr   => 'Neue Nachrichtengröße stimmt nicht',
   user_not_exist    => 'Benutzer existiert nicht',
   func_notsupported => 'Funktion nicht unterstützt',
   auth_syserr       => 'Fehler im Authentikationsystem',
   param_fmterr      => 'Fehler beim Parameterformat',
   pwd_incorrect     => 'Ungültiges Kennwort',
   network_server_error => 'Netzwerk Fehler',
   sendmail_error    => 'Das Absenden der Nachricht war leider nicht möglich. Drücken Sie auf den Zurück-Knopf Ihres Browsers, überprüfen Sie Ihre Nachricht und versuchen Sie es erneut.',
   at_char_not_allowed => 'Das @-Zeichen ist in diesem Eingabefeld nicht erlaubt. Klicken sie auf zurück und versuchen sie es erneut!',
   badnum_in_days => 'Falsche Zahl im Feld für die Tage'
   );

1;
