#!/usr/bin/perl -T

$lang_charset = 'iso-8859-1';

%lang_folders =
   (
   INBOX => 'EINGANG',
   SAVED => 'GESICHERT',
   SENT  => 'GESENDET',
   TRASH => 'PAPIERKORB'
   );

%lang_sortlabels =
   (
   status      => 'Status (Unread first)',
   date        => 'Datum (neueste zuerst)',
   date_rev    => 'Datum (älteste zuerst)',
   sender      => 'Absender (alphabetisch)',
   sender_rev  => 'Absender (rückwärts)',
   size        => 'Größe (größte zuerst)',
   size_rev    => 'Größe (kleinste zuerst)',
   subject     => 'Betreff (alphabetisch)',
   subject_rev => 'Betreff (rückwärts)'
   );

%lang_mualabels =
   (
   outlookexp5 => 'Outlook Express 5',
   nsmail      => 'Netscape Mail 4.x'
   );

%lang_text =
   (  
   login      => 'Anmelden',
   clear      => 'Löschen',
   of         => 'von',
   messages   => 'eMails',
   unread     => 'ungelesen',
   nomessages => 'keine eMails',
   composenew => 'neue eMail schreiben',
   refresh    => 'Aktualisieren',
   userprefs  => 'Benutzer Einstellungen',
   addressbook=> 'Adressbuch',
   folders    => 'Ordner Optionen',
   emptytrash => 'Müll leeren',
   logout     => 'Abmelden',
   page       => 'Seite',
   moveconfirm=> '\'Sind Sie sicher, dass Sie die markierte(n) eMail(s) verschieben möchten?\'',
   move       => 'Verschieben',
   date       => 'Datum',
   recipient  => 'Empfänger',
   sender     => 'Absender',
   subject    => 'Betreff',
   size       => 'Größe',
   backto     => 'Zurück zu',
   reply      => 'Antworten',
   replyall   => 'Allen Antworten',
   forward    => 'Weiterleiten',
   from       => 'Von',
   replyto    => 'Antwort-an',
   to         => 'An',
   cc         => 'CC',
   bcc        => 'BCC',
   simplehead => 'wichtige Header',
   allhead    => 'alle Header',
   simpleattmode => 'Simple attachments',
   allattmode    => 'All attachments',
   attachment => 'Anhang',
   type       => 'Typ',
   filename   => 'Dateiname',
   encoding   => 'Format',
   download   => 'Download',
   send       => 'Senden',
   cancel     => 'Abbrechen',
   continue   => 'Weiter',
   for        => 'FÜR',
   yourname   => 'Ihr Name',
   save       => 'Speichern',
   add        => 'Neu',
   folderconf => '\'Sind Sie sicher, dass Sie diesen Ordner mit all seinen Inhalten löschen möchten?\'',
   delete     => 'Löschen',
   importadd  => 'Adressbuch importieren',
   import     => 'Importieren',
   addmod     => 'Neu/Bearbeiten',
   abooktitle => 'Adressbuch',
   abook      => 'ADRESSBUCH',
   quota_hit  => 'SPEICHERPLATZLIMIT ÜBERSCHRITTEN',
   pop3book   => 'POP3 Setup',
   retr_pop3s => 'Retrieve POP3 Mail',
   filterbook => 'Mail Filter Setup',
   include    => 'Include',
   exclude    => 'Exclude',
   header     => 'Header',
   body       => 'Body',
   attfilename=> 'Attachment Filename',
   read       => 'Read',
   yourmsg    => 'Your message',
   delivered  => 'Delivered',
   wasreadon1 => 'was read on',
   wasreadon2 => '.',
   globaladdressbook => 'Global AddressBook',
   globalfilterrule => 'Global FilterRule',
   readonly   => 'ReadOnly',
   search     => 'Search'
   );

%lang_err = (
            has_illegal_chars => 'enthält unzulässige Zeichen!',
            couldnt_open      => 'Fehler beim Öffnen der Datei',
            couldnt_locksh    => 'Couldn\'t get read lock on',
            couldnt_lock      => 'Fehler beim Schreiben der Datei',
            couldnt_seek      => 'Fehler beim Lesen der Datei',
            couldnt_close     => 'Fehler beim Schließen der Datei',
            norootlogin       => 'Der root Zugang ist aus Sicherheitsgründen deaktiviert!',
            shouldnt_move_here=> 'Sie können keine eMails in diesen Ordner verschieben!',
            destination_folder=> 'Ziel Ordner',
            doesnt_exist      => 'existiert nicht!',
            foldername_long   => 'Der Ordnername darf maximal 16 Zeichen lang sein!',
            folder_with_name  => 'Ein Ordner mit dem Namen',
            already_exists    => 'existiert bereits!',
            cant_create_folder=> 'Fehler beim Erstellen des Ordners',
            abook_invalid     => 'Diese Datei scheint kein gültiges Outlook Express 5 CVS Format zu haben. Stellen Sie sicher, dass die erste Zeile der Datei "Name,E-mail Address" lautet. Gehen Sie dann',
            back              => 'zurück',
            tryagain          => 'und versuchen Sie es nocheinmal',
            abook_toobig      => 'Diese Aktion würde die maximale Größe Ihres Adressbuches überschreiten. Versuchen Sie Speicherplatz frei zu machen. Gehen Sie dann',
            cant_create_dir   => 'Fehler beim Erstellen Ihres Benutzerverzeichnisses!',
            folder_hitquota   => 'Sie haben Ihr Speicherplatzlimit überschritten. Sie können keine weiteren eMails mehr in Ihren Ordnern speichern. eMails die in den Müll verschoben werden, werden jetzt direkt gelöscht! Versuchen Sie ein paar eMails zu löschen oder Ihren Müll zu leeren um wieder mehr Speicherplatz zu Verfügung zu haben.',
            att_overlimit     => 'Der Dateianhang überschreitet die zugelassene Maximalgröße von',
            inv_sessid        => 'Your request didn\'t contain the proper session ID cookie -- access denied!',
            user_not_exist    => 'user does not exist',
            password_error    => 'wrong password',
            network_server_error => 'network server error'
            );

1;
