#!/usr/bin/perl

# Greek translation by Dimitris 'sehh' Michelinakis
# charset: iso-8859-7

%lang_folders =
   (
   INBOX => 'Εισερχόμενα',
   'saved-messages' => 'Σωσμένα',
   'sent-mail'      => 'Εξερχόμενα',
   'saved-drafts'   => 'Προσχέδιο',
   'mail-trash'     => 'Απορρίματα',
   DELETE => '--Διαγραφή--'
   );

%lang_sortlabels =
   (
   status      => 'Θέση (Πρώτα τα αδιάβαστα)',
   date        => 'Ημερομηνία (Πρώτα τα νέα)',
   date_rev    => 'Ημερομηνία (Πρώτα τα παλαιά)',
   sender      => 'Αποστολέας (Πρώτα τα νέα)',
   sender_rev  => 'Αποστολέας (Πρώτα τα παλαιά)',
   subject     => 'Θέμα (Πρώτα τα νέα)',
   subject_rev => 'Θέμα (Πρώτα τα παλαιά)',
   size        => 'Μέγεθος (Πρώτα τα μεγαλύτερα)',
   size_rev    => 'Μέγεθος (Πρώτα τα μικρότερα)'
   );

%lang_prioritylabels =
   (
   normal      => 'Κανονικά',
   urgent      => 'Επείγων',
   'non-urgent'=> 'Όχι επείγων'
   );

%lang_withoriglabels =
   (
   at_beginning => 'στήν αρχή',
   at_end      => 'στό τέλος',
   none        => 'Καθόλου'
   );

%lang_receiptlabels =
   (
   ask => 'Επαλήθευση',
   yes => 'Ναί',
   no  => 'Όχι'
   );

%lang_positionlabels =
   (
   before => 'Before mail edit area',
   after => 'After mail edit area',
   both  => 'Before and after mail edit area'
   );

%lang_timelabels =
   (
      3 => '3 λεπτά',
      5 => '5 λεπτά',
     10 => '10 λεπτά',
     20 => '20 λεπτά',
     30 => '30 λεπτά',
     60 => '60 λεπτά',
    120 => '2 ώρες',
    180 => '3 ώρες',
    360 => '6 ώρες',
    720 => '12 ώρες',
   1440 => '24 ώρες'
   );

%lang_advsearchlabels =
   (
   contains    => 'περιέχει',
   notcontains => 'δέν περιέχει',
   is          => 'είναι',
   isnot       => 'δέν είναι',
   startswith  => 'αρχίξει με',
   endswith    => 'τελειώνει με',
   regexp      => 'παρόμοιο με regexp',
   );

%lang_calendar = 
   (
   yearview  => 'Ετήσιο ημερολόγιο, ',
   monthview => 'Μηνιαίο ημερολόγιο, ',
   weekview  => 'Εβδομαδιαίο ημερολόγιο, ',
   dayview   => 'Ημερίσιο ημερολόγιο, ',
   listview   => 'Listview'
   );

%lang_month =
   (
   1  => 'Ιανουάριος',
   2  => 'Φεβρουάριος',
   3  => 'Μάρτιος',
   4  => 'Απρίλιος',
   5  => 'Μάϊος',
   6  => 'Ιούνιος',
   7  => 'Ιούλιος',
   8  => 'Άυγουστος',
   9  => 'Σεπτέμβριος',
   10 => 'Οκτόβριος',
   11 => 'Νοέμβριος',
   12 => 'Δεκέμβριος'
   );

%lang_wday =
   (
   0 => 'Κυριακή',
   1 => 'Δευτέρα',
   2 => 'Τρίτη',
   3 => 'Τετάρτη',
   4 => 'Πέμπτη',
   5 => 'Παρασκευή',
   6 => 'Σάββατο'
   );

%lang_wday_abbrev =
   (
   week => 'Εβ/δα',
   0 => 'Κυ',
   1 => 'Δε',
   2 => 'Τρ',
   3 => 'Τε',
   4 => 'Πε',
   5 => 'Πα',
   6 => 'Σαβ'
   );

%lang_order =
   (
   1 => '1η',
   2 => '2η',
   3 => '3η',
   4 => '4η',
   5 => 'τελευταία'
   );

%lang_text =
   (
   login      => 'Είσοδος',
   clear      => 'Εκκαθάριση',
   point      => 'Σημείο',
   pixel      => 'Πίξελ',
   changepwd  => 'Αλλαγή Κωδικού',
   viewhistory=> 'Ιστορικό',
   of         => 'από',
   messages   => 'μηνύματα',
   unread     => 'αδιάβαστα',
   nomessages => 'Κανένα μήνυμα',
   inmessages => 'Incoming msgs',
   composenew => 'Δημιουργία μηνύματος',
   refresh    => 'Ανανέωση',
   userprefs  => 'Προτιμήσεις',
   addressbook=> 'Κατάλογος διευθύνσεων',
   folders    => 'Φάκελος',
   emptytrash => 'Άδειασμα απορριμάτων',
   totrash    => 'Διαγραφή',
   forever    => 'Για πάντα',
   userdef    => 'Καθορισμός από τον χρήστη',
   logout     => 'Έξοδος',
   page       => 'Σελίδα',
   msgcopyconf=> '\'Επιβεβαίωση αντιγραφής επιλεγμένου(-νων) μηνύματος(-των);\'',
   copy       => 'Αντιγραφή',
   msgmoveconf=> '\'Επιβεβέωση μεταφοράς επιλεγμλένου(-νων) μηνύματος(-των);\'',
   move       => 'Μεταφορά',
   markasread => 'Σημάδεμα ως διαβασμένο',
   markasunread => 'Σημάδεμα ως αδιάβαστο',
   dateformat => 'Διάταξη ημερομηνίας',
   date       => 'Ημερομηνία',
   recipient  => 'Παραλήπτης',
   sender     => 'Αποστολέας',
   subject    => 'Θέμα',
   thread     => 'Νήμα',
   size       => 'Μέγεθος',
   backto     => 'Επιστροφή προς',
   reply      => 'Απάντηση',
   replyall   => 'Απάντηση σε όλους',
   forward    => 'Διαβίβαση',
   forwardasatt=>'Διαβίβαση σαν επισύναψη',
   printfriendly=> 'Προς εκτύπωση',
   from       => 'Από',
   replyto    => 'Απάντηση-προς',
   to         => 'Προς',
   cc         => 'CC',
   bcc        => 'BCC',
   simplehead => 'Simple headers',
   allhead    => 'All headers',
   simpleattmode => 'Απλή επισύναψη',
   allattmode    => 'Όλες οι επισυνάψοις',
   attachment => 'Επισύναψη',
   type       => 'Τύπος',
   filename   => 'Αρχείο',
   encoding   => 'Encoding',
   description=> 'Περιγραφή',
   download   => 'Download',
   charset    => 'Charset',
   samecharset=> 'The same as composing charset',
   thisispartialmsg => 'Ατελές μήνυμα',
   msgrebuild => 'Ανοικοδόμηση Μηνύματος',
   editdraft  => 'Επεξεργασία Προσχεδίου',
   savedraft  => 'Σώσιμο Προσχεδίου',
   send       => 'Αποστολή',
   about      => 'Πληροφορίες',
   close      => 'Κλείσιμο',
   cancel     => 'Ακύρωση',
   continue   => 'Συνέχεια',
   loginagain => 'Είσοδος',
   exit       => 'Έξοδος',
   for        => 'για',
   yourname   => 'Το Όνομα',
   save       => 'Σώσιμο',
   add        => 'Πρόσθεση',
   folderrenprop => '\'Please enter the new name for this folder\'',
   rename     => 'Μετονόμαση',
   folderdelconf => '\'Are you sure you want to delete this folder and all its contents?\'',
   markread   => 'Σημάδεμα/διαβασμένα',
   foldermarkreadconf => '\'Are you going to mark read on all messages in this folder?\'',
   chkindex   => 'Έλεγχος Index',
   folderchkindexconf => '\'Are you going to check the index of this folder?\'',
   reindex    => 'ReIndex',
   folderreindexconf => '\'Are you sure you want to reindex this folder?\'',
   total      => 'Συνολικό ποσό',
   delete     => 'Διαγραφή',
   reserve    => 'Εφεδρεία',
   clearadd   => 'Διαγραφή όλων των διευθύνσεων',
   importadd  => 'Εισαγωγή διευθύνσεων',
   exportadd  => 'Εξαγωγή διευθύνσεων',
   import     => 'Εισαγωγή',
   addmod     => 'Πρόσθεση/Τροποποίηση',
   modify     => 'Τροποποίηση',
   abooktitle => 'Κατάλογος διευθύνσεων',
   abook      => 'ΚΑΤΑΛΟΓΟΣ ΔΙΕΥΘΥΝΣΕΩΝ',
   name       => 'Όνομα',
   email      => 'Email',
   note       => 'Σημείωση',
   group      => 'Κατηγορία',
   quota_hit  => 'Υπέρβαση Ανώτατου Ορίου',
   usage      => 'Χρήση',
   tzmap      => 'Χάρτης της παγκόσμιας ωριαίας ζώνης',
   testsound  => 'Test sound',
   editfroms  => 'Επεξεργασία προσωπικών email διευθύνσεων',
   pop3book   => 'Προτιμήσεις POP3',
   retr_pop3s => 'Παραλαβή POP3 μηνημάτων',
   filterbook => 'Προτιμήσεις φίλτρων μηνυμάτων',
   include    => 'Περιλαμβάνω',
   exclude    => 'Αποκλείω',
   smtprelay  => 'SMTP Relay',
   header     => 'Επικεφαλίδα',
   body       => 'Σώμα',
   attfilename=> 'Αρχείο/Επισύναψη',
   all        => 'Όλα',
   enable     => 'Ενεργωποίηση',
   disable    => 'Απενεργοποίηση',
   filtered   => 'Φιλτραρισμένο',
   blockrelay => 'Φραγή SMTP Relay',
   blockemail => 'Φραγή email',
   read       => 'Ανάγνωση',
   yourmsg    => 'Το μήνυμα',
   delivered  => 'Απεστάλλει',
   wasreadon1 => 'διαβάστηκε στις',
   wasreadon2 => '.',
   globaladdressbook => 'Γενικός Κατάλογος διευθύνσεων',
   globalfilterrule => 'Γενικά φίλτρα μηνυμάτων',
   readonly   => 'ReadOnly',
   textcontent=> 'Κείμενο/Περιεχόμενο',
   search     => 'Αναζήτηση',
   advsearch  => 'Αναζήτηση για προχωρημένους',
   folder     => 'Φάκελος',
   nofoldersel=> 'Κανένας φάκελος δεν είναι επιλεγμένος',
   showall    => 'Εμφάνιση Όλων',
   spellcheck => 'Ορθογραφικός Έλεγχος',
   checkagain => 'Επανέλεγχος',
   finishchecking => 'Λήξη',
   manuallyfix=> 'Χειροκίνητη διόρθωση',
   editstat   => 'Edit Stationery',
   savestat   => 'Save Stationery',
   clearstat  => 'Clear All Stationery',
   selectstat => '-- Select Stationery for Reply --',
   calendar   => 'Ημερολόγιο',
   am         => 'πμ',
   pm         => 'μμ',
   calfmt_year          => 'Χρονιά @@@YEAR@@@',
   calfmt_yearmonth     => '@@@MONTH_STR@@@ @@@YEAR@@@',
   calfmt_yearmonthday  => '@@@DAY@@@ @@@MONTH_STR@@@ @@@YEAR@@@',
   calfmt_yearmonthdaywday => '@@@WEEKDAY_STR@@@ @@@DAY@@@, @@@MONTH_STR@@@ @@@YEAR@@@',
   calfmt_hourminampm => '@@@HOURMIN@@@ @@@AMPM@@@',
   none       => 'Καθόλου',
   moreitems  => 'περισσότερα αντικείμενα',
   multieditconf => 'This item was added for multiple dates.\\nEditing it will change the item for all dates.\\nContinue with Edit?',
   multidelconf  => 'This item was added for multiple dates.\\nDeleting it will delete the item for all dates.\\nContinue with Delete?',
   ed         => 'Επεξ/σία',
   del        => 'Διαγραφή',
   noitemforthisday => 'Καμία εγγραφή για σήμερα',
   today_only               => 'Σημερινή ημέρα',
   the_wday_of_thismonth    => 'Η @@@ORDER@@@ @@@WDAY@@@ του μήνα',
   every_wday_of_thismonth  => 'Κάθε @@@WDAY@@@ του μήνα'
   );

%lang_err =
   (
   has_illegal_chars => 'has illegal characters!',
   couldnt_open      => 'Couldn\'t open',
   couldnt_locksh    => 'Couldn\'t get read lock on',
   couldnt_lock      => 'Couldn\'t get write lock on',
   couldnt_seek      => 'Couldn\'t seek to the beginning of',
   couldnt_close     => 'Couldn\'t close',
   couldnt_updatedb  => 'Couldn\'t update index db ',
   disallowed_pop3   => 'Disallowed POP3 server',
   disallowed_client => 'You are not allowed to connect from this client',
   disallowed_receiverdomain => 'You are not allowed to send message to this email address',
   norootlogin       => 'Sorry, root login is disabled for security\'s sake.',
   shouldnt_move_here=> 'You shouldn\'t be trying to move messages here!',
   destination_folder=> 'Destination folder',
   doesnt_exist      => 'doesn\'t exist!',
   foldername_long   => 'Folder name cannot be more than 16 characters!',
   folder_with_name  => 'A folder with the name',
   already_exists    => 'already exists!',
   cant_create_folder=> 'Can\'t create folder!',
   under_indexing    => 'is still under indexing, please try later',
   abook_invalid     => 'Sorry, this file doesn\'t appear to be an address book exported from Microsoft Outlook Express 5 in CSV format.  Make sure that when viewing it in a text editor, the first line starts out "Name,E-mail Address", then go',
   back              => 'back',
   tryagain          => 'and try again.',
   abook_toobig      => 'Sorry, this would exceed the size limit for your address book.  Please go',
   cant_create_dir   => 'Can\'t create your user directory!',
   folder_hitquota   => 'Sorry, you\'ve hit your quota, and no more mail can be stored in your mail folders.  You will be unable to move messages anywhere but to the TRASH, where they will be deleted.  Go back, delete some messages or empty your trash, and try again.',
   folder_cutdone    => 'Warning, since the folderquota limit(@@@FOLDERQUOTA@@@) were hit, oldest messages in folders have been removed automatcially',
   att_overlimit     => 'Sorry, your attachments exceed the attachment size limit, which is',
   inv_msg_op        => 'Invalid operation for message',
   inv_sessid        => 'Your request didn\'t contain the proper session ID cookie -- access denied!',
   no_endpart        => 'End part not found',
   part_missing      => 'Some part was missing',
   rebuild_fmterr    => 'New message format error',
   rebuild_sizeerr   => 'New message size mismatch',
   user_not_exist    => 'user does not exist',
   func_notsupported => 'function not supported',
   auth_syserr       => 'authentication system error',
   param_fmterr      => 'parameter format error',
   pwd_incorrect     => 'Password incorrect',
   pwd_tooshort      => 'Password too short (minimum length @@@PASSWDMINLEN@@@)',
   pwd_toosimple     => 'Password too simple (both alphabet and digit are required)',
   network_server_error => 'network server error',
   sendmail_error    => 'Sorry, there was a problem sending your message.  Please click your browser\'s Back button, check your message, and try again.',
   at_char_not_allowed => 'The @ character is not allowed in this field.  Press browser back button and try again',
   badnum_in_days => 'bad number in consecutive days field'
   );

1;
