#!/usr/bin/perl -T

$lang_charset = 'iso-8859-1';

%lang_folders =
   (
   INBOX => 'ENTRADA',
   SAVED => 'GUARDADOS',
   SENT  => 'ENVIADOS',
   TRASH => 'PAPELERA'
   );

%lang_sortlabels =
   (
   status      => 'Status (Unread first)',
   date        => 'Fecha (Nuevos primero)',
   date_rev    => 'Fecha (Antiguos primero)',
   sender      => 'Remitente (Alfabético - Ascendente)',
   sender_rev  => 'Remitente (Alfabético - Descendente)',
   size        => 'Tamaño (Mayor primero)',
   size_rev    => 'Tamaño (Menor primero)',
   subject     => 'Asunto (Alfabético - Ascendente)',
   subject_rev => 'Asunto (Alfabético - Descendente)'
   );

%lang_mualabels =
   (
   outlookexp5 => 'Outlook Express 5',
   nsmail      => 'Netscape Mail 4.x'
   );

%lang_text =
   (  
   login      => 'Entrar',
   clear      => 'Resetear',
   of         => 'de',
   messages   => 'mensajes',
   unread     => 'no leido',
   nomessages => 'Carpeta vacida',
   composenew => 'Enviar nuevo mensaje',
   refresh    => 'Actualizar',
   userprefs  => 'Preferencias personales',
   addressbook=> 'Libreta de direcciones',
   folders    => 'Carpetas',
   emptytrash => 'Papelera vacida',
   logout     => 'Salir',
   page       => 'Página',
   moveconfirm=> '\'Esta seguro de querer mover los mensajes seleccionados?\'',
   move       => 'Mover',
   date       => 'Fecha',
   recipient  => 'Para',
   sender     => 'Remitente',
   subject    => 'Asunto',
   size       => 'Tamaño',
   backto     => 'Volver a',
   reply      => 'Contestar',
   replyall   => 'Contestar a todos',
   forward    => 'Re-Enviar',
   from       => 'De',
   replyto    => 'Contestar a',
   to         => 'Para',
   cc         => 'CC',
   bcc        => 'CCO',
   simplehead => 'Encabezado simple',
   allhead    => 'Todos los encabezados',
   simpleattmode => 'Simple attachments',
   allattmode    => 'All attachments',
   attachment => 'Archivos adjuntos',
   type       => 'Tipo',
   filename   => 'Archivo',
   encoding   => 'Codificando',
   download   => 'Descargar',
   send       => 'Enviar',
   cancel     => 'Cancelar',
   continue   => 'Continuar',
   for        => 'PARA',
   yourname   => 'Su Nombre y Apellido',
   save       => 'Guardar',
   add        => 'Agregar',
   folderconf => '\'Esta seguro de querer borrar esta carpeta y todo su contenido?\'',
   delete     => 'Borrar',
   importadd  => 'Importar direcciones',
   import     => 'Importar',
   addmod     => 'Agregar/Modificar',
   abooktitle => 'Libreta de direcciones',
   abook      => 'LIBRETA DE DIRECCIONES',
   quota_hit  => 'MAXIMO TAMAÑO PERMITIDO',
   pop3book   => 'POP3 Setup',
   retr_pop3s => 'Retrieve POP3 Mail',
   filterbook => 'Mail Filter Setup',
   include    => 'Include',
   exclude    => 'Exclude',
   smtprelay  => 'SMTP Relay',
   header     => 'Header',
   body       => 'Body',
   attfilename=> 'Attachment Filename',
   enable     => 'Enable',
   disable    => 'Disable',
   blockrelay => 'Block SMTP Relay',
   read       => 'Read',
   yourmsg    => 'Your message',
   delivered  => 'Delivered',
   wasreadon1 => 'was read on',
   wasreadon2 => '.',
   globaladdressbook => 'Global AddressBook',
   globalfilterrule => 'Global FilterRule',
   readonly   => 'ReadOnly',
   search     => 'Search'
   );

%lang_err = (
            has_illegal_chars => 'tiene caracteres ilegales!',
            couldnt_open      => 'No pude abrir',
            couldnt_locksh    => 'Couldn\'t get read lock on',
            couldnt_lock      => 'No pude bloquear escritura',
            couldnt_seek      => 'No pude encontrar el comienzo de',
            couldnt_close     => 'No pude cerrar',
            norootlogin       => 'Lo siento, acceso a cuenta de root está inhabilitada por razones de seguridad.',
            shouldnt_move_here=> 'No debería de tratar de mover mensajes hasta aquí!',
            destination_folder=> 'Carpeta de destino',
            doesnt_exist      => 'no existe!',
            foldername_long   => 'Nombre de carpeta no puede ser mayor a 16 caracteres!',
            folder_with_name  => 'La carpeta con el nombre',
            already_exists    => 'ya existe!',
            cant_create_folder=> 'No puedo crear carpeta!',
            abook_invalid     => 'Lo siento, este archivo no pareciera ser un libro de direcciones exportado desde Microsoft Outlook Express 5 en formato CSV.  Asegurese de ver este archivo en un editor de textos y que la primera línea comience con "Nombre,Dirección E-mail", entonces regrese',
            back              => 'atrás',
            tryagain          => 'y trate nuevamente.',
            abook_toobig      => 'Lo siento, se ha excedido del tamaño limite para su libreta de direcciones.  Por favor, regrese',
            cant_create_dir   => 'No puedo crear su directorio de usuario!',
            folder_hitquota   => 'Lo siento, usted llegó a su limite de quota y no puedo guardar más mensajes en ninguna carpeta. Sólo podrá mover los mensajes a la carpeta PAPELERA, donde seran borrados.  Regrese atrás, borre algunos mensajes ó vacie la Papelera y trate de nuevo.',
            att_overlimit     => 'Lo siento, el tamaño de su archivo excede el tamaño límite permitido, el cual es de',
            inv_sessid        => 'Your request didn\'t contain the proper session ID cookie -- access denied!',
            user_not_exist    => 'user does not exist',
            password_error    => 'wrong password',
            network_server_error => 'network server error'
            );

1;
