#!/usr/bin/perl

# Spanish translation by Javier Smaldone, jsmaldone.AT.yahoo.com
# charset: iso-8859-1

%lang_folders =
   (
   INBOX => 'ENTRADA',
   'saved-messages' => 'GUARDADOS',
   'sent-mail'      => 'ENVIADOS',
   'saved-drafts'   => 'BORRADOR',
   'mail-trash'     => 'PAPELERA',
   DELETE => '--BORRAR--'
   );

%lang_sortlabels =
   (
   status      => 'Estado (No leídos primero)',
   date        => 'Fecha (Nuevos primero)',
   date_rev    => 'Fecha (Antiguos primero)',
   sender      => 'Remitente (Nuevos primero)',
   sender_rev  => 'Remitente (Antiguos primero)',
   subject     => 'Asunto (Nuevos primero)',
   subject_rev => 'Asunto (Antiguos primero)',
   size        => 'Tamaño (Mayor primero)',
   size_rev    => 'Tamaño (Menor primero)'
   );

%lang_prioritylabels =
   (
   normal      => 'Normal',
   urgent      => 'Urgente',
   'non-urgent'=> 'No urgente'
   );

%lang_withoriglabels =
   (
   at_beginning => 'al principio',
   at_end      => 'al final',
   none        => 'ninguno'
   );

%lang_receiptlabels =
   (
   ask => 'Pedir confirmación',
   yes => 'Si',
   no  => 'No'
   );

%lang_positionlabels =
   (
   before => 'Before mail edit area',
   after => 'After mail edit area',
   both  => 'Before and after mail edit area'
   );

%lang_timelabels =
   (
      3 => '3 minutos',
      5 => '5 minutos',
     10 => '10 minutos',
     20 => '20 minutos',
     30 => '30 minutos',
     60 => '60 minutos',
    120 => '2 horas',
    180 => '3 horas',
    360 => '6 horas',
    720 => '12 horas',
   1440 => '24 horas'
   );

%lang_advsearchlabels =
   (
   contains    => 'contiene',
   notcontains => 'no contiene',
   is          => 'es',
   isnot       => 'no es',
   startswith  => 'comienza con',
   endswith    => 'termina con',
   regexp      => 'coincide con la expresión regular',
   );

%lang_calendar = 
   (
   yearview  => 'Vista anual',
   monthview => 'Vista mensual',
   weekview  => 'Vista semanal',
   dayview   => 'Vista diaria',
   listview   => 'Listview'
   );

%lang_month =
   (
   1  => 'Enero',
   2  => 'Febrero',
   3  => 'Marzo',
   4  => 'Abril',
   5  => 'Mayo',
   6  => 'Junio',
   7  => 'Julio',
   8  => 'Agosto',
   9  => 'Septiembre',
   10 => 'Octubre',
   11 => 'Noviembre',
   12 => 'Diciembre'
   );

%lang_wday =
   (
   0 => 'Domingo',
   1 => 'Lunes',
   2 => 'Martes',
   3 => 'Miércoles',
   4 => 'Jueves',
   5 => 'Viernes',
   6 => 'Sábado'
   );

%lang_wday_abbrev =
   (
   week => 'SE',
   0 => 'D',
   1 => 'L',
   2 => 'Ma',
   3 => 'Mi',
   4 => 'J',
   5 => 'V',
   6 => 'S'
   );

%lang_order =
   (
   1 => '1er',
   2 => '2do',
   3 => '3ro',
   4 => '4to',
   5 => 'último'
   );

%lang_text =
   (
   login      => 'Entrar',
   clear      => 'Restablecer',
   point      => 'Punto',
   pixel      => 'Pixel',
   changepwd  => 'Cambiar contraseña',
   viewhistory=> 'Ver Historial',
   of         => 'de',
   messages   => 'mensajes',
   unread     => 'no leído',
   nomessages => 'Carpeta vacía',
   inmessages => 'Incoming msgs',
   composenew => 'Enviar nuevo mensaje',
   refresh    => 'Actualizar',
   userprefs  => 'Preferencias personales',
   addressbook=> 'Libreta de direcciones',
   folders    => 'Carpetas',
   emptytrash => 'Vaciar Papelera',
   totrash    => 'Enviar a la Papelera',
   forever    => 'Para siempre',
   delatlogout=> 'Delete at Logout',
   userdef    => 'Definido por el usuario',
   logout     => 'Salir',
   page       => 'Página',
   msgcopyconf=> '\'¿Está seguro de querer copiar los mensajes seleccionados?\'',
   copy       => 'Copiar',
   msgmoveconf=> '\'¿Está seguro de querer mover los mensajes seleccionados?\'',
   move       => 'Mover',
   markasread => 'Marcar como leído',
   markasunread => 'Marcar como no leído',
   dateformat => 'Formato de fecha',
   date       => 'Fecha',
   recipient  => 'Para',
   sender     => 'Remitente',
   subject    => 'Asunto',
   thread     => 'Conversación',
   size       => 'Tamaño',
   backto     => 'Volver a',
   reply      => 'Responder',
   replyall   => 'Responder a todos',
   forward    => 'Reenviar',
   forwardasatt=>'Reenviar como archivo adjunto',
   printfriendly=> 'Versión imprimible',
   from       => 'De',
   replyto    => 'Responder a',
   to         => 'Para',
   cc         => 'CC (copia)',
   bcc        => 'CCO (copia oculta)',
   simplehead => 'Encabezado simple',
   allhead    => 'Todos los encabezados',
   simpleattmode => 'Archivos adjuntos simples',
   allattmode    => 'Todos los archivos adjuntos',
   attachment => 'Archivo adjunto',
   type       => 'Tipo',
   filename   => 'Archivo',
   encoding   => 'Codificación',
   description=> 'Descripción',
   download   => 'Descargar',
   charset    => 'Charset',
   samecharset=> 'The same as composing charset',
   thisispartialmsg => 'Este es un mensaje parcial.',
   msgrebuild => 'Reconstruir Mensaje',
   editdraft  => 'Editar borrador',
   savedraft  => 'Guardar borrador',
   send       => 'Enviar',
   about      => 'Acerca de',
   close      => 'Cerrar',
   cancel     => 'Cancelar',
   continue   => 'Continuar',
   loginagain => 'Volver a conectar',
   exit       => 'Salir',
   for        => 'para',
   yourname   => 'Su Nombre y Apellido',
   save       => 'Guardar',
   add        => 'Agregar',
   folderrenprop => '\'Por favor introduzca el nuevo nombre de esta carpeta\'',
   rename     => 'Renombrar',
   folderdelconf => '\'¿Está seguro de querer borrar esta carpeta y todo su contenido?\'',
   markread   => 'Marcar leído',
   foldermarkreadconf => '\'¿Desea marcar como leídos todos los mensajes de esta carpeta?\'',
   chkindex   => 'Verificar índice',
   folderchkindexconf => '\'¿Desea verificar el índice de esta carpeta?\'',
   reindex    => 'Re-indexar',
   folderreindexconf => '\'¿Desea reindexar esta carpeta?\'',
   total      => 'Total',
   delete     => 'Borrar',
   reserve    => 'Reservar',
   clearadd   => 'Borrar todas las direcciones',
   importadd  => 'Importar direcciones',
   exportadd  => 'Exportar direcciones',
   import     => 'Importar',
   addmod     => 'Agregar/Modificar',
   modify     => 'Modificar',
   abooktitle => 'Libreta de direcciones',
   abook      => 'LIBRETA DE DIRECCIONES',
   name       => 'Nombre',
   email      => 'Dirección',
   note       => 'Nota',
   group      => 'Grupo',
   quota_hit  => 'TAMAÑO MÁXIMO PERMITIDO',
   usage      => 'Uso',
   tzmap      => 'Mapa de zonas horarias',
   testsound  => 'Test sound',
   editfroms  => 'Editar direcciones de correo personales',
   pop3book   => 'Configuración POP3',
   retr_pop3s => 'Descargar correo POP3',
   filterbook => 'Configuración de los filtros de correo',
   include    => 'contenga',
   exclude    => 'no contenga',
   smtprelay  => 'SMTP Relay',
   header     => 'Cabecera',
   body       => 'Cuerpo',
   attfilename=> 'Nombe del archivo adjunto',
   all        => 'Todo',
   enable     => 'Activar',
   disable    => 'Desactivar',
   filtered   => 'Filtrado',
   blockrelay => 'Bloquear SMTP Relay',
   blockemail => 'Bloquear dirección',
   read       => 'Leer',
   yourmsg    => 'Su mensaje',
   delivered  => 'Entregado',
   wasreadon1 => 'fue leído en',
   wasreadon2 => '.',
   globaladdressbook => 'Libreta global de direcciones',
   globalfilterrule => 'Reglas globales de filtrado',
   readonly   => 'Sólo lectura',
   textcontent=> 'Contenido del texto',
   search     => 'Buscar',
   advsearch  => 'Búsqueda avanzada',
   folder     => 'Carpeta',
   nofoldersel=> 'No hay carpeta seleccionada',
   showall    => 'Mostrar todos',
   spellcheck => 'Corregir ortografía',
   checkagain => 'Comprobar de nuevo',
   finishchecking => 'Finalizar corrección',
   manuallyfix=> 'Arreglar manualmente',
   editstat   => 'Edit Stationery',
   savestat   => 'Save Stationery',
   clearstat  => 'Clear All Stationery',
   selectstat => '-- Select Stationery for Reply --',
   calendar   => 'Calendar',
   am         => 'am',
   pm         => 'pm',
   calfmt_year          => 'Año @@@YEAR@@@',
   calfmt_yearmonth     => '@@@MONTH_STR@@@ @@@YEAR@@@',
   calfmt_yearmonthday  => '@@@MONTH_STR@@@ @@@DAY@@@ @@@YEAR@@@',
   calfmt_yearmonthdaywday => '@@@MONTH_STR@@@ @@@DAY@@@ @@@YEAR@@@ @@@WEEKDAY_STR@@@',
   calfmt_hourminampm => '@@@HOURMIN@@@ @@@AMPM@@@',
   none       => 'Ninguno',
   moreitems  => 'más items',
   multieditconf => 'Este item fue agregado a múltiples fechas.\\nAl editarlo cambiará para todas las fechas\\n¿Desea continuar con la edición?',
   multidelconf	 => 'Este item fue agregado a múltiples fechas.\\nAl eliminarlo se quitará de todas las fechas\\n¿Desea eliminarlo?',
   ed         => 'Ed',
   del        => 'Borr',
   noitemforthisday => 'No hay items para este día',
   today_only               => 'Sólo de hoy',
   the_wday_of_thismonth    => 'El @@@ORDER@@@ @@@WDAY@@@ del mes',
   every_wday_of_thismonth  => 'Cada @@@WDAY@@@ este mes'
   );

%lang_err =
   (
   has_illegal_chars => '¡tiene caracteres ilegales!',
   couldnt_open      => 'No pude abrir',
   couldnt_locksh    => 'No pude bloquear para lectura',
   couldnt_lock      => 'No pude bloquear para escritura',
   couldnt_seek      => 'No pude encontrar el comienzo de',
   couldnt_close     => 'No pude cerrar',
   couldnt_updatedb  => 'Couldn\'t update index db ',
   disallowed_pop3   => 'Servidor POP3 no permitido',
   disallowed_client => 'No esta permitido conectarse desde este cliente',
   disallowed_receiverdomain => 'No tiene permiso para enviar un mensaje a esa dirección de correo',
   norootlogin       => 'Lo siento, acceso a cuenta de root está inhabilitada por razones de seguridad.',
   shouldnt_move_here=> 'No debería de tratar de mover mensajes hasta aquí!',
   destination_folder=> 'Carpeta de destino',
   doesnt_exist      => '¡no existe!',
   foldername_long   => '¡El nombre de la carpeta no puede ser mayor a 32 caracteres!',
   folder_with_name  => 'La carpeta con el nombre',
   already_exists    => '¡ya existe!',
   cant_create_folder=> '¡No puedo crear la carpeta!',
   under_indexing    => 'está aún indexándose, por favor intente después',
   abook_invalid     => 'Lo siento, este archivo no parece ser una libreta de direcciones exportada desde Microsoft Outlook Express 5 en formato CSV.  Asegurese de ver este archivo en un editor de textos y que la primera línea comience con "Nombre,Dirección E-mail", entonces regrese',
   back              => 'atrás',
   tryagain          => 'y trate nuevamente.',
   abook_toobig      => 'Lo siento, se ha excedido del tamaño límite para su libreta de direcciones.  Por favor, regrese',
   cant_create_dir   => '¡No puedo crear su directorio de usuario!',
   folder_hitquota   => 'Lo siento, usted llegó a su límite de espacio y no puedo guardar más mensajes en ninguna carpeta. Sólo podrá mover los mensajes a la carpeta PAPELERA, donde serán borrados.  Regrese atrás, borre algunos mensajes o vacíe la Papelera y trate de nuevo.',
   folder_cutdone    => 'Warning, since the folderquota limit(@@@FOLDERQUOTA@@@) were hit, oldest messages in folders have been removed automatcially',
   att_overlimit     => 'Lo siento, el tamaño de su archivo excede el tamaño límite permitido, el cual es de',
   inv_msg_op        => 'Operación no válida para el mensaje',
   inv_sessid        => 'Su petición no contiene la correspondiente Cookie de Identificación -- acceso denegado!',
   no_endpart        => 'Parte final no encontrada',
   part_missing      => 'Alguna parte se ha perdido',
   rebuild_fmterr    => 'Error en el formato del nuevo mensaje',
   rebuild_sizeerr   => 'El tamaño del nuevo mensaje no coincide',
   user_not_exist    => 'el usuario no existe',
   func_notsupported => 'función no soportada',
   auth_syserr       => 'error del sistema de autenticación',
   param_fmterr      => 'error en el formato de un parámetro',
   pwd_incorrect     => 'contraseña incorrecta',
   pwd_tooshort      => 'Password too short (minimum length @@@PASSWDMINLEN@@@)',
   pwd_toosimple     => 'Password too simple (both alphabet and digit are required)',
   network_server_error => 'error de red del servidor',
   sendmail_error    => 'Disculpe, hubo un problema enviando su mensaje. Por favor presione el botón Anterior de su navegador, compruebe su mensaje, e intente nuevamente.',
   at_char_not_allowed => 'El caracter @ no está permitido en este campo. Presione el botón Atrás de su navegador e intente nuevamente',
   badnum_in_days => 'número erróneo en el campo de días consecutivos'
   );

1;
