#!/usr/bin/perl

# French translation by Cyril Sabatier, c.sabatier.AT.bocquet.com
# charset: iso-8859-1

%lang_folders =
   (
   INBOX => 'Reçus',
   'saved-messages' => 'Enregistrés',
   'sent-mail'      => 'Envoyés',
   'saved-drafts'   => 'Brouillons',
   'mail-trash'     => 'Poubelle',
   DELETE => '-- SUPPRIMER --'
   );

%lang_sortlabels =
   (
   status      => 'Status (Non lus d\'abord)',
   date        => 'Date (Le plus récent d\'abord)',
   date_rev    => 'Date (Le plus ancien d\'abord)',
   sender      => 'Expéditeur (Le plus récent d\'abord)',
   sender_rev  => 'Expéditeur (Le plus ancien d\'abord)',
   subject     => 'Sujet (Le plus récent d\'abord)',
   subject_rev => 'Sujet (Le plus ancien d\'abord)',
   size        => 'Taille (Le plus gros d\'abord)',
   size_rev    => 'Taille (Le plus petit d\'abord)'
   );

%lang_prioritylabels =
   (
   normal      => 'Normal',
   urgent      => 'Urgent',
   'non-urgent'=> 'Non-Urgent'
   );

%lang_withoriglabels =
   (
   at_beginning => 'Au début',
   at_end      => 'A la fin',
   none        => 'Ne pas l\'insérer'
   );

%lang_receiptlabels =
   (
   ask => 'Demander confirmation',
   yes => 'Oui',
   no  => 'Non'
   );

%lang_ctrlpositionlabels =
   (
   top => 'En haut',
   bottom => 'En bas'
   );

%lang_sendpositionlabels =
   (
   before => 'Avant la zone d\'édition du mail',
   after => 'Après la zone d\'édition du mail',
   both  => 'Avant et après la zone d\'édition du mail'
   );

%lang_abookbuttonpositionlabels = 
   (
   before => 'Before addressbook entries',
   after  => 'After addressbook entries',
   both   => 'Before and after addressbook entries'
   );

%lang_timelabels =
   (
      3 => '3 minutes',
      5 => '5 minutes',
     10 => '10 minutes',
     20 => '20 minutes',
     30 => '30 minutes',
     60 => '60 minutes',
    120 => '2 heures',
    180 => '3 heures',
    360 => '6 heures',
    720 => '12 heures',
   1440 => '24 heures'
   );

%lang_advsearchlabels =
   (
   contains    => 'contient',
   notcontains => 'ne contient pas',
   is          => 'est',
   isnot       => 'n\'est pas',
   startswith  => 'commencer par',
   endswith    => 'terminer par',
   regexp      => 'expression régulière',
   );

%lang_sizes =
   (
   mb   => 'Mo',	# mega bytes
   kb   => 'Ko',	# kilo bytes
   byte => 'Octets'
   );

%lang_calendar = 
   (
   yearview  => 'Vue par année',
   monthview => 'Vue par mois',
   weekview  => 'Vue par semaine',
   dayview   => 'Vue par jour',
   listview  => 'Liste'
   );

%lang_month =
   (
   1  => 'Janvier',
   2  => 'Février',
   3  => 'Mars',
   4  => 'Avril',
   5  => 'Mai',
   6  => 'Juin',
   7  => 'Juillet',
   8  => 'Août',
   9  => 'Septembre',
   10 => 'Octobre',
   11 => 'Novembre',
   12 => 'Décembre'
   );

%lang_wday =
   (
   0 => 'Dimanche',
   1 => 'Lundi',
   2 => 'Mardi',
   3 => 'Mercredi',
   4 => 'Jeudi',
   5 => 'Vendredi',
   6 => 'Samedi'
   );

%lang_wday_abbrev =
   (
   week => 'Sem',
   0 => 'Di',
   1 => 'Lu',
   2 => 'Ma',
   3 => 'Me',
   4 => 'Je',
   5 => 'Ve',
   6 => 'Sa'
   );

%lang_order =
   (
   1 => '1 er',
   2 => '2 ème',
   3 => '3 ème',
   4 => '4 ème',
   5 => 'dernier'
   );

%lang_wdbutton =
   (
   refresh  => 'Rafraîchir',
   preview  => 'Apperçu', 
   edit     => 'Editer',
   listarchive=> 'Lister',
   decompress=>'Decompresser',
   extract  => 'Extraire',
   chdir    => 'Ch. Rép.',
   mkdir    => 'Créer Rép.',
   newfile  => 'Nouv. Fic.',
   delete   => 'Effacer',
   copy     => 'Copier',
   move     => 'Déplacer',
   gzip     => 'Créer gz',
   mkzip    => 'Créer zip',
   mktgz    => 'Créer tgz',
   mkthumbnail  => 'Créer thumbnail', 
   download => 'Télécharger',
   upload   => 'Envoyer',
   );   

%lang_text =
   (
   login      => 'Entrer',
   clear      => 'Effacer',
   point      => 'Points',
   pixel      => 'Pixels',
   changepwd  => 'Changer mot de passe',
   viewhistory=> 'Historique',
   of         => 'de',
   messages   => 'messages',
   unread     => 'non lu(s)',
   nomessages => 'Pas de messages',
   inmessages => 'Messages reçus',
   composenew => 'Composer un nouveau message',
   refresh    => 'Rafraîchir',
   userprefs  => 'Préférences Utilisateur',
   addressbook=> 'Carnet d\'adresses',
   folders    => 'Dossiers',
   emptytrash => 'Vider la poubelle',
   totrash    => 'Mettre à la poubelle',
   forever    => 'Toujours',
   delatlogout=> 'Effacer à la déconnexion',
   userdef    => 'Personnaliser',
   logout     => 'Déconnecter',
   page       => 'Page',
   msgcopyconf=> '\'Êtes-vous sûr(e) de vouloir copier le(s) message(s) sélectionné(s)?\'',
   copy       => 'Copier',
   msgmoveconf=> '\'Êtes-vous sûr(e) de vouloir déplacer le(s) message(s) sélectionné(s) ?\'',
   move       => 'Déplacer',
   markasread => 'Marquer comme \'Lu\'',
   markasunread => 'Marquer comme \'Non-Lu\'',
   dateformat => 'Format de date',
   date       => 'Date',
   recipient  => 'Destinataire',
   sender     => 'Expéditeur',
   subject    => 'Sujet',
   thread     => 'Tâche',
   size       => 'Taille',
   backto     => 'Retour à',
   reply      => 'Répondre',
   replyall   => 'Répondre à tous',
   forward    => 'Faire suivre',
   forwardasatt=>'Faire suivre en tant qu\'attachement',
   printfriendly=> 'Impression amicale',
   from       => 'Expéditeur',
   replyto    => 'Répondre à',
   to         => 'Destinataire',
   cc         => 'Copie',
   bcc        => 'Copie Cachée',
   simplehead => 'En-tête simplifié',
   allhead    => 'En-tête complet',
   simpleattmode => 'attachements simples',
   allattmode    => 'Tous les attachements',
   attachment => 'Pièce attachée',
   type       => 'Type',
   filename   => 'Nom de fichier',
   encoding   => 'Encodage',
   description=> 'Description',
   download   => 'Télécharger',
   charset    => 'Jeu de caractères',
   samecharset=> 'Le même que celui d\'édition',
   thisispartialmsg => 'Ceci est un message partiel.',
   msgrebuild => 'Message reconstruit',
   editdraft  => 'Editer brouillon',
   savedraft  => 'Enregistrer brouillon',
   send       => 'Envoyer',
   about      => 'A propos',
   close      => 'Fermer',
   cancel     => 'Annuler',
   ok         => 'Ok',
   continue   => ' OK ',
   loginagain => 'Se reconnecter',
   exit       => 'Quitter',
   for        => 'pour',
   yourname   => 'Votre nom',
   save       => 'Enregistrer',
   add        => 'Ajouter',
   folderrenprop => '\'Entrez un nouveau nom pour ce dossier\'',
   rename     => 'Renommer',
   folderdelconf => '\'Êtes-vous sûr(e) de vouloir détruire ce dossier et tout son contenu ?\'',
   markread   => 'Marquer comme lu',
   foldermarkreadconf => '\'Êtes-vous sûr(e) de vouloir marquer tous les messages de ce dossier comme lus ?\'',
   chkindex   => 'Vérifier l\'index',
   folderchkindexconf => '\'Êtes-vous sûr(e) de vouloir vérifier l\'index de ce dossier ?\'',
   reindex    => 'Réindexer',
   folderreindexconf => '\'Êtes-vous sûr(e) de vouloir réindexer ce dossier ?\'',
   total      => 'Total',
   edit       => 'Editer',
   delete     => 'Effacer',
   reserve    => 'Réserve',
   clearadd   => 'Effacer toutes les adresses',
   importadd  => 'Importer adresses',
   exportadd  => 'Exporter adresses',
   import     => 'Importer',
   addmod     => 'Ajouter/Modifier',
   modify     => 'Modifier',
   abooktitle => 'Carnet d\'adresses ',
   abook      => 'Carnet d\'adresses',
   name       => 'Nom',
   email      => 'Email',
   note       => 'Commentaire',
   max        => 'Maximum',
   group      => 'Groupe',
   quota_hit  => 'QUOTA ATTEINT',
   usage      => 'Utilisation',
   tzmap      => 'Fuseaux horaires',
   testsound  => 'Test audio',
   editfroms  => 'Editer vos adresses mails personnelles',
   pop3book   => 'Configuration POP3',
   retr_pop3s => 'Rapatrier mails POP3',
   filterbook => 'Configuration du filtre de mails',
   include    => 'contient',
   exclude    => 'ne contient pas',
   smtprelay  => 'Relais SMTP',
   header     => 'Entête',
   body       => 'Corps du Message',
   attfilename=> 'Nom de fichier(s)',
   all        => 'Tous',
   enable     => 'Actif',
   disable    => 'Inactif',
   filtered   => 'Filtré',
   blockrelay => 'Bloquer le relais SMTP',
   blockemail => 'Bloquer les emails',
   read       => 'Lu',
   yourmsg    => 'Votre message',
   delivered  => 'Distribué',
   wasreadon1 => 'a été lu',
   wasreadon2 => '.',
   globaladdressbook => 'Carnet d\'Adresses Global',
   globalfilterrule => 'Règles de Filtrage Globales',
   readonly   => 'Lecture seule',
   textcontent=> 'Message',
   search     => 'Chercher',
   advsearch  => 'Recherche avancée',
   folder     => 'Dossier',
   nofoldersel=> 'aucun dossier sélectionné',
   showall    => 'Afficher tout',
   spellcheck => 'Vérif. Orth.',
   checkagain => 'Vérif. encore',
   finishchecking => 'Fin vérif.',
   manuallyfix=> 'Correction manuelle',
   editstat   => 'Editer modèle de documents',
   savestat   => 'Sauver modèle de documents',
   clearstat  => 'Effacer tous les modèles de documents',
   statreply  => '-- Modèle de documents pour répondre --',
   calendar   => 'Calendrier',
   am         => 'am',
   pm         => 'pm',
   calfmt_year          => 'Année @@@YEAR@@@',
   calfmt_yearmonth     => '@@@MONTH_STR@@@ @@@YEAR@@@',
   calfmt_yearmonthday  => '@@@DAY@@@ @@@MONTH_STR@@@ @@@YEAR@@@',
   calfmt_yearmonthdaywday => '@@@WEEKDAY_STR@@@ @@@DAY@@@ @@@MONTH_STR@@@ @@@YEAR@@@',
   calfmt_hourminampm => '@@@HOURMIN@@@ @@@AMPM@@@',
   none       => 'Aucun',
   moreitems  => 'plus d\'éléments',
   multieditconf => 'Cet élément a été ajouté pour des dates multiples.\\nSi vous le modifiez l\'élément sera modifié pour toutes les autres dates.\\nContinuer?',
   multidelconf  => 'Cet élément a été ajouté pour des dates multiples.\\nSi vous l\'effacez l\'élément sera effacé pour toutes les autres dates.\\nContinuer?',
   noitemforthisday => 'Aucun élément pour cette journée',
   thisday_only          => 'La date d\'aujourd\'hui uniquement',
   the_wday_of_thismonth => 'le @@@ORDER@@@ @@@WDAY@@@ du mois',
   every_wday_thismonth  => 'chaque @@@WDAY@@@ de ce mois',
   thismonth_only           => 'Seulement ce mois', 
   every_oddmonth_thisyear  => 'Tous les mois impairs de cette année',
   every_evenmonth_thisyear => 'Tous les mois pairs de cette année',
   every_month_thisyear     => 'Tous les mois de cette année',
   webdisk      => 'WebDisk',
   sshterm      => 'Terminal SSH',
   dir          => 'Répertoire',
   dirs         => 'Répertoires',
   file         => 'fichier',
   files        => 'fichiers',
   program      => 'Programme',
   dest_of_chdir  => 'répertoire de destination',
   name_of_newdir => 'le nom du répertoire à créer',
   name_of_newfile=> 'le nom du fichier à créer',
   dest_of_thecopy=> 'le nom du répertoire ou du fichier de destination pour la copie',
   dest_of_themove=> 'le nom du répertoire ou du fichier de destination pour le déplacement',
   dest_of_thezip=> 'le nom du fichier de destination pour le nouveau zip',
   dest_of_thetgz=> 'le nom du fichier de destination pour le nouveau tgz',
   homedir      => 'Répertoire de base',
   showthumbnail    => 'Thumbnails',
   showhidden   => 'Voir fichiers cachés',
   lastmodified => 'Date de modification',
   perm         => 'Perm.',
   permission   => 'Access Permission',
   noitemfound  => 'Pas d'objet trouvé',
   savefile     => 'Fichier sauvé',
   succeeded    => 'avec succès',
   failed       => 'avec des erreurs',
   savefile_towd=> 'Sauver fichier vers le WebDisk',
   saveatt_towd => 'Sauver l\'attachement vers le WebDisk',
   addatt_fromwd=> 'Ajouter un attachement à partir du WebDisk'
   );

%lang_err =
   (
   has_illegal_chars => 'a des caractères illégaux !',
   couldnt_open      => 'Ouverture impossible de ',
   couldnt_locksh    => 'Impossible d\'établir un verrou de lecture',
   couldnt_lock      => 'Protection en écriture de ',
   couldnt_seek      => 'Recherche impossible vers le début de',
   couldnt_close     => 'Fermeture impossible de',
   couldnt_updatedb  => 'Ne peut pas mettre à jour l\'index de base de données ',
   disallowed_pop3   => 'Serveur POP3 interdit',
   disallowed_client => 'Vous n\'êtes pas autorisé à vous connecter de ce client',
   disallowed_receiverdomain => 'Vous n\'êtes pas autorisé à envoyer des messages à cette adresse mail',
   norootlogin       => 'Connexion root désactivée pour des raisons de sécurité.',
   shouldnt_move_here=> 'Vous ne devriez pas tenter de déplacer des messages ici !',
   destination_folder=> 'Dossier de destination',
   doesnt_exist      => 'n\'existe pas !',
   foldername_long   => 'Le nom du dossier est limité à 16 caractères !',
   folder_with_name  => 'Un dossier du nom de',
   already_exists    => 'existe déjà !',
   cant_create_folder=> 'impossible de créer le dossier !',
   under_indexing    => 'est déjà en cours d\'indexage. Essayez plus tard',
   abook_invalid     => 'Désolé, ce fichier ne semble pas être un carnet d\'adresses au format CSV exporté depuis Microsoft Outlook Express 5. Assurez-vous en le visualisant avec un éditeur de texte la première ligne débute par "Name,E-mail Address", puis recommencez.',
   back              => 'retour',
   tryagain          => 'réessayez.',
   abook_toobig      => 'Désolé, la taille limite de votre carnet d\'adresses serait dépassée.',
   cant_create_dir   => 'Impossible de créer votre répertoire utilisateur !',
   folder_hitquota   => 'Désolé, vous avez atteint votre quota, aucun courrier supplémentaire ne peut plus être stocké dans vos dossiers. Vous ne pouvez plus déplacer de message, sauf vers la CORBEILLE où ils seront détruits.  Effacez quelques messages, videz votre corbeille, et réessayez.',
   folder_cutdone    => 'Attention, comme la limite de quotas (@@@FOLDERQUOTA@@@) a été atteinte, de vieux messages dans des dossiers ont été automatiquement effacés.',
   att_overlimit     => 'Désolé, vous avez atteint la taille maximale d\'attachements, à savoir',
   inv_msg_op        => 'Opération non valide pour le message',
   sess_cookieerr    => 'Votre requête ne contient pas un numéro de session valide - Accès refusé !',
   sess_iperr        => 'Votre requête ne provient pas de la même IP que cette session - Accès refusé !',
   no_endpart        => 'Fin non trouvée',
   part_missing      => 'Certaines parties sont manquantes',
   rebuild_fmterr    => 'Erreur de format du message',
   rebuild_sizeerr   => 'Erreur de taille du message',
   user_not_exist    => 'utilisateur inexistant',
   func_notsupported => 'fonction non-supportée',
   auth_syserr       => 'erreur d\'authentification',
   param_fmterr      => 'erreur de format de paramètre',
   pwd_incorrect     => 'Mot de passe incorrect ',
   pwd_tooshort      => 'Mot de passe trop court (Longueur minimum : @@@PASSWDMINLEN@@@)',
   pwd_toosimple     => 'Mot de passe trop simple (Il faut qu\'il y ait des chiffres et des lettres !)',
   network_server_error => 'erreur de serveur réseau',
   sendmail_error    => 'Une erreur s\'est produite lors de l\'envoi de votre mail. Cliquez sur le bouton \'Précédent\' de votre navigateur, et prévenez votre Administrateur',
   at_char_not_allowed => 'Le caractère @ n\'est pas autorisé dans ce champs. Cliquez sur le boutton précédent et corrigez',
   badnum_in_days => 'Chiffre incorrect dans le champ des jours consécutifs',
   access_denied     => 'Accès interdit',
   couldnt_chdirto   => 'Ne peut pas changer de répertoire vers',
   isnt_a_dir        => 'n\'est pas un répertoire',
   edit_notfordir    => 'Vous ne pouvez pas éditer un répertoire',
   onefileonly       => 'Un seul fichier est autorisé pour cette opération',
   no_file_todownload=> 'Aucun fichier n\'ets spécifier pour le téléchargement',
   upload_overlimit  => 'La taille du fichier d\'upload dépasse la taille limite',
   decomp_notsupported=>'La décompression n\'est pas disponible pour ce fichier.',
   webdisk_hitquota   => 'Désolé, vous avez atteind le QUOTA. Effacer d\'abord des fichiers.',
   webdisk_readonly   => 'Désolé, votre webdisk est en lexture seule.'
   );

1;
