#!/usr/bin/perl -T

# French translation by Cyril Sabatier, c.sabatier.AT.bocquet.com
# charset: iso-8859-1

%lang_folders =
   (
   INBOX => 'Reçus',
   'saved-messages' => 'Enregistrés',
   'sent-mail'      => 'Envoyés',
   'saved-drafts'   => 'Brouillons',
   'mail-trash'     => 'Poubelle',
   'all'            => 'All',
   DELETE => '-- SUPPRIMER --'
   );

%lang_sortlabels =
   (
   status      => 'Status (Non lu d\'abord)',
   date        => 'Date (Le plus récent d\'abord)',
   date_rev    => 'Date (Le plus ancien d\'abord)',
   sender      => 'Expéditeur (Le plus récent d\'abord)',
   sender_rev  => 'Expéditeur (Le plus ancien d\'abord)',
   subject     => 'Sujet (Le plus récent d\'abord)',
   subject_rev => 'Sujet (Le plus ancien d\'abord)',
   size        => 'Taille (Le plus gros d\'abord)',
   size_rev    => 'Taille (Le plus petit d\'abord)'
   );

%lang_prioritylabels =
   (
   normal      => 'Normal',
   urgent      => 'Urgent',
   'non-urgent'=> 'Non-Urgent'
   );

%lang_withoriglabels =
   (
   at_beginning => 'au Début',
   at_end      => 'à la Fin',
   none        => 'Rien'
   );

%lang_receiptlabels =
   (
   ask => 'Demander confirmation',
   yes => 'Oui',
   no  => 'Non'
   );

%lang_timelabels =
   (
     10 => '10 minutes',
     30 => '30 minutes',
     60 => '60 minutes',
    120 => '2 hours',
    180 => '3 hours',
    360 => '6 hours',
    720 => '12 hours',
   1440 => '24 hours'
   );

%lang_advsearchlabels =
   (
   contains    => 'contains',
   notcontains => 'does not contain',
   is          => 'is',
   isnot       => 'is not',
   startswith  => 'starts with',
   endswith    => 'ends with',
   regexp      => 'matches regexp(insensitive)',
   );

%lang_calendar = 
   (
   yearview  => 'Yearview',
   monthview => 'Monthview',
   weekview  => 'Weekview',
   dayview   => 'Dayview'
   );

%lang_month =
   (
   1  => 'January',
   2  => 'February',
   3  => 'March',
   4  => 'April',
   5  => 'May',
   6  => 'June',
   7  => 'July',
   8  => 'August',
   9  => 'September',
   10 => 'October',
   11 => 'November',
   12 => 'December'
   );

%lang_wday =
   (
   0 => 'Sunday',
   1 => 'Monday',
   2 => 'Tuesday',
   3 => 'Wednesday',
   4 => 'Thursday',
   5 => 'Friday',
   6 => 'Saturday'
   );

%lang_wday_abbrev =
   (
   week => 'WK',
   0 => 'S',
   1 => 'M',
   2 => 'T',
   3 => 'W',
   4 => 'T',
   5 => 'F',
   6 => 'S'
   );

%lang_order =
   (
   1 => '1st',
   2 => '2nd',
   3 => '3rd',
   4 => '4th',
   5 => 'last'
   );

%lang_text =
   (
   login      => 'Entrer',
   clear      => 'Effacer',
   point      => 'Point',
   pixel      => 'Pixel',
   changepwd  => 'Changer Mot de Passe',
   viewhistory=> 'Historique',
   of         => 'de',
   messages   => 'messages',
   unread     => 'non lu(s)',
   nomessages => 'Pas de messages',
   composenew => 'Composer un nouveau message',
   refresh    => 'Rafraîchir',
   userprefs  => 'Préférences Utilisateur',
   addressbook=> 'Carnet d\'adresses',
   folders    => 'Dossiers',
   emptytrash => 'Vider la Poubelle',
   totrash    => 'Move to Trash',
   forever    => 'Toujours',
   userdef    => 'Personnaliser',
   logout     => 'Déconnecter (Logout)',
   page       => 'Page',
   msgcopyconf=> '\'Êtes-vous sûr(e) de vouloir copier le(s) message(s) sélectionné(s)?\'',
   copy       => 'Copier',
   msgmoveconf=> '\'Êtes-vous sûr(e) de vouloir déplacer le(s) message(s) sélectionné(s) ?\'',
   move       => 'Déplacer',
   markasread => 'Pointer \'Lu\'',
   markasunread => 'Pointer \'Non-lu\'',
   dateformat => 'Format de Date',
   date       => 'Date',
   recipient  => 'Destinataire',
   sender     => 'Expéditeur',
   subject    => 'Sujet',
   thread     => 'Thread',
   size       => 'Taille',
   backto     => 'Retour à',
   reply      => 'Répondre',
   replyall   => 'Répondre à tous',
   forward    => 'Faire suivre',
   forwardasatt=>'Faire suivre en tant qu\'attachement',
   printfriendly=> 'Print friendly',
   from       => 'Expéditeur',
   replyto    => 'Répondre à',
   to         => 'Destinataire',
   cc         => 'Copie',
   bcc        => 'Copie Cachée',
   simplehead => 'En-tête simplifié',
   allhead    => 'En-tête complet',
   simpleattmode => 'Simple attachments',
   allattmode    => 'Tous les attachments',
   attachment => 'Pièce attachée',
   type       => 'Type',
   filename   => 'Nom de fichier',
   encoding   => 'Encodage',
   description=> 'Description',
   download   => 'Télécharger',
   thisispartialmsg => 'Ceci est un message partiel.',
   msgrebuild => 'Message Reconstruit',
   editdraft  => 'Editer Brouillon',
   savedraft  => 'Enregistrer Brouillon',
   send       => 'Envoyer',
   about      => 'About',
   close      => 'Close',
   cancel     => 'Annuler',
   continue   => ' OK ',
   loginagain => 'Login again',
   exit       => 'Fermer',
   for        => 'pour',
   yourname   => 'Votre nom',
   save       => 'Enregistrer',
   add        => 'Ajouter',
   folderrenprop => '\'Entrez un nouveau nom pour ce dossier\'',
   rename     => 'Renommer',
   folderdelconf => '\'Êtes-vous sûr(e) de vouloir détruire ce dossier et tout son contenu ?\'',
   markread   => 'MarkRead',
   foldermarkreadconf => '\'Are you going to mark read on all messages in this folder?\'',
   chkindex   => 'CheckIndex',
   folderchkindexconf => '\'Are you going to check the index of this folder?\'',
   reindex    => 'ReIndex',
   folderreindexconf => '\'Are you sure you want to reindex this folder?\'',
   total      => 'Total',
   delete     => 'Effacer',
   reserve    => 'Reserve',
   clearadd   => 'Effacer toutes les adresses',
   importadd  => 'Importer adresses',
   exportadd  => 'Exporter adresses',
   import     => 'Importer',
   addmod     => 'Ajouter/Modifier',
   modify     => 'Modifier',
   abooktitle => 'Carnet d\'adresses ',
   abook      => 'Carnet d\'adresses',
   name       => 'Nom',
   email      => 'Email',
   note       => 'Commentaire',
   group      => 'Groupe',
   quota_hit  => 'QUOTA ATTEINT',
   usage      => 'Utilisation',
   tzmap      => 'World timezone map',
   editfroms  => 'Edit personal email addresses',
   pop3book   => 'Configuration POP3',
   retr_pop3s => 'Rappatrier emails POP3',
   filterbook => 'Configuration du filtre de mails',
   include    => 'contient',
   exclude    => 'ne contient pas',
   smtprelay  => 'Relais SMTP',
   header     => 'Entête',
   body       => 'Corps du Message',
   attfilename=> 'Nom de fichier(s)',
   all        => 'Tous',
   enable     => 'Actif',
   disable    => 'Inactif',
   filtered   => 'Filtered',
   blockrelay => 'Bloquer le relais SMTP',
   blockemail => 'Bloquer les emails',
   read       => 'Lu',
   yourmsg    => 'Votre message',
   delivered  => 'Distribué',
   wasreadon1 => 'a été lu',
   wasreadon2 => '.',
   globaladdressbook => 'Carnet d\Adresses Global',
   globalfilterrule => 'Règles de Filtrage Globales',
   readonly   => 'Lecture seule',
   textcontent=> 'Message',
   search     => 'Chercher',
   advsearch  => 'Advanced search',
   folder     => 'Folder',
   nofoldersel=> 'No Folder selected',
   showall    => 'Show All',
   spellcheck => 'Vérif. Orth.',
   checkagain => 'Vérif. encore',
   finishchecking => 'Fin vérif.',
   manuallyfix=> 'Correction manuelle',
   calendar   => 'Calendar',
   am         => 'am',
   pm         => 'pm',
   calfmt_year          => 'Year @@@YEAR@@@',
   calfmt_yearmonth     => '@@@MONTH_STR@@@ @@@YEAR@@@',
   calfmt_yearmonthday  => '@@@MONTH_STR@@@ @@@DAY@@@ @@@YEAR@@@',
   calfmt_yearmonthdaywday => '@@@MONTH_STR@@@ @@@DAY@@@ @@@YEAR@@@ @@@WEEKDAY_STR@@@',
   calfmt_hourminampm => '@@@HOURMIN@@@ @@@AMPM@@@',
   none       => 'None',
   moreitems  => 'more items',
   multieditconf => 'This item was added for multiple dates.\\nEditing it will change the item for all dates.\\nContinue with Edit?',
   multidelconf  => 'This item was added for multiple dates.\\nDeleting it will delete the item for all dates.\\nContinue with Delete?',
   ed         => 'Ed',
   del        => 'Del',
   noitemforthisday => 'No items for this day',
   today_only               => 'Today\'s date only',
   the_wday_of_thismonth    => 'The',
   the_wday_of_thismonth2   => 'of the month',
   every_wday_of_thismonth  => 'Every',
   every_wday_of_thismonth2 => 'this month'
   );

%lang_err =
   (
   has_illegal_chars => 'a des caractères illégaux !',
   couldnt_open      => 'Ouverture imposible de ',
   couldnt_locksh    => 'Couldn\'t get read lock on',
   couldnt_lock      => 'Protection en écriture de ',
   couldnt_seek      => 'Recherche impossible vers le début de',
   couldnt_close     => 'Fermeture impossible de',
   disallowed_pop3   => 'Serveur POP3 interdit',
   disallowed_client => 'You are not allowed to connect from this client',
   disallowed_receiverdomain => 'You are not allowed to send message to this email address',
   norootlogin       => 'Connexion root désactivée pour des raisons de sécurité.',
   shouldnt_move_here=> 'Vous ne devriez pas tenter de déplacer des messages ici !',
   destination_folder=> 'Dossier de destination',
   doesnt_exist      => 'n\'existe pas !',
   foldername_long   => 'Le nom du dossier est limité à 16 caractères !',
   folder_with_name  => 'Un dossier du nom de',
   already_exists    => 'existe déjà !',
   cant_create_folder=> 'impossible de créer le dossier !',
   under_indexing    => 'est déjà en cours d\'indexage. Essayez plus tard',
   abook_invalid     => 'Désolé, ce fichier ne semble pas être un carnet d\'adresses au format CSV exporté depuis Microsoft Outlook Express 5. Assurez-vous en le visualisant avec un éditeur de texte la première ligne débute par "Name,E-mail Address", puis recommencez.',
   back              => 'retour',
   tryagain          => 'réessayez.',
   abook_toobig      => 'Désolé, la taille limite de votre carnet d\'adresses serait dépassée.',
   cant_create_dir   => 'Impossible de créer votre répertoire utilisateur !',
   folder_hitquota   => 'Désolé, vous avez atteint votre quota, aucun courrier supplémentaire ne peut plus être stocké dans vos dossiers. Vous ne pouvez plus déplacer de message, sauf vers la CORBEILLE où ils seront détruits.  Effacez quelques messages, videz votre corbeille, et réessayez.',
   att_overlimit     => 'Désolé, vous avez atteint la taille maximale d\'attachements, à savoir',
   inv_msg_op        => 'Opération non-valide pour le message',
   inv_sessid        => 'Votre requête ne contient pas un numéro de session valide - Accès refusé !',
   no_endpart        => 'Fin non trouvée',
   part_missing      => 'Certaines parties sont manquantes',
   rebuild_fmterr    => 'Erreur de format du message',
   rebuild_sizeerr   => 'Erreur de taille du message',
   user_not_exist    => 'utilisateur inexistant',
   func_notsupported => 'fonction non-supporté',
   auth_syserr       => 'erreur d\'authentification',
   param_fmterr      => 'erreur de format de paramètre',
   pwd_incorrect     => 'Mot de Passe incorrect ',
   network_server_error => 'erreur de serveur réseau',
   sendmail_error    => 'Une erreur s\'est produite lors de l\'envoi de votre mail. Cliquez sur le bouton \'Précédent\' de votre navigateur, et prévenez votre Administrateur',
   at_char_not_allowed => 'The @ character is not allowed in this field.  Press browser back button and try again',
   badnum_in_days => 'bad number in consecutive days field'
   );

1;
