#!/usr/bin/perl

# Italian translation by Benedet Marvi, i3100579.AT.ingstud.univ.trieste.it
# charset: iso-8859-1

%lang_folders =
   (
   INBOX => 'ARRIVATI',
   'saved-messages' => 'SALVATI',
   'sent-mail'      => 'INVIATI',
   'saved-drafts'   => 'BOZZE',
   'mail-trash'     => 'CESTINO',
   DELETE => '--CANCELLA--'
   );

%lang_sortlabels =
   (
   status      => 'Status (Non letti prima)',
   date        => 'Data (Più recenti prima)',
   date_rev    => 'Data (Più vecchi prima)',
   sender      => 'Mittente (Più recenti prima)',
   sender_rev  => 'Mittente (Più vecchi prima)',
   subject     => 'Oggetto (Più recenti prima)',
   subject_rev => 'Oggetto (Più vecchi prima)',
   size        => 'Dimensioni (Ordine decrescente)',
   size_rev    => 'Dimensioni (Ordine crescente)'
   );

%lang_prioritylabels =
   (
   normal      => 'Normale',
   urgent      => 'Urgente',
   'non-urgent'=> 'Non-Urgente'
   );

%lang_withoriglabels =
   (
   at_beginning => 'all\'inizio',
   at_end      => 'alla fine',
   none        => 'Nessuno'
   );

%lang_receiptlabels =
   (
   ask => 'Richiedi conferma',
   yes => 'Si',
   no  => 'No'
   );

%lang_positionlabels =
   (
   before => 'Prima area messaggio',
   after => 'Dopo area messaggio',
   both  => 'Prima e dopo area messaggio'
   );

%lang_timelabels =
   (
      3 => '3 minuti',
      5 => '5 minuti',
     10 => '10 minuti',
     20 => '20 minuti',
     30 => '30 minuti',
     60 => '60 minuti',
    120 => '2 ore',
    180 => '3 ore',
    360 => '6 ore',
    720 => '12 ore',
   1440 => '24 ore'
   );

%lang_advsearchlabels =
   (
   contains    => 'contiene',
   notcontains => 'non contiene',
   is          => 'è',
   isnot       => 'non è',
   startswith  => 'inizia per',
   endswith    => 'finisce per',
   regexp      => 'soddisfa regexp',
   );

%lang_calendar = 
   (
   yearview  => 'Annuale',
   monthview => 'Mensile',
   weekview  => 'Settimanale',
   dayview   => 'Giornaliero',
   listview   => 'Listview'
   );

%lang_month =
   (
   1  => 'Gennaio',
   2  => 'Febbraio',
   3  => 'Marzo',
   4  => 'Aprile',
   5  => 'Maggio',
   6  => 'Giugno',
   7  => 'Luglio',
   8  => 'Agosto',
   9  => 'Settembre',
   10 => 'Ottobre',
   11 => 'Novembre',
   12 => 'Dicembre'
   );

%lang_wday =
   (
   0 => 'Domenica',
   1 => 'Lunedì',
   2 => 'Martedì',
   3 => 'Mercoledì',
   4 => 'Giovedì',
   5 => 'Venerdì',
   6 => 'Sabato'
   );

%lang_wday_abbrev =
   (
   week => 'ST',
   0 => 'D',
   1 => 'L',
   2 => 'M',
   3 => 'M',
   4 => 'G',
   5 => 'V',
   6 => 'S'
   );

%lang_order =
   (
   1 => '1.',
   2 => '2.',
   3 => '3.',
   4 => '4.',
   5 => 'ultimo'
   );

%lang_text =
   (
   login      => 'Login',
   clear      => 'Cancella',
   point      => 'Punti',
   pixel      => 'Pixel',
   changepwd  => 'Cambia Password',
   viewhistory=> 'Mostra cronologia',
   of         => 'di',
   messages   => 'messaggi',
   unread     => 'non letti',
   nomessages => 'Nessun messaggio',
   inmessages => 'Messaggi in arrivo',
   composenew => 'Componi nuovo messaggio',
   refresh    => 'Aggiorna',
   userprefs  => 'Preferenze utente',
   addressbook=> 'Rubrica',
   folders    => 'Cartelle',
   emptytrash => 'Svuota cestino',
   totrash    => 'Sposta in cestino',
   forever    => 'Per Sempre',
   delatlogout=> 'Cancella all\'uscita',
   userdef    => 'Personalizzato',
   logout     => 'Esci',
   page       => 'Pagina',
   msgcopyconf=> '\'Sei sicuro di voler copiare i messaggi selezionati?\'',
   copy       => 'Copia',
   msgmoveconf=> '\'Sei sicuro di voler spostare i messaggi selezionati?\'',
   move       => 'Sposta',
   markasread => 'Segna come letto',
   markasunread => 'Segna come non letto',
   dateformat => 'Formato data',
   date       => 'Data',
   recipient  => 'Destinatario',
   sender     => 'Mittente',
   subject    => 'Oggetto',
   thread     => 'Argomento',
   size       => 'Dimensione',
   backto     => 'Torna a',
   reply      => 'Rispondi',
   replyall   => 'Rispondi a tutti',
   forward    => 'Inoltra',
   forwardasatt=>'Inoltra come allegato',
   printfriendly=> 'Versione stampabile',
   from       => 'Da',
   replyto    => 'Rispondi a',
   to         => 'A',
   cc         => 'CC',
   bcc        => 'BCC',
   simplehead => 'Intestazioni principali',
   allhead    => 'Tutte le intestazioni',
   simpleattmode => 'Allegato semplice',
   allattmode    => 'Tutti gli allegati',
   attachment => 'Allegato',
   type       => 'Tipo',
   filename   => 'Nome del file',
   encoding   => 'Codifica',
   description=> 'Descrizione',
   download   => 'Scarica',
   charset    => 'Charset',
   samecharset=> 'The same as composing charset',
   thisispartialmsg => 'Questo è un messaggio parziale.',
   msgrebuild => 'Messaggio ricostruito',
   editdraft  => 'Edita bozze',
   savedraft  => 'Salva bozza',
   send       => 'Invia',
   about      => 'Informazioni',
   close      => 'Chiudi',
   cancel     => 'Annulla',
   continue   => 'Continua',
   loginagain => 'Login di nuovo',
   exit       => 'Uscita',
   for        => 'PER',
   yourname   => 'Nome',
   save       => 'Salva',
   add        => 'Aggiungi',
   folderrenprop => '\'Inserisci il nome di questa cartella\'',
   rename     => 'Rinomina',
   folderdelconf => '\'Cancello questa cartella e tutto il suo contenuto?\'',
   markread   => 'SegnaLetto',
   foldermarkreadconf => '\'Vuoi segnare come letti tutti i messaggi di questa cartella?\'',
   chkindex   => 'ControlloIndice',
   folderchkindexconf => '\'Vuoi controllare l\\\'indice di questa cartella?\'',
   reindex    => 'ReIndex',
   folderreindexconf => '\'Vuoi ricreare l\\\'indice di questa cartella?\'',
   total      => 'Totale',
   delete     => 'Cancella',
   reserve    => 'Conserva',
   clearadd   => 'Cancella tutti gli indirizzi',
   importadd  => 'Importa indirizzi',
   exportadd  => 'Esporta indirizzi',
   import     => 'Importa',
   addmod     => 'Aggiungi/Modifica',
   modify     => 'Modifica',
   abooktitle => 'Rubrica di ',
   abook      => 'RUBRICA',
   name       => 'Nome',
   email      => 'Email',
   note       => 'Note',
   group      => 'Gruppo',
   quota_hit  => 'LIMITE RAGGIUNTO',
   usage      => 'Uso',
   tzmap      => 'Mappa fusi orari',
   testsound  => 'Test suono',
   editfroms  => 'Modifica indirizzi e-mail personali',
   pop3book   => 'Impostazioni POP3',
   retr_pop3s => 'Scarica posta POP3',
   filterbook => 'Setup filtro posta',
   include    => 'Includi',
   exclude    => 'Escludi',
   smtprelay  => 'SMTP Relay',
   header     => 'Intestazione',
   body       => 'Corpo Testo',
   attfilename=> 'NomeFileAllegato',
   all        => 'Tutti',
   enable     => 'Abilitato',
   disable    => 'Disabilitato',
   filtered   => 'Filtrato',
   blockrelay => 'Blocca SMTP Relay',
   blockemail => 'Blocca email',
   read       => 'Leggi',
   yourmsg    => 'Il tuo messaggio',
   delivered  => 'Consegnato',
   wasreadon1 => 'è stato letto',
   wasreadon2 => '.',
   globaladdressbook => 'Rubrica Globale',
   globalfilterrule => 'Regola Filtro Globale',
   readonly   => 'SolaLettura',
   textcontent=> 'Testo Contenuto',
   search     => 'Cerca',
   advsearch  => 'Ricerca avanzata',
   folder     => 'Cartella',
   nofoldersel=> 'Nessuna cartella selezionata',
   showall    => 'Mostra tutto',
   spellcheck => 'Controllo Ortografico',
   checkagain => 'Controlla Ancora',
   finishchecking => 'Ferma controllo',
   manuallyfix=> 'Correggi a mano',
   editstat   => 'Modifica Stationery',
   savestat   => 'Salva Stationery',
   clearstat  => 'Cancella tutti i Stationery',
   selectstat => '-- Seleziona  Stationery per la Risposta --',
   calendar   => 'Calendario',
   am         => 'am',
   pm         => 'pm',
   calfmt_year          => 'Anno @@@YEAR@@@',
   calfmt_yearmonth     => '@@@MONTH_STR@@@ @@@YEAR@@@',
   calfmt_yearmonthday  => '@@@MONTH_STR@@@ @@@DAY@@@ @@@YEAR@@@',
   calfmt_yearmonthdaywday => '@@@MONTH_STR@@@ @@@DAY@@@ @@@YEAR@@@ @@@WEEKDAY_STR@@@',
   calfmt_hourminampm => '@@@HOURMIN@@@ @@@AMPM@@@',
   none       => 'Nessuno',
   moreitems  => 'più voci',
   multieditconf => 'Questa voce  stata aggiunta per più date.\\nModificandola verrà cabiata per tutte le date.\\nContinuare?',
   multidelconf  => 'Qeusto voce  stata aggiunta per più date.\\nCancellandola verrà eliminata per ogni data.\\nContinuare?',
   ed         => 'Ed',
   del        => 'Del',
   noitemforthisday => 'Nessuna voce per questo giorno',
   today_only               => 'Solo Oggi',
   the_wday_of_thismonth    => 'Il @@@ORDER@@@ @@@WDAY@@@ del mese',
   every_wday_of_thismonth  => 'Ogni @@@WDAY@@@ questo mese'
   );

%lang_err =
   (
   has_illegal_chars => 'contiene caratteri non permessi!',
   couldnt_open      => 'Non posso aprire',
   couldnt_locksh    => 'Non posso ottenere blocco in lettura',
   couldnt_lock      => 'Non posso scrivere',
   couldnt_seek      => 'Non posso raggiungere l\'inizio di',
   couldnt_close     => 'Non posso chiudere',
   couldnt_updatedb  => 'Impossibile aggiornare l\'indice db ',
   disallowed_pop3   => 'Server POP3 diabilitato',
   disallowed_client => 'Non sei abilitato a connetterti da questo client',
   disallowed_receiverdomain => 'Non sei abilitato a spedire mail a questo indirizzo',
   norootlogin       => 'Spiacente, ma root non può usare questo sistema per motivi di sicurezza',
   shouldnt_move_here=> 'Non dovresti tentare di spostare i tuoi messaggi qui!',
   destination_folder=> 'Cartella destinazione',
   doesnt_exist      => 'non esiste!',
   foldername_long   => 'Il nome di una cartella non può essere più lungo di 16 caratteri!',
   folder_with_name  => 'Una cartella di nome',
   already_exists    => 'esiste già!',
   cant_create_folder=> 'Non posso creare la cartella',
   under_indexing    => 'fase di indicizzazione, riprova dopo',
   abook_invalid     => 'Questo file non è una rubrica esportata da Outlook Express 5 in formato CSV. Assicurati che la prima riga inizi con "Nome, E-mail", quindi riprova',
   back              => 'indietro',
   tryagain          => 'e riprova.',
   abook_toobig      => 'Spiacente, questo eccederebbe il limite per la tua rubrica. Torna',
   cant_create_dir   => 'Non posso creare la tua directory utente!',
   folder_hitquota   => 'Spiacente, hai raggiunto il limite di spazio a te concesso e non puoi più salvare posta. Puoi solo spostare i tuoi messaggi nel cestino dove verranno cancellati. Torna indietro, cancella qualche messaggio, svuota il cestino e riprova.',
   folder_cutdone    => 'Attenzione, dal momento che è stato raggiunto il limite di spazio su disco (@@@FOLDERQUOTA@@@), sono stati rimmossi automaticamente i vecchi messaggi',
   att_overlimit     => 'L\'allegato è troppo grande. Il limite è',
   inv_msg_op        => 'Operazione invalida per il messaggio',
   inv_sessid        => 'La tua richiesta non contiene un session ID cookie valido -- accesso negato!',
   no_endpart        => 'Parte finale non trovata',
   part_missing      => 'Mancano alcune parti',
   rebuild_fmterr    => 'Formato nuovo messaggio errato',
   rebuild_sizeerr   => 'Dimensione nuovo messaggio sbagliata',
   user_not_exist    => 'non esiste l\'utente',
   func_notsupported => 'funzione non supportata',
   auth_syserr       => 'Password sbagliata!',
   param_fmterr      => 'errore formato parametri',
   pwd_incorrect     => 'Password sbagliata',
   pwd_tooshort      => 'Password troppo corta (lunghezza minima @@@PASSWDMINLEN@@@)',
   pwd_toosimple     => 'Password troppo semplice (sono richiesti sia caratteri che numeri)',
   network_server_error => 'errore del server di rete',
   sendmail_error    => 'Spiacente, si è verificato  un errore nella spedizione del tuo messaggio. Prova a cliccare su bottone  indietro del tuo browser, controlla il messaggio e riprova',
   at_char_not_allowed => 'Il carattere @ non è permesso in questo campo. Premi Indietro sul browser e riprova',
   badnum_in_days => 'numero errato nel campo giorni consecutivi'
   );

1;
