#!/usr/bin/perl

# Lithuanian translation by Alvydas Sinkunas, dvm382.AT.takas.lt
# charset: windows-1257

%lang_folders =
   (
   INBOX => 'Gauti laiğkai',
   'saved-messages' => 'Iğsaugoti laiğkai',
   'sent-mail'      => 'Iğsiøsti laiğkai',
   'saved-drafts'   => 'Rağomi laiğkai',
   'mail-trash'     => 'Ğiukğliadëşë',
   DELETE => '--TRINTI--'
   );

%lang_sortlabels =
   (
   status      => 'Ruğiavimas (pirma neskaityti)',
   date        => 'Pagal datà (pirma naujausi)',
   date_rev    => 'Pagal datà (pirma seniausi)',
   sender      => 'Pagal siuntëjà (pirma naujausi)',
   sender_rev  => 'Pagal siuntëjà (pirma seniausi)',
   subject     => 'Pagal  temà (pirma naujausi)',
   subject_rev => 'Pagal  temà (pirma seniausi)',
   size        => 'Pagal dydá (pirma didşiausi)',
   size_rev    => 'Pagal dydá (pirma maşiausia)'
   );

%lang_prioritylabels =
   (
   normal      => 'Normalus',
   urgent      => 'Svarbus',
   'non-urgent'=> 'Nesvarbus'
   );

%lang_withoriglabels =
   (
   at_beginning => 'nuo pradşios',
   at_end      => 'nuo pabaigos',
   none        => 'Nëra'
   );

%lang_receiptlabels =
   (
   ask => 'Prağyti patvirtinimo',
   yes => 'Taip',
   no  => 'Ne'
   );

%lang_positionlabels =
   (
   before => 'Before mail edit area',
   after => 'After mail edit area',
   both  => 'Before and after mail edit area'
   );

%lang_timelabels =
   (
      3 => '3 min.',
      5 => '5 min.',
     10 => '10 min.',
     20 => '20 min.',
     30 => '30 min.',
     60 => '60 min.',
    120 => '2 val.',
    180 => '3 val.',
    360 => '6 val.',
    720 => '12 val.',
   1440 => '24 val.'
   );

%lang_advsearchlabels =
   (
   contains    => 'yra frazë',
   notcontains => 'nëra frazës',
   is          => 'yra tiksli frazë',
   isnot       => 'nëra tikslios frazës',
   startswith  => 'prasideda su',
   endswith    => 'baigiasi su',
   regexp      => 'matches regexp',
   );

%lang_calendar = 
   (
   yearview  => 'Metai',
   monthview => 'Mënuo',
   weekview  => 'Savaitë',
   dayview   => 'Diena',
   listview   => 'Listview'
   );

%lang_month =
   (
   1  => 'Sausis',
   2  => 'Vasaris',
   3  => 'Kovas',
   4  => 'Balandis',
   5  => 'Geguşë',
   6  => 'Birşelis',
   7  => 'Liepa',
   8  => 'Rugpjûtis',
   9  => 'Rugsëjis',
   10 => 'Spalis',
   11 => 'Lapkritis',
   12 => 'Gruodis'
   );

%lang_wday =
   (
   0 => 'Sekmadienis',
   1 => 'Pirmadienis',
   2 => 'Antradienis',
   3 => 'Treèiadienis',
   4 => 'Ketvirtadienis',
   5 => 'Penktadienis',
   6 => 'Ğeğtadienis'
   );

%lang_wday_abbrev =
   (
   week => '',
   0 => 'S',
   1 => 'P',
   2 => 'A',
   3 => 'T',
   4 => 'k',
   5 => 'P',
   6 => 'Ğ'
   );

%lang_order =
   (
   1 => '1-as.',
   2 => '2-as.',
   3 => '3-as.',
   4 => '4-as',
   5 => '5-as'
   );

%lang_text =
   (
   login      => 'Jungtis',
   clear      => 'Iğvalyti',
   point      => 'Point',
   pixel      => 'Pixel',
   changepwd  => 'Keisti slaptaşodá',
   viewhistory=> 'Perşiûrëti şurnalà',
   of         => 'iğ viso laiğkø:',
   messages   => ' ',
   unread     => 'neskaityti',
   nomessages => 'Laiğkø nëra',
   inmessages => 'Incoming msgs',
   composenew => 'Rağyti laiğkà',
   refresh    => 'Atnaujinti',
   userprefs  => 'Vartotojo nustatymai',
   addressbook=> 'Adresø sàrağas',
   folders    => 'Segtuvai',
   emptytrash => 'Ar iğtrinti ğiukğledëşæ',
   totrash    => 'Move to Trash',
   forever    => 'Visam laikui',
   delatlogout=> 'Delete at Logout',
   userdef    => 'Vartotojo nustatyti',
   logout     => 'Baigti darbà',
   page       => 'Lapas',
   msgcopyconf=> '\'Ar tikrai norite nukopijuoti paşymëtus laiğkus?\'',
   copy       => 'Kopijuoti',
   msgmoveconf=> '\'Ar tikrai norite perkelti paşymëtus laiğkus?\'',
   move       => 'Perkelti',
   markasread => 'Perskaitymo şymë',
   markasunread => 'Neperskaitymo şymë',
   dateformat => 'Datos formatas',
   date       => 'Data',
   recipient  => 'Gavëjas',
   sender     => 'Siuntëjas',
   subject    => 'Tema',
   thread     => 'Thread',
   size       => 'Dydis',
   backto     => 'Gráşti á',
   reply      => 'Atsakyti',
   replyall   => 'Atsakyti visiems',
   forward    => 'Persiøsti',
   forwardasatt=> 'Persiøsti viskà',
   printfriendly=> 'Print friendly',
   from       => 'Rağë',
   replyto    => 'Atgalinis adresas',
   to         => 'Kam',
   cc         => 'CC',
   bcc        => 'BCC',
   simplehead => 'Be antarğèiø',
   allhead    => 'Su antrağtëm',
   simpleattmode => 'Be antrağèiø',
   allattmode    => 'Su antrağtëm',
   attachment => 'Priedas',
   type       => 'Tipas',
   filename   => 'Bylos vardas',
   encoding   => 'Kodavimas',
   description=> 'Aprağymas',
   download   => 'Parsisiøsti',
   charset    => 'Charset',
   samecharset=> 'The same as composing charset',
   thisispartialmsg => 'Èia yra nepilnas laiğkas.',
   msgrebuild => 'Laiğko atstatymas',
   editdraft  => 'Redaguoti rağomà laiğkà',
   savedraft  => 'Árağyti neiğsiunèiant',
   send       => 'Siøsti',
   about      => 'Apie',
   close      => 'U=daryti',
   cancel     => 'Anuliuoti',
   continue   => 'Tæsti',
   loginagain => 'Prisijungti vël',
   exit       => 'Iğeiti',
   for        => '-',
   yourname   => 'Jûsø vardas',
   save       => 'Árağyti',
   add        => 'Pridëti',
   folderrenprop => '\'Árağykite naujà segtuvo pavadinimà\'',
   rename     => 'Pervardinti',
   folderdelconf => '\'Ar tikrai norite iğtrinti ğá segtuvà ir visà jo turiná?\'',
   markread   => 'MarkRead',
   foldermarkreadconf => '\'Are you going to mark read on all messages in this folder?\'',
   chkindex   => 'CheckIndex',
   folderchkindexconf => '\'Ar norite patikrinti katalogo indeksà?\'',
   reindex    => 'ReIndex',
   folderreindexconf => '\'Ar tikrai norite perindeksuoti ğá katalogà?\'',
   total      => 'Iğ viso',
   delete     => 'Iğtrinti',
   reserve    => 'Rezervuoti',
   clearadd   => 'Iğtrinti visus adresus',
   importadd  => 'Importuoti',
   exportadd  => 'Eksportuoti',
   import     => 'Importuoti',
   addmod     => 'Pridëti/Keisti',
   modify     => 'Keisti',
   abooktitle => 'Adresø knygutë',
   abook      => 'ADRESØ KNYGUTË',
   name       => 'Vardas',
   email      => 'El.pağtas',
   note       => 'Pastaba',
   group      => 'Grupë',
   quota_hit  => 'JÛSØ DISKO VIETA IĞNAUDOTA',
   usage      => 'Iğnaudota disko vietos',
   tzmap      => 'Pasaulio laiko juostø şemëlapis',
   testsound  => 'Test sound',
   editfroms  => 'Redaguoti personaliná el. pağto adresà',
   pop3book   => 'POP3 nustatymai',
   retr_pop3s => 'Tikrinti POP3 pağto dëşutæ',
   filterbook => 'Pağto filtrai',
   include    => 'Naudoti',
   exclude    => 'Nenaudoti',
   smtprelay  => 'SMTP leidimas',
   header     => 'Adresai',
   body       => 'Turinys',
   attfilename=> 'Priedø varduose',
   all        => 'Visur',
   enable     => '',
   disable    => 'Uşdrausta',
   filtered   => 'Nufiltruota',
   blockrelay => 'Uşdraustas SMTP',
   blockemail => 'Uşdraustas pağtas',
   read       => 'Skaityti',
   yourmsg    => 'Jûsø laiğkas',
   delivered  => 'Pristatytas',
   wasreadon1 => 'Tik skaityti',
   wasreadon2 => '.',
   globaladdressbook => 'Globali adresø knygelë',
   globalfilterrule => 'Globalûs filtrai',
   readonly   => 'Tik skaityti',
   textcontent=> 'Tekste',
   search     => 'Ieğkoti',
   advsearch  => 'Iğplëstinë paieğka',
   folder     => 'Katalogas',
   nofoldersel=> 'Nepasirinktas katalogas',
   showall    => 'rodyti viskà',
   spellcheck => 'Tikrinti rağybà',
   checkagain => 'Tikrinti vël',
   finishchecking => 'Patikrinta',
   manuallyfix=> 'Fiksuoti',
   editstat   => 'Edit Stationery',
   savestat   => 'Save Stationery',
   clearstat  => 'Clear All Stationery',
   selectstat => '-- Select Stationery for Reply --',
   calendar   => 'Kalendorius',
   am         => 'iki.p',
   pm         => 'po.p',
   calfmt_year          => 'Metai @@@YEAR@@@',
   calfmt_yearmonth     => '@@@MONTH_STR@@@ @@@YEAR@@@',
   calfmt_yearmonthday  => '@@@MONTH_STR@@@ @@@DAY@@@ @@@YEAR@@@',
   calfmt_yearmonthdaywday => '@@@MONTH_STR@@@ @@@DAY@@@ @@@YEAR@@@ @@@WEEKDAY_STR@@@',
   calfmt_hourminampm => '@@@HOURMIN@@@ @@@AMPM@@@',
   none       => 'Nieko',
   moreitems  => 'daugiau árağø',
   multieditconf => 'Ğis árağas su keliomis datomis.\\nRedaguodami pakeisite árağà visoms datoms.\\nAr testi redagavimà?',
   multidelconf  => 'Ğis árağas su keliomis datomis.\\nIğtrinti galima tik visas datas iğ karto.\\nAr tæsti trynimà?',
   ed         => 'Red',
   del        => 'Iğtr.',
   noitemforthisday => 'Ğiai dienai árağø nëra',
   today_only               => 'Tik ğiai datai',
   the_wday_of_thismonth    => ' @@@ORDER@@@ @@@WDAY@@@ per mënesá',
   every_wday_of_thismonth  => 'Kiekvienas @@@WDAY@@@ ğá mënesá'
   );

%lang_err =
   (
   has_illegal_chars => 'neleistini simboliai!',
   couldnt_open      => 'nepavyko atversti',
   couldnt_locksh    => 'Skaitymo klaida',
   couldnt_lock      => 'Rağymo klaida',
   couldnt_seek      => 'Nëra pradşios',
   couldnt_close     => 'Nepavyko uşdaryti',
   couldnt_updatedb  => 'Couldn\'t update index db ',
   disallowed_pop3   => 'Nepriëmë  POP3 serveris',
   disallowed_client => 'Ğiam vardui nëra teisës prisijungti',
   disallowed_receiverdomain => 'You are not allowed to send message to this email address',
   norootlogin       => 'Prisijungti nepavyks! Gudrutis... :-)',
   shouldnt_move_here=> 'Pabandykite perkelti laiğkà èia!',
   destination_folder=> 'Tikslo katalogas',
   doesnt_exist      => 'nëra!',
   foldername_long   => 'Segtuvo vardas turi bûti ne ilgesnis kaip 16 simboliø!',
   folder_with_name  => 'Segtuvas',
   already_exists    => 'jau yra!',
   cant_create_folder=> 'Nepavyko sukurti segtuvo!',
   under_indexing    => 'is still under indexing, please try later',
   abook_invalid     => 'Atrodo, kad norite importuoti bylà, kuri neatitinka Microsoft Outlook Express 5 CSV formato. Pasişiûrëkit ar pirmoje eilutë tokia: "Name,E-mail Address", jei taip, bandykite importuoti',
   back              => 'atgal',
   tryagain          => 'bandykit dar kartà.',
   abook_toobig      => 'Gaila, bet Jûs iğnaudojote adresø knygelei skirtà disko vietà.',
   cant_create_dir   => 'Nepavyko sukurti segtuvo Jûsø darbui!',
   folder_hitquota   => 'Gaila, bet iğnaudota Jums skirta disko vieta. Perşiûrëkit ir iğtrinkit senus, gal bût nebereikalingus laiğkus.',
   folder_cutdone    => 'Warning, since the folderquota limit(@@@FOLDERQUOTA@@@) were hit, oldest messages in folders have been removed automatcially',
   att_overlimit     => 'Gaila, bet Jûsø prikabinta byla didesnë uş leistinà',
   inv_msg_op        => 'Neteisingi veiksmai su laiğku',
   inv_sessid        => 'Sesijos ID nesutampa su esamu "sausainiu" - Jûsø veiksmai neleistini!',
   no_endpart        => 'Nëra pabaigos',
   part_missing      => 'Kaşkas blogai',
   rebuild_fmterr    => 'Blogas naujo laiğko formatas',
   rebuild_sizeerr   => 'Naujas laiğkas per didelis',
   user_not_exist    => 'vartotojo nëra',
   func_notsupported => 'nenaudojama funkcija',
   auth_syserr       => 'slaptaşodşio tikrinimo klaida',
   param_fmterr      => 'parametro formato klaida',
   pwd_incorrect     => 'slaptaşodis neteisingas',
   pwd_tooshort      => 'Password too short (minimum length @@@PASSWDMINLEN@@@)',
   pwd_toosimple     => 'Password too simple (both alphabet and digit are required)',
   network_server_error => 'tinklo klaida',
   sendmail_error    => 'Gaila, bet iğkilo bëdø siunèiant laiğkà. Gráşkite atgal ir bandykite dar kartà.',
   at_char_not_allowed => 'Simbolis @ negalimas ğiame lauke.  Gráşkite atgal ir bandykite dar kartà',
   badnum_in_days => 'blogas skaièius , nenuoseklus'
   );

1;
