#!/usr/bin/perl -T

# Norwegian Nynorsk translation, incomplete...
# charset: iso-8859-1

%lang_folders =
   (
   INBOX => 'INNBOKS',
   'saved-messages' => 'LAGRET',
   'sent-mail'      => 'SENDT',
   'saved-drafts'   => 'DRAFT',
   'mail-trash'     => 'SØPPELBØTTE',
   DELETE => '--DELETE--'
   );

%lang_sortlabels =
   (
   status      => 'Status (Unread first)',
   date        => 'Dato (Nyeste først)',
   date_rev    => 'Dato (Eldste først)',
   sender      => 'Avsender (Nyeste først)',
   sender_rev  => 'Avsender (Eldste først)',
   subject     => 'Emne (Nyeste først)',
   subject_rev => 'Emne (Eldste først)',
   size        => 'Størresle (Største først)',
   size_rev    => 'Størrelse (Minste først)'
   );

%lang_prioritylabels =
   (
   normal      => 'Normal',
   urgent      => 'Urgent',
   'non-urgent'=> 'Non-Urgent'
   );

%lang_withoriglabels =
   (
   at_beginning => 'at Beginning',
   at_end      => 'at End',
   none        => 'None'
   );

%lang_receiptlabels =
   (
   ask => 'Ask to confirm',
   yes => 'Yes',
   no  => 'No'
   );

%lang_timelabels =
   (
     10 => '10 minutes',
     30 => '30 minutes',
     60 => '60 minutes',
    120 => '2 hours',
    180 => '3 hours',
    360 => '6 hours',
    720 => '12 hours',
   1440 => '24 hours'
   );

%lang_advsearchlabels =
   (
   contains    => 'contains',
   notcontains => 'does not contain',
   is          => 'is',
   isnot       => 'is not',
   startswith  => 'starts with',
   endswith    => 'ends with',
   regexp      => 'matches regexp',
   );

%lang_calendar = 
   (
   yearview  => 'Yearview',
   monthview => 'Monthview',
   weekview  => 'Weekview',
   dayview   => 'Dayview'
   );

%lang_month =
   (
   1  => 'January',
   2  => 'February',
   3  => 'March',
   4  => 'April',
   5  => 'May',
   6  => 'June',
   7  => 'July',
   8  => 'August',
   9  => 'September',
   10 => 'October',
   11 => 'November',
   12 => 'December'
   );

%lang_wday =
   (
   0 => 'Sunday',
   1 => 'Monday',
   2 => 'Tuesday',
   3 => 'Wednesday',
   4 => 'Thursday',
   5 => 'Friday',
   6 => 'Saturday'
   );

%lang_wday_abbrev =
   (
   week => 'WK',
   0 => 'S',
   1 => 'M',
   2 => 'T',
   3 => 'W',
   4 => 'T',
   5 => 'F',
   6 => 'S'
   );

%lang_order =
   (
   1 => '1st',
   2 => '2nd',
   3 => '3rd',
   4 => '4th',
   5 => 'last'
   );

%lang_text =
   (
   login      => 'Logg inn',
   clear      => 'Slett',
   point      => 'Point',
   pixel      => 'Pixel',
   changepwd  => 'Change Password',
   viewhistory=> 'View History',
   of         => 'av',
   messages   => 'meldinger',
   unread     => 'ulest',
   nomessages => 'Ingen meldinger',
   composenew => 'Skriv ny melding',
   refresh    => 'Oppdater',
   userprefs  => 'Brukerinnstillinger',
   addressbook=> 'Adressebok',
   folders    => 'Mapper',
   emptytrash => 'Tøm søppelbøtten',
   totrash    => 'Move to Trash',
   forever    => 'Forever',
   userdef    => 'User Define',
   logout     => 'Logg ut',
   page       => 'Side',
   msgcopyconf=> '\'Are you sure you want to copy the selected message(s)?\'',
   copy       => 'Copy',
   msgmoveconf=> '\'Er du sikker på at du vil flytte de valgte meldingene?\'',
   move       => 'Flytt',
   markasread => 'Mark as read',
   markasunread => 'Mark as unread',
   dateformat => 'Dato format',
   date       => 'Dato',
   recipient  => 'Mottaker',
   sender     => 'Avsender',
   subject    => 'Emne',
   thread     => 'Thread',
   size       => 'Størrelse',
   backto     => 'Tilbake til',
   reply      => 'Svar',
   replyall   => 'Svar alle',
   forward    => 'Videresend',
   forwardasatt=>'Forward as attachment',
   printfriendly=> 'Print friendly',
   from       => 'Fra',
   replyto    => 'Svar til',
   to         => 'Til',
   cc         => 'Kopi',
   bcc        => 'Blindkopi',
   simplehead => 'Enkle meldingshoder',
   allhead    => 'Alle meldingshoder',
   simpleattmode => 'Simple attachments',
   allattmode    => 'All attachments',
   attachment => 'Vedlegg',
   type       => 'Type',
   filename   => 'Filnavn',
   encoding   => 'Koding',
   description=> 'Description',
   download   => 'Lagre',
   thisispartialmsg => 'This is a partial message.',
   msgrebuild => 'Message Rebuild',
   editdraft  => 'Edit Draft',
   savedraft  => 'Save Draft',
   send       => 'Send',
   about      => 'About',
   close      => 'Close',
   cancel     => 'Avbryt',
   continue   => 'Fortsett',
   loginagain => 'Login again',
   exit       => 'Exit',
   for        => 'for',
   yourname   => 'Ditt navn',
   save       => 'Lagre',
   add        => 'Legg til',
   folderrenprop => '\'Please enter the new name for this folder\'',
   rename     => 'Rename',
   folderdelconf => '\'Er du sikker på at du vil slette denne mappen og alt innholdet?\'',
   markread   => 'MarkRead',
   foldermarkreadconf => '\'Are you going to mark read on all messages in this folder?\'',
   chkindex   => 'CheckIndex',
   folderchkindexconf => '\'Are you going to check the index of this folder?\'',
   reindex    => 'ReIndex',
   folderreindexconf => '\'Are you sure you want to reindex this folder?\'',
   total      => 'Total',
   delete     => 'Slett',
   reserve    => 'Reserve',
   clearadd   => 'Clear all addresses',
   importadd  => 'Importer adresser',
   exportadd  => 'Exporter adresser',
   import     => 'Importer',
   addmod     => 'Legg til/Endre',
   modify     => 'Endre',
   abooktitle => 'Adressebok',
   abook      => 'ADRESSEBOK',
   name       => 'Name',
   email      => 'Email',
   note       => 'Note',
   group      => 'Group',
   quota_hit  => 'IKKE MER LAGRINGSPLASS',
   usage      => 'Usage',
   tzmap      => 'World timezone map',
   editfroms  => 'Edit personal email addresses',
   pop3book   => 'POP3 Setup',
   retr_pop3s => 'Retrieve POP3 Mail',
   filterbook => 'Mail Filter Setup',
   include    => 'Include',
   exclude    => 'Exclude',
   smtprelay  => 'SMTP Relay',
   header     => 'Header',
   body       => 'Body',
   attfilename=> 'AttFilename',
   all        => 'All',
   enable     => 'Enable',
   disable    => 'Disable',
   filtered   => 'Filtered',
   blockrelay => 'Block SMTP Relay',
   blockemail => 'Block email',
   read       => 'Read',
   yourmsg    => 'Your message',
   delivered  => 'Delivered',
   wasreadon1 => 'was read on',
   wasreadon2 => '.',
   globaladdressbook => 'Global AddressBook',
   globalfilterrule => 'Global FilterRule',
   readonly   => 'ReadOnly',
   textcontent=> 'TextContent',
   search     => 'Search',
   advsearch  => 'Advanced search',
   folder     => 'Folder',
   nofoldersel=> 'No Folder selected',
   showall    => 'Show All',
   spellcheck => 'Spell Check',
   checkagain => 'Check Again',
   finishchecking => 'Finish Checking',
   manuallyfix=> 'Manually Fix',
   calendar   => 'Calendar',
   am         => 'am',
   pm         => 'pm',
   calfmt_year          => 'Year @@@YEAR@@@',
   calfmt_yearmonth     => '@@@MONTH_STR@@@ @@@YEAR@@@',
   calfmt_yearmonthday  => '@@@MONTH_STR@@@ @@@DAY@@@ @@@YEAR@@@',
   calfmt_yearmonthdaywday => '@@@MONTH_STR@@@ @@@DAY@@@ @@@YEAR@@@ @@@WEEKDAY_STR@@@',
   calfmt_hourminampm => '@@@HOURMIN@@@ @@@AMPM@@@',
   none       => 'None',
   moreitems  => 'more items',
   multieditconf => 'This item was added for multiple dates.\\nEditing it will change the item for all dates.\\nContinue with Edit?',
   multidelconf  => 'This item was added for multiple dates.\\nDeleting it will delete the item for all dates.\\nContinue with Delete?',
   ed         => 'Ed',
   del        => 'Del',
   noitemforthisday => 'No items for this day',
   today_only               => 'Today\'s date only',
   the_wday_of_thismonth    => 'The @@@ORDER@@@ @@@WDAY@@@ of the month',
   every_wday_of_thismonth  => 'Every @@@WDAY@@@ this month'
   );

%lang_err =
   (
   has_illegal_chars => 'inneholder ulovlige tegn!',
   couldnt_open      => 'Kunne ikke åpne',
   couldnt_locksh    => 'Couldn\'t get read lock on',
   couldnt_lock      => 'Fikk ikke skrivetilgang til',
   couldnt_seek      => 'Kunne ikke finne starten på',
   couldnt_close     => 'Kunne ikke lukke',
   disallowed_pop3   => 'Disallowed POP3 server',
   disallowed_client => 'You are not allowed to connect from this client',
   disallowed_receiverdomain => 'You are not allowed to send message to this email address',
   norootlogin       => 'Beklager, root kan ikke logge seg inn på grunn av sikkerhetshensyn.',
   shouldnt_move_here=> 'Du bør ikke flytte meldinger til denne mappen!',
   destination_folder=> 'Målmappe',
   doesnt_exist      => 'eksisterer ikke!',
   foldername_long   => 'Mappenavnet kan ikke være mer enn 16 tegn!',
   folder_with_name  => 'En mappe med navnet',
   already_exists    => 'eksisterer allerede!',
   cant_create_folder=> 'Kan ikke opprette mappen!',
   under_indexing    => 'is still under indexing, please try later',
   abook_invalid     => 'Beklager, denne filen virker ikke som om den er en adressebok eksportert fra Microsoft Outlook Express 5 i CVS-format. Forsikre deg om at filen starter med:"Name,E-mail Address", og gå',
   back              => 'tilbake',
   tryagain          => 'og forsøk på nytt.',
   abook_toobig      => 'Beklager, du overstiger tillatt størrelse på adresseboken din. Gå',
   cant_create_dir   => 'Brukerkatalogen din kunne ikke opprettes!',
   folder_hitquota   => 'Beklager, du har oversteget tillatt lagringsplass for mappene dine. Du har ikke adgang til å flytte meldinger til andre mapper enn søppelbøtten, hvor de vil bli slettet automatisk. Gå tilbake og slett noen meldinger eller tømme søppelbøtten, og forsøk på nytt.',
   att_overlimit     => 'Beklager, du har oversteget tillatt størrelse for vedlegg. Vedlegg må ikke overstige',
   inv_msg_op        => 'Invalid operation for message',
   inv_sessid        => 'Your request didn\'t contain the proper session ID cookie -- access denied!',
   no_endpart        => 'End part not found',
   part_missing      => 'Some part was missing',
   rebuild_fmterr    => 'New message format error',
   rebuild_sizeerr   => 'New message size mismatch',
   user_not_exist    => 'user does not exist',
   func_notsupported => 'function not supported',
   auth_syserr       => 'authentication system error',
   param_fmterr      => 'parameter format error',
   pwd_incorrect     => 'password incorrect',
   network_server_error => 'network server error',
   sendmail_error    => 'Sorry, there was a problem sending your message.  Please click your browser\'s Back button, check your message, and try again.',
   at_char_not_allowed => 'The @ character is not allowed in this field.  Press browser back button and try again',
   badnum_in_days => 'bad number in consecutive days field'
   );

1;
