#!/usr/bin/perl -T

# Polish translation by Pawel Jablonski, jablonski.AT.dialogok.pl 
#                       michal talecki, mik.AT.orka.ibz.pl
#                       Grzegorz Nosek, blackfire.AT.virtual.net.pl
#                       Andrzej Cuber, rea.AT.supermedia.pl
# charset: iso-8859-2

%lang_folders =
   (
   INBOX => 'PRZYCHODZ¡CA',
   'saved-messages' => 'ZAPISANE',
   'sent-mail'      => 'WYS£ANE',
   'saved-drafts'   => 'BRUDNOPIS',
   'mail-trash'     => 'KOSZ',
   'all'            => 'WSZYSTKIE',
   DELETE => '--USUÑ--'
   );

%lang_sortlabels =
   (
   status      => 'Status (Pierwsze nieprzeczytane)',
   date        => 'Data (od najnowszych)',
   date_rev    => 'Data (od najstarszych)',
   sender      => 'Nadawca (od najnowszych)',
   sender_rev  => 'Nadawca (od najstarszych)',
   subject     => 'Temat (od najnowszych)',
   subject_rev => 'Temat (od najstarszych)',
   size        => 'Rozmiar (od najwiêkszych)',
   size_rev    => 'Rozmiar (od najmniejszych)'
   );

%lang_prioritylabels =
   (
   normal      => 'Normalny',
   urgent      => 'Pilny',
   'non-urgent'=> 'Ma³o wa¿ny'
   );

%lang_withoriglabels =
   (
   at_beginning => 'Na pocz±tku',
   at_end      => 'Na koñcu',
   none        => 'Brak'
   );

%lang_receiptlabels =
   (
   ask => 'Zapytaj',
   yes => 'Tak',
   no  => 'Nie'
   );

%lang_timelabels =
   (
     10 => '10 minut',
     30 => '30 minut',
     60 => '60 minut',
    120 => '2 godziny',
    180 => '3 godziny',
    360 => '6 godzin',
    720 => '12 godzin',
   1440 => '24 godziny'
   );

%lang_advsearchlabels =
   (
   contains    => 'zawiera',
   notcontains => 'nie zawiera',
   is          => 'jest równy',
   isnot       => 'nie jest równy',
   startswith  => 'rozpoczyna siê od',
   endswith    => 'koñczy siê na',
   regexp      => 'matches regexp(insensitive)',
   );

%lang_calendar = 
   (
   yearview  => '',
   monthview => 'Miesi±c:',
   weekview  => 'Tydzieñ:',
   dayview   => ''
   );

%lang_month =
   (
   1  => 'Styczeñ',
   2  => 'Luty',
   3  => 'Marzec',
   4  => 'Kwiecieñ',
   5  => 'Maj',
   6  => 'Czerwiec',
   7  => 'Lipiec',
   8  => 'Sierpieñ',
   9  => 'Wrzesieñ',
   10 => 'Pa¼dziernik',
   11 => 'Listopad',
   12 => 'Grudzieñ'
   );

%lang_wday =
   (
   0 => 'niedziela',
   1 => 'poniedzia³ek',
   2 => 'wtorek',
   3 => '¶roda',
   4 => 'czwartek',
   5 => 'pi±tek',
   6 => 'sobota'
   );

%lang_wday_abbrev =
   (
   week => 't.',
   0 => 'N',
   1 => 'Pn',
   2 => 'Wt',
   3 => '¦r',
   4 => 'Cz',
   5 => 'Pi',
   6 => 'So'
   );

%lang_order =
   (
   1 => 'pierwszy(±)',
   2 => 'drugi(±)',
   3 => 'trzeci(±)',
   4 => 'czwarty(±)',
   5 => 'ostatni(±)'
   );

%lang_text =
   (
   login      => 'Wejd¼',
   clear      => 'Wyczy¶æ',
   point      => 'Pkt.',
   pixel      => 'Pixel',
   changepwd  => 'Zmiana has³a',
   viewhistory=> 'Obejrzyj historiê',
   of         => 'z',
   messages   => 'wiadomo¶ci',
   unread     => 'nieprzeczytane',
   nomessages => 'Brak wiadomo¶ci',
   composenew => 'Utwórz now± wiadomo¶æ',
   refresh    => 'Od¶wie¿',
   userprefs  => 'Preferencje u¿ytkownika',
   addressbook=> 'Ksi±¿ka adresowa',
   folders    => 'Foldery',
   emptytrash => 'Opró¿nij kosz',
   totrash    => 'Przenie¶ do kosza',
   forever    => 'Zawsze',
   userdef    => 'Zdefiniowane przez u¿ytkownika',
   logout     => 'Wyloguj',
   page       => 'Strona',
   msgcopyconf=> '\'Na pewno chcesz skopiowaæ zaznaczone widomo¶ci?\'',
   copy       => 'Kopiuj',
   msgmoveconf=> '\'Na pewno chcesz przenie¶æ zaznaczone wiadomo¶ci?\'',
   move       => 'Przenie¶',
   markasread => 'Zaznacz jako przeczytane',
   markasunread => 'Zaznacz jako nieprzeczytane',
   dateformat => 'Format daty',
   date       => 'Data',
   recipient  => 'Adresat',
   sender     => 'Nadawca',
   subject    => 'Temat',
   thread     => 'W±tek',
   size       => 'Rozmiar',
   backto     => 'Wróæ do',
   reply      => 'Odpowiedz',
   replyall   => 'Odpowiedz wszystkim',
   forward    => 'Przeka¿',
   forwardasatt=>'Przeka¿ jako za³±cznik',
   printfriendly=> 'Do wydruku',
   from       => 'Od',
   replyto    => 'Odpowiedz',
   to         => 'Do',
   cc         => 'Do wiadomo¶ci',
   bcc        => 'Do ukrytej wiadomo¶ci',
   simplehead => 'Proste nag³ówki',
   allhead    => 'Wszystkie nag³ówki',
   simpleattmode => 'Proste nag³ówki',
   allattmode    => 'Wszystkie nag³ówki',
   attachment => 'Za³±cznik',
   type       => 'Typ',
   filename   => 'Nazwa pliku',
   encoding   => 'Kodowanie',
   description=> 'Opis',
   download   => 'Pobierz',
   thisispartialmsg => 'To jest czê¶æ wiadomo¶ci.',
   msgrebuild => 'Od¶wie¿anie',
   editdraft  => 'Edytuj brudnopis',
   savedraft  => 'Zapisz brudnopis',
   send       => 'Wy¶lij',
   about      => 'Informacje o po³±czeniu',
   close      => 'Zamknij',
   cancel     => 'Anuluj',
   continue   => 'Kontynuuj',
   loginagain => 'Zaloguj ponownie',
   exit       => 'Wyjd¼',
   for        => 'DLA',
   yourname   => 'Imiê Nazwisko',
   save       => 'Zapisz',
   add        => 'Dodaj',
   folderrenprop => '\'Podaj now± nazwê folderu\'',
   rename     => 'Zmieñ nazwê',
   folderdelconf => '\'Na pewno chcesz usun±æ ten folder wraz z zawarto¶ci±?\'',
   markread   => 'MarkRead',
   foldermarkreadconf => '\'Are you going to mark read on all messages in this folder?\'',
   chkindex   => 'Sprawd¼ indeks',
   folderchkindexconf => '\'Czy chcesz sprawdziæ indeks tego folderu?\'',
   reindex    => 'Przeindeksuj',
   folderreindexconf => '\'Czy chcesz przeindeksowaæ ten folder?\'',
   total      => 'Ca³kowity',
   delete     => 'Usuñ',
   reserve    => 'Zarezerwuj',
   clearadd   => 'Usuñ wszystkie adresy',
   importadd  => 'Importuj adresy',
   exportadd  => 'Eksportuj adresy',
   import     => 'Importuj',
   addmod     => 'Dodaj/Zmieñ',
   modify     => 'Zmieñ',
   abooktitle => 'Ksi±¿ka Adresowa',
   abook      => 'KSI¡¯KA ADRESOWA',
   name       => 'Nazwa',
   email      => 'Email',
   note       => 'Opis',
   group      => 'Grupa',
   quota_hit  => 'OSI¡GNIÊTO LIMIT DOSTÊPNEJ PRZESTRZENI NA DYSKU',
   usage      => 'U¿ycie',
   tzmap      => 'Mapa stref czasowych',
   editfroms  => 'Edytuj w³asne adresy e-mail',
   pop3book   => 'Konfiguracja POP3',
   retr_pop3s => 'Odbierz pocztê POP3',
   filterbook => 'Konfiguracja filtrowania',
   include    => 'Zawiera',
   exclude    => 'Nie zawiera',
   smtprelay  => 'SMTP Relay',
   header     => 'Nag³ówek',
   body       => 'Tre¶æ',
   attfilename=> 'Za³±cznik',
   all        => 'Wszystko',
   enable     => 'Aktywne',
   disable    => 'Nieaktywne',
   filtered   => 'Filtrowane',
   blockrelay => 'Zablokuj SMTP Relay',
   blockemail => 'Zablokuj e-mail',
   read       => 'Odczytaj',
   yourmsg    => 'Twoja wiadomo¶æ',
   delivered  => 'Przekazano',
   wasreadon1 => 'zosta³a odczytana',
   wasreadon2 => '.',
   globaladdressbook => 'Wspólna ksi±¿ka adresowa',
   globalfilterrule => 'Wspólne regu³y filtrowania',
   readonly   => 'Tylko do odczytu',
   textcontent=> 'Zawarto¶æ',
   search     => 'Szukaj',
   advsearch  => 'Zaawansowane wyszukiwanie',
   folder     => 'Folder',
   nofoldersel=> 'Nie wybrano folderu',
   showall    => 'Poka¿ wszystkie',
   spellcheck => 'Sprawd¼ pisowniê',
   checkagain => 'Sprawd¼ powtórnie',
   finishchecking => 'Zakoñcz sprawdzanie ',
   manuallyfix=> 'Popraw rêcznie',
   calendar   => 'Kalendarz',
   am         => 'am',
   pm         => 'pm',
   calfmt_year          => 'Rok @@@YEAR@@@',
   calfmt_yearmonth     => '@@@MONTH_STR@@@ @@@YEAR@@@',
   calfmt_yearmonthday  => '@@@DAY@@@ @@@MONTH_STR@@@ @@@YEAR@@@',
   calfmt_yearmonthdaywday => '@@@DAY@@@ @@@MONTH_STR@@@ @@@YEAR@@@ @@@WEEKDAY_STR@@@',
   calfmt_hourminampm => '@@@HOURMIN@@@ @@@AMPM@@@',
   none       => 'brak',
   moreitems  => 'wiêcej',
   multieditconf => 'This item was added for multiple dates.\\nEditing it will change the item for all dates.\\nContinue with Edit?',
   multidelconf  => 'This item was added for multiple dates.\\nDeleting it will delete the item for all dates.\\nContinue with Delete?',
   ed         => 'Zmieñ',
   del        => 'Usuñ',
   noitemforthisday => 'Koniec wpisów',
   today_only               => 'Tylko w dniu dzisiejszym',
   the_wday_of_thismonth    => 'W ',
   the_wday_of_thismonth2   => 'miesi±ca',
   every_wday_of_thismonth  => 'Ka¿dy(±)',
   every_wday_of_thismonth2 => 'bie¿±cego miesi±ca'
   );

%lang_err =
   (
   has_illegal_chars => 'ma niedozwolone znaki!',
   couldnt_open      => 'Nie mo¿na otworzyæ',
   couldnt_locksh    => 'Nie mo¿na odczytaæ blokady',
   couldnt_lock      => 'Nie mo¿na zablokowaæ pliku',
   couldnt_seek      => 'Nie mo¿na odnale¼æ pocz±tku',
   couldnt_close     => 'Nie mo¿na zamkn±æ',
   disallowed_pop3   => 'Niedozwolony serwer POP3',
   disallowed_client => 'Nie mo¿esz siê po³±czyæ za pomoc± tego klienta',
   disallowed_receiverdomain => 'Nie mo¿esz wys³aæ poczty e-mail na ten adres',
   norootlogin       => 'Nie chcesz tego robiæ!',
   shouldnt_move_here=> 'Niepowiniene¶ próbowaæ przenie¶æ tu wiadomo¶ci!',
   destination_folder=> 'Folder docelowy',
   doesnt_exist      => 'nie istnieje!',
   foldername_long   => 'Nazwa folderu nie mo¿e byæ d³u¿sza ni¿ 16 znaków',
   folder_with_name  => 'Folder ',
   already_exists    => 'ju¿ istnieje!',
   cant_create_folder=> 'Nie mo¿na utworzyæ foldera!',
   under_indexing    => 'jest ci±gle w trakcie indeksowania, proszê czekac',
   abook_invalid     => 'Niestety, ale ten plik nie wygl±da na wyeksportowany z Outlook Express 5 w formacie CSV.  Upewnij siê przy pomocy edytora tekstu, czy pierwsza linia rozpoczyna siê od "Name,E-mail", przejd¼',
   back              => 'wstecz',
   tryagain          => 'i spróbuj jeszcze raz.',
   abook_toobig      => 'Przykro mi ale przekraczasz dopuszczalny rozmiar swojej Ksi±¿ki Adresowej.  Przejd¼',
   cant_create_dir   => 'Nie mogê utworzyæ twojego osobistego katalogu!',
   folder_hitquota   => 'Przykro mi, ale przekroczy³e¶ dopuszczalny rozmiar skrzynki pocztowej. Nie bêdziesz teraz móg³ przenie¶æ wiadomo¶ci gdziekolwiek poza Kosze, z którego zostan± natychmiast usuniête.  Wróæ, usuñ czê¶æ wiadomo¶ci, opró¿nij kosz i spróbuj jeszcze raz.',
   att_overlimit     => 'Przykro mi ale rozmiar za³±cznika przekracza limit, który wynosi',
   inv_msg_op        => 'Nieprawid³owa operacja dla tej wiadomo¶ci',
   inv_sessid        => 'Twoje zapytanie nie zawiera w³asciwego identyfikatora sesji - dostêp zabroniony!',
   no_endpart        => 'Czê¶æ koñcowa nieznaleziona',
   part_missing      => 'Czê¶æ zosta³a zagubiona',
   rebuild_fmterr    => 'Z³y format wiadomo¶ci',
   rebuild_sizeerr   => 'Niezgodno¶æ rozmiaru wiadomo¶ci',
   user_not_exist    => 'u¿ytkownik nie istnieje',
   func_notsupported => 'funkcja nie obs³ugiwana',
   auth_syserr       => 'b³±d autentyfikacji',
   param_fmterr      => 'nieprawid³owy format parametru',
   pwd_incorrect     => 'nieprawid³owe has³o',
   network_server_error => 'b³±d sieci',
   sendmail_error    => 'Niestety wyst±pi³ problem podczas wysy³ania Twojej wiadomo¶ci. Naci¶nij przycisk wstecz w przegl±darce, sprawd¼ wiadomo¶æ i spróbuj ponownie.',
   at_char_not_allowed => 'The @ character is not allowed in this field.  Press browser back button and try again',
   badnum_in_days => 'bad number in consecutive days field'
   );

1;
