#!/usr/bin/perl -T

# Portuguese Brazil translation by Edison Figueira Junior, edison.AT.brc.com.br
#                       updated by Rui - iG, ruisb.AT.ig.com.br
# charset: iso-8859-1

%lang_folders =
   (
   INBOX => 'Entrada',
   'saved-messages' => 'Guardadas',
   'sent-mail'      => 'Enviadas',
   'saved-drafts'   => 'Rascunho',
   'mail-trash'     => 'Lixo',
   DELETE => '--APAGAR--'
   );

%lang_sortlabels =
   (
   status      => 'Estado (Não lidas)',
   date        => 'Data (Mais Recente)',
   date_rev    => 'Data (Menos Recente)',
   sender      => 'Remetente (Mais Recente)',
   sender_rev  => 'Remetente (Menos Recente)',
   subject     => 'Assunto (Mais Recente)',
   subject_rev => 'Assunto (Menos Recente)',
   size        => 'Tamanho (Maior)',
   size_rev    => 'Tamanho (Menor)'
   );

%lang_prioritylabels =
   (
   normal      => 'Normal',
   urgent      => 'Alta',
   'non-urgent'=> 'Baixa'
   );

%lang_withoriglabels =
   (
   at_beginning => 'No início',
   at_end      => 'No final',
   none        => 'Ignorar'
   );

%lang_receiptlabels =
   (
   ask => 'Pergunte-me',
   yes => 'Sim',
   no  => 'Não'
   );

%lang_timelabels =
   (
     10 => '10 minutos',
     30 => '30 minutos',
     60 => '60 minutos',
    120 => '2 horas',
    180 => '3 horas',
    360 => '6 horas',
    720 => '12 horas',
   1440 => '24 horas'
   );

%lang_advsearchlabels =
   (
   contains    => 'contendo',
   notcontains => 'não contendo',
   is          => 'sendo',
   isnot       => 'não sendo',
   startswith  => 'iniciando com',
   endswith    => 'terminado em',
   regexp      => 'conforme expressão regular',
   );

%lang_calendar = 
   (
   yearview  => 'Visualizar o',
   monthview => 'Visualizar o Mês de',
   weekview  => 'Visualizar a Semana do dia',
   dayview   => 'Visualizar o Dia'
   );

%lang_month =
   (
   1  => 'Janeiro',
   2  => 'Fevereiro',
   3  => 'Março',
   4  => 'Abril',
   5  => 'Maio',
   6  => 'Junho',
   7  => 'Julho',
   8  => 'Agosto',
   9  => 'Setembro',
   10 => 'Outubro',
   11 => 'Novembro',
   12 => 'Dezembro'
   );

%lang_wday =
   (
   0 => 'Domingo',
   1 => 'Segunda',
   2 => 'Terça',
   3 => 'Quarta',
   4 => 'Quinta',
   5 => 'Sexta',
   6 => 'Sábado'
   );

%lang_wday_abbrev =
   (
   week => 'SEM',
   0 => 'D',
   1 => 'S',
   2 => 'T',
   3 => 'Q',
   4 => 'Q',
   5 => 'S',
   6 => 'S'
   );

%lang_order =
   (
   1 => '1º',
   2 => '2º',
   3 => '3º',
   4 => '4º',
   5 => 'última'
   );

%lang_text =
   (
   login      => 'Entrar',
   clear      => 'Limpar',
   point      => 'Pontos',
   pixel      => 'Pixels',
   changepwd  => 'Trocar Senha',
   viewhistory=> 'Ver Histórico',
   of         => 'de',
   messages   => 'mensagens',
   unread     => 'não lidas',
   nomessages => 'Não há mensagens',
   composenew => 'Compor Mensagem',
   refresh    => 'Atualizar',
   userprefs  => 'Preferências do Usuário',
   addressbook=> 'Livro de Endereços',
   folders    => 'Pastas',
   emptytrash => 'Esvaziar Pasta Lixo',
   totrash    => 'Mover para o Lixo',
   forever    => 'Para sempre',
   userdef    => 'Usuário Define',
   logout     => 'Sair',
   page       => 'Página',
   msgcopyconf=> '\'Tem a certeza que quer copiar a(s) mensagem(s) selecionada(s)?\'',
   copy       => 'Copiar',
   msgmoveconf=> '\'Tem a certeza que quer mover as mensagens selecionadas?\'',
   move       => 'Mover',
   markasread => 'Marcar como lida',
   markasunread => 'Marcar como não lida',
   dateformat => 'Formato da data',
   date       => 'Data',
   recipient  => 'Destinatário',
   sender     => 'Remetente',
   subject    => 'Assunto',
   thread     => 'Thread',
   size       => 'Tamanho',
   backto     => 'Voltar para',
   reply      => 'Responder',
   replyall   => 'Responder a Todos',
   forward    => 'Encaminhar',
   forwardasatt=>'Encaminhar como Anexo',
   printfriendly=> 'Impressão Amigável',
   from       => 'De',
   replyto    => 'Responder a',
   to         => 'Para',
   cc         => 'Cópia',
   bcc        => 'Cópia Oculta',
   simplehead => 'Cabeçalho Simples',
   allhead    => 'Cabeçalho Completo',
   simpleattmode => 'Anexos Simples',
   allattmode    => 'Todos os Anexos',
   attachment => 'Anexo',
   type       => 'Tipo',
   filename   => 'Nome do Arquivo',
   encoding   => 'Codificação',
   description=> 'Descrição',
   download   => 'Baixar',
   thisispartialmsg => 'Esta é uma mensagem parcial.',
   msgrebuild => 'Reconstroi mensagem',
   editdraft  => 'Editar Rascunho',
   savedraft  => 'Salvar Rascunho',
   send       => 'Enviar',
   about      => 'Sobre...',
   close      => 'Fechar',
   cancel     => 'Cancelar',
   continue   => 'Continuar',
   loginagain => 'Novo Acesso',
   exit       => 'Sair',
   for        => 'Para',
   yourname   => 'Seu Nome',
   save       => 'Salvar',
   add        => 'Adicionar',
   folderrenprop => '\' favor indicar o novo nome para esta pasta\'',
   rename     => 'Renomear',
   folderdelconf => '\'Tem certeza que quer excluir esta pasta e o seu conteúdo?\'',
   markread   => 'Marcar com Lido',
   foldermarkreadconf => '\'Tem certeza que quer marcar todas as mensagens desta pasta como lidas?\'',
   chkindex   => 'Verifica Índice',
   folderchkindexconf => '\'Tem certeza que quer verificar o índice desta pasta?\'',
   reindex    => 'Refaz Índice',
   folderreindexconf => '\'Tem certeza que quer refazer o índice desta pasta?\'',
   total      => 'Total',
   delete     => 'Apagar',
   reserve    => 'Reservar',
   clearadd   => 'Apagar Todos os Endereços',
   importadd  => 'Importar Endereços',
   exportadd  => 'Exportar Endereços',
   import     => 'Importar',
   addmod     => 'Adicionar/Modificar',
   modify     => 'Modificar',
   abooktitle => 'Livro de Endereços',
   abook      => 'Livro de Endereços',
   name       => 'Nome',
   email      => 'E-mail',
   note       => 'Nota',
   group      => 'Grupo',
   quota_hit  => 'LIMITE DE TAMANHO PERMITIDO',
   usage      => 'Uso',
   tzmap      => 'Fuso horário',
   editfroms  => 'Editar Endereços de E-mail Pessoal',
   pop3book   => 'Contas POP3',
   retr_pop3s => 'Buscar Mensagens POP3',
   filterbook => 'Filtro de Mensagens',
   include    => 'Incluir',
   exclude    => 'Excluir',
   smtprelay  => 'SMTP Relay',
   header     => 'Cabeçalho',
   body       => 'Corpo',
   attfilename=> 'Anexo',
   all        => 'Tudo',
   enable     => 'Ativo',
   disable    => 'Inativo',
   filtered   => 'Filtrado',
   blockrelay => 'Bloquear SMTP Relay',
   blockemail => 'Bloquear E-mail',
   read       => 'Ler',
   yourmsg    => 'Sua mensagem',
   delivered  => 'Entregue',
   wasreadon1 => 'lida em',
   wasreadon2 => '.',
   globaladdressbook => 'Livro de Endereços Global',
   globalfilterrule => 'Regras de Filtros Globais',
   readonly   => 'Somente Leitura',
   textcontent=> 'Conteúdo do Texto',
   search     => 'Pesquisar',
   advsearch  => 'Pesquisa Avançada',
   folder     => 'Pasta',
   nofoldersel=> 'Nenhuma Pasta Selecionada',
   showall    => 'Mostrar Todas',
   spellcheck => 'Verificar Ortografia',
   checkagain => 'Verificar Novamente',
   finishchecking => 'Terminar a Verificação',
   manuallyfix=> 'Corrigir Manualmente',
   calendar   => 'Agenda de Compromissos',
   am         => 'am',
   pm         => 'pm',
   calfmt_year          => 'Ano de @@@YEAR@@@',
   calfmt_yearmonth     => '@@@MONTH_STR@@@ de @@@YEAR@@@',
   calfmt_yearmonthday  => '@@@DAY@@@ de @@@MONTH_STR@@@ de @@@YEAR@@@',
   calfmt_yearmonthdaywday => '@@@WEEKDAY_STR@@@, @@@DAY@@@ de @@@MONTH_STR@@@ de @@@YEAR@@@',
   calfmt_hourminampm => '@@@HOURMIN@@@ @@@AMPM@@@',
   none       => 'Nenhum',
   moreitems  => 'mais itens',
   multieditconf => 'Este item foi adicionado em multiplas datas.\\nEditá-lo irá alterar o item em todas as datas.\\nContinua a Edição?',
   multidelconf  => 'Este item foi adicionado em multiplas datas.\\nExcluí-lo irá fazer com que seja excluido em todas as datas.\\nContinua a Exclusão?',
   ed         => 'Editar',
   del        => 'Excluir',
   noitemforthisday => 'Nenhum item para esta data',
   today_only               => 'Somente nesta data',
   the_wday_of_thismonth    => 'A @@@ORDER@@@ @@@WDAY@@@ do mês',
   every_wday_of_thismonth  => 'Cada @@@WDAY@@@ deste mês'
   );

%lang_err =
   (
   has_illegal_chars => 'Tem caracteres ilegais!',
   couldnt_open      => 'Não foi possível abrir',
   couldnt_locksh    => 'Não consigo ler, bloqueado',
   couldnt_lock      => 'Não foi possível gravar, esta',
   couldnt_seek      => 'Não foi possível procurar no início de',
   couldnt_close     => 'Não foi possível fechar',
   disallowed_pop3   => 'Erro no Servidor POP3',
   disallowed_client => 'Você não tem permissão para se conectar a partir deste endereço IP',
   disallowed_receiverdomain => 'Você não tem permissão para enviar mensagens para este endereço de e-mail',
   norootlogin       => 'O que está tentando fazer, hã!? ;-)',
   shouldnt_move_here=> 'Não deveria tentar mover as mensagens aqui!',
   destination_folder=> 'Pasta de destino',
   doesnt_exist      => 'Não existe!',
   foldername_long   => 'O nome da pasta não pode conter mais que 16 caracteres!',
   folder_with_name  => 'A pasta com o nome',
   already_exists    => 'já existe!',
   cant_create_folder=> 'Não foi possível criar a pasta!',
   under_indexing    => 'Ainda está indexando, favor tentar mais tarde',
   abook_invalid     => 'Lamento, este arquivo não aparenta ter o formato correto para o livro de endereços. Verifique se exportou o arquivo no formato correto.',
   back              => 'Voltar',
   tryagain          => 'Tentar novamente.',
   abook_toobig      => 'Lamento, foi excedido o limite permitido para o livro de endereços.',
   cant_create_dir   => 'Não foi possível criar o diretório do usuário!',
   folder_hitquota   => 'Lamento, chegou ao limite de espaço da sua pasta, mais nenhum e-mail será guardado. Por favor envie as mensagens antigas para o LIXO e depois apague-as definitivamente.',
   att_overlimit     => 'Lamento, o tamanho do arquivo anexado ultrapassou o limite permitido.',
   inv_msg_op        => 'Operação inválida para a mensagem',
   inv_sessid        => 'O pedido não tem o ID correto -- acesso negado!',
   no_endpart        => 'Parte final não encontrada',
   part_missing      => 'Alguma parte está perdida',
   rebuild_fmterr    => 'Erro no formato da nova mensagem',
   rebuild_sizeerr   => 'Erro no tamanho da nova mensagem',
   user_not_exist    => 'este usuário não existe',
   func_notsupported => 'Função não suportada',
   auth_syserr       => 'Erro na autenticação',
   param_fmterr      => 'Erro no formato do parâmetro',
   pwd_incorrect     => 'Senha incorreta',
   network_server_error => 'erro no servidor de rede',
   sendmail_error    => 'Lamento, houve um problema no envio da mensagem. Favor clicar no botão de voltar do navegador (browser), verifique a sua mensagem e tente novamente.',
   at_char_not_allowed => 'O caracter @ não é permitido neste campo. Pressione o botão retornar do navegador e tente novamente',
   badnum_in_days => 'número incorreto no campo de dias consecutivos'
   );

1;
