#!/usr/bin/perl -T

# Romanian translation by Vladimir Hrusca, vladimir.AT.bitsoft.ro
# charset: iso-8859-2

%lang_folders =
   (
   INBOX => 'INBOX',
   'saved-messages' => 'SALVATE',
   'sent-mail'      => 'TRIMISE',
   'saved-drafts'   => 'DRAFT',
   'mail-trash'     => 'STERSE',
   DELETE => '-STERGERE-'
   );

%lang_sortlabels =
   (
   status      => 'Status (Intai necitite)',
   date        => 'Data (Intai cele mai noi)',
   date_rev    => 'Data (Intai cele mai vechi)',
   sender      => 'Expeditor (Intai cele mai noi)',
   sender_rev  => 'Expeditor (Intai cele mai vechi)',
   subject     => 'Subiect (Intai cele mai noi)',
   subject_rev => 'Subiect (Intai cele mai vechi)',
   size        => 'Marime (Intai cele mai mari)',
   size_rev    => 'Marime (Intai cele mai mici)'
   );

%lang_prioritylabels =
   (
   normal      => 'Normal',
   urgent      => 'Urgent',
   'non-urgent'=> 'Nu e Urgent'
   );

%lang_withoriglabels =
   (
   at_beginning => 'in Inceput',
   at_end      => 'in Sfarsit',
   none        => 'None'
   );

%lang_receiptlabels =
   (
   ask => 'Inreaba',
   yes => 'Da',
   no  => 'Nu'
   );

%lang_timelabels =
   (
     10 => '10 minute',
     30 => '30 minute',
     60 => '60 minute',
    120 => '2 ore',
    180 => '3 ore',
    360 => '6 ore',
    720 => '12 ore',
   1440 => '24 ore'
   );

%lang_advsearchlabels =
   (
   contains    => 'contains',
   notcontains => 'does not contain',
   is          => 'is',
   isnot       => 'is not',
   startswith  => 'starts with',
   endswith    => 'ends with',
   regexp      => 'matches regexp',
   );

%lang_calendar = 
   (
   yearview  => 'Yearview',
   monthview => 'Monthview',
   weekview  => 'Weekview',
   dayview   => 'Dayview'
   );

%lang_month =
   (
   1  => 'January',
   2  => 'February',
   3  => 'March',
   4  => 'April',
   5  => 'May',
   6  => 'June',
   7  => 'July',
   8  => 'August',
   9  => 'September',
   10 => 'October',
   11 => 'November',
   12 => 'December'
   );

%lang_wday =
   (
   0 => 'Sunday',
   1 => 'Monday',
   2 => 'Tuesday',
   3 => 'Wednesday',
   4 => 'Thursday',
   5 => 'Friday',
   6 => 'Saturday'
   );

%lang_wday_abbrev =
   (
   week => 'WK',
   0 => 'S',
   1 => 'M',
   2 => 'T',
   3 => 'W',
   4 => 'T',
   5 => 'F',
   6 => 'S'
   );

%lang_order =
   (
   1 => '1st',
   2 => '2nd',
   3 => '3rd',
   4 => '4th',
   5 => 'last'
   );

%lang_text =
   (
   login      => 'Intra',
   clear      => 'Sterge',
   point      => 'Point',
   pixel      => 'Pixel',
   changepwd  => 'Schimba parola',
   viewhistory=> 'Vede Istoria',
   of         => 'din',
   messages   => 'mesaje',
   unread     => 'necitite',
   nomessages => 'Nici un mesaj',
   composenew => 'Compune un mesaj',
   refresh    => 'Reincarca',
   userprefs  => 'Preferinte',
   addressbook=> 'Agenda',
   folders    => 'Foldere',
   emptytrash => 'Curata mesajele sterse',
   totrash    => 'Move to Trash',
   forever    => 'Intotdeauna',
   userdef    => 'User defineste',
   logout     => 'Iesire',
   page       => 'Pagina',
   msgcopyconf=> '\'Sunteti sigur ca doriti sa copiati mesajul(ele) selectate?\'',
   copy       => 'Copiaza',
   msgmoveconf=> '\'Esti sigur ca vrei sa muti mesajul(ele) selectate?\'',
   move       => 'Muta',
   markasread => 'Marcheaza ca citit',
   markasunread => 'Marcheaza ca necitit',
   dateformat => 'Data format',
   date       => 'Data',
   recipient  => 'Destinatar',
   sender     => 'Expeditor',
   subject    => 'Subiect',
   thread     => 'Grup',
   size       => 'Marime',
   backto     => 'Inapoi la',
   reply      => 'Raspunde',
   replyall   => 'Raspunde tuturor',
   forward    => 'Trimite mai departe',
   forwardasatt=>'Forwardeaza atasat',
   printfriendly=> 'Bun de tipar',
   from       => 'De la',
   replyto    => 'Raspunde',
   to         => 'Pentru',
   cc         => 'CC',
   bcc        => 'BCC',
   simplehead => 'Header simplu',
   allhead    => 'Header complet',
   simpleattmode => 'Attasament simplu',
   allattmode    => 'Toate attasament-uri',
   attachment => 'Atasament',
   type       => 'Tip',
   filename   => 'Nume fisier',
   encoding   => 'Codare',
   description=> 'Descriptia',
   download   => 'Downloadeaza',
   thisispartialmsg => 'Acesta este un mesaj partial.',
   msgrebuild => 'Refacere Messajul',
   editdraft  => 'Redactare Draft',
   savedraft  => 'Salvare Draft',
   send       => 'Trimite',
   about      => 'Despre',
   close      => 'Inchide',
   cancel     => 'Anuleaza',
   continue   => 'Continua',
   loginagain => 'Login inca o data',
   exit       => 'Esire',
   for        => 'PENTRU',
   yourname   => 'Numele Tau',
   save       => 'Salveaza',
   add        => 'Adauga',
   folderrenprop => '\'Va rugam sa introduceti un nou nume pentru acest folder\'',
   rename     => 'Renumire',
   folderdelconf => '\'Esti sigur ca vrei sa stergi folderul asta si continutul lui?\'',
   markread   => 'MarkRead',
   foldermarkreadconf => '\'Are you going to mark read on all messages in this folder?\'',
   chkindex   => 'Verifica Index',
   folderchkindexconf => '\'Doriti sa verificati Index pentru acest folder?\'',
   reindex    => 'ReIndexare',
   folderreindexconf => '\'Doriti sa reindexati acest folder?\'',
   total      => 'Total',
   delete     => 'Sterge',
   reserve    => 'Reservare',
   clearadd   => 'Sterge toate adrese',
   importadd  => 'Importa adrese',
   exportadd  => 'Exporta adrese',
   import     => 'Importa',
   addmod     => 'Adauga/Modifica',
   modify     => 'Modifica',
   abooktitle => 'Agenda',
   abook      => 'AGENDA',
   name       => 'Nume',
   email      => 'Email',
   note       => 'Note',
   group      => 'Groupa',
   quota_hit  => 'DEP&Atilde;SIRE SPATIU ALOCAT',
   usage      => 'Folosit',
   tzmap      => 'World timezone map',
   editfroms  => 'Redactarea email-urilor personale',
   pop3book   => 'POP3 Setup',
   retr_pop3s => 'Citeste POP3 Mail',
   filterbook => 'Mail Filter setare',
   include    => 'Include',
   exclude    => 'Exclude',
   smtprelay  => 'SMTP Relay',
   header     => 'Cap',
   body       => 'Corp',
   attfilename=> 'FisierAtas',
   all        => 'Toate',
   enable     => 'Activ',
   disable    => 'Inactiv',
   filtered   => 'Filtrat',
   blockrelay => 'Blockare SMTP Relay',
   blockemail => 'Blockare email',
   read       => 'Citire',
   yourmsg    => 'Mesaj Dv.',
   delivered  => 'Trimis',
   wasreadon1 => 'a fost citit pe',
   wasreadon2 => '.',
   globaladdressbook => 'Cartea globala',
   globalfilterrule => 'Filtrare globala',
   readonly   => 'NumaiCitire',
   textcontent=> 'Content',
   search     => 'Cauta',
   advsearch  => 'Advanced search',
   folder     => 'Folder',
   nofoldersel=> 'No Folder selected',
   showall    => 'Show All',
   spellcheck => 'Verificare',
   checkagain => 'Verifica iar',
   finishchecking => 'Termina verificare',
   manuallyfix=> 'Fixeaza manual',
   calendar   => 'Calendar',
   am         => 'am',
   pm         => 'pm',
   calfmt_year          => 'Year @@@YEAR@@@',
   calfmt_yearmonth     => '@@@MONTH_STR@@@ @@@YEAR@@@',
   calfmt_yearmonthday  => '@@@MONTH_STR@@@ @@@DAY@@@ @@@YEAR@@@',
   calfmt_yearmonthdaywday => '@@@MONTH_STR@@@ @@@DAY@@@ @@@YEAR@@@ @@@WEEKDAY_STR@@@',
   calfmt_hourminampm => '@@@HOURMIN@@@ @@@AMPM@@@',
   none       => 'None',
   moreitems  => 'more items',
   multieditconf => 'This item was added for multiple dates.\\nEditing it will change the item for all dates.\\nContinue with Edit?',
   multidelconf  => 'This item was added for multiple dates.\\nDeleting it will delete the item for all dates.\\nContinue with Delete?',
   ed         => 'Ed',
   del        => 'Del',
   noitemforthisday => 'No items for this day',
   today_only               => 'Today\'s date only',
   the_wday_of_thismonth    => 'The @@@ORDER@@@ @@@WDAY@@@ of the month',
   every_wday_of_thismonth  => 'Every @@@WDAY@@@ this month'
   );

%lang_err =
   (
   has_illegal_chars => 'are caractere ilegale!',
   couldnt_open      => 'Nu pot deschide',
   couldnt_locksh    => 'Nu pot citi mesajul blocat',
   couldnt_lock      => 'Nu pot bloca',
   couldnt_seek      => 'Nu pot ajunge la inceput',
   couldnt_close     => 'Nu pot inchide',
   disallowed_pop3   => 'Server POP3 inaccesibil',
   disallowed_client => 'Nu aveti voie sa va conectati de la acest client',
   disallowed_receiverdomain => 'Nu aveti voie sa trimiteti mesaje la aceasta adresa',
   norootlogin       => 'Imi pare rau dar nu poti intra cu root',
   shouldnt_move_here=> 'Nu ar trebui sa iti muti mesajele aici',
   destination_folder=> 'Folderul destinatie',
   doesnt_exist      => 'nu exista!',
   foldername_long   => 'Numele folderului nu poate contine mai mult de 16 litere!',
   folder_with_name  => 'Un folder cu numele',
   already_exists    => 'deja exista!',
   cant_create_folder=> 'Nu pot crea folderul!',
   under_indexing    => 'is still under indexing, please try later',
   abook_invalid     => 'Imi pare rau dar acest fisier nu pare a fi exportat din Microsoft Outlook Express 5 in format CSV. Asigura-te ca atunci cand il vezi intr-un editor de texte, prima linie incepe cu "Name,E-mail Address", apoi du-te',
   back              => 'inapoi',
   tryagain          => 'incearca din nou.',
   abook_toobig      => 'Imi pare rau dar aceasta ar depasi limita agendei tale. Te rog du-te',
   cant_create_dir   => 'Nu pot creea directorul tau!',
   folder_hitquota   => 'Imi pare rau dar ti-ai depasit spatiul alocat si nu mai poti salva scrisori.  Nu vei putea muta decat mesaje spre STERSE.  Du-te inapoi sterge ceva mesaje, distruge mesajele sterse si incearca din nou.',
   att_overlimit     => 'Imi pare rau, atachmentul dvs. depaseste marimea acceptata, adica',
   inv_msg_op        => 'Operatia incorecta pentru mesaj',
   inv_sessid        => 'Request-ul Dv. nu contine cooky-ul potrivit pentru sessiunea aceasta - acces inchis!',
   no_endpart        => 'Nu am gasit sfarsit',
   part_missing      => 'Nu am gasit o parte',
   rebuild_fmterr    => 'Formatarea mesajului nou incorecta',
   rebuild_sizeerr   => 'Dimensiune mesajului nou incorecta',
   user_not_exist    => 'nu exista acest user',
   func_notsupported => 'Functia nu e suportata',
   auth_syserr       => 'erroarea sistemului de autotenficare',
   param_fmterr      => 'parameter incorect',
   pwd_incorrect     => 'parola incorecta',
   network_server_error => 'greseala serverului',
   sendmail_error    => 'Este o problema in trimiterea mesajului Dv. Va rugam sa apasati inapoi si sa verificati mesajul.',
   at_char_not_allowed => 'The @ character is not allowed in this field.  Press browser back button and try again',
   badnum_in_days => 'bad number in consecutive days field'
   );

1;
