#!/usr/bin/perl -T

$lang_charset = 'koi8-r';

%lang_folders =
   (
   INBOX => 'ВХОДЯЩИЕ',
   SAVED => 'АРХИВ',
   SENT  => 'ОТПРАВЛЕННЫЕ',
   TRASH => 'КОРЗИНА'
   );

%lang_sortlabels =
   (
   status      => 'Status (Unread first)',
   date        => 'по дате ',
   date_rev    => 'по дате (Обратный порядок)',
   sender      => 'по автору',
   sender_rev  => 'по автору (Обратный порядок)',
   size        => 'по размеру ',
   size_rev    => 'по размеру (Обратный порядок)',
   subject     => 'по теме ',
   subject_rev => 'по теме (Обратный порядок)'
   );

%lang_mualabels =
   (
   outlookexp5 => 'Outlook Express 5',
   nsmail      => 'Netscape Mail 4.x'
   );

%lang_text =
   (  
   login      => 'Вход',
   clear      => 'Сброс',
   of         => 'из',
   messages   => 'сообщений',
   unread     => 'новых',
   nomessages => 'нет сообщений',
   composenew => 'Создать сообщение',
   refresh    => 'Обновить',
   userprefs  => 'Настройки',
   addressbook=> 'Адресная книга',
   folders    => 'Папки',
   emptytrash => 'Очистить корзину',
   logout     => 'Выход',
   page       => 'Страница',
   moveconfirm=> '\'Удалить выбранные сообщения?\'',
   move       => 'Переместить',
   date       => 'Дата',
   recipient  => 'Отправлено',
   sender     => 'Автор',
   subject    => 'Тема',
   size       => 'Размер',
   backto     => 'Вернуться в',
   reply      => 'Ответить',
   replyall   => 'Ответить всем',
   forward    => 'Переадресовать',
   from       => 'От',
   replyto    => 'Обратный адрес',
   to         => 'Кому',
   cc         => 'Копия',
   bcc        => 'BCC',
   simplehead => 'краткое',
   allhead    => 'полное',
   simpleattmode => 'Simple attachments',
   allattmode    => 'All attachments',
   attachment => 'Вложение',
   type       => 'Тип',
   filename   => 'Имя файла',
   encoding   => 'Кодировка',
   download   => 'Загрузить',
   send       => 'Отправить',
   cancel     => 'Отмена',
   continue   => 'Продолжить',
   for        => 'ДЛЯ',
   yourname   => 'Ваше Имя',
   save       => 'Сохранить',
   add        => 'Добавить',
   folderconf => 'Удалить папку и её содержимое?',
   delete     => 'Удалить',
   importadd  => 'Импорт адресной книги',
   import     => 'Импортировать',
   addmod     => 'Добавить/Изменить',
   abooktitle => 'Адресная книга ',
   abook      => 'АДРЕСНАЯ КНИГА',
   quota_hit  => 'Превышение Квоты',
   pop3book   => 'POP3 Setup',
   retr_pop3s => 'Retrieve POP3 Mail',
   filterbook => 'Mail Filter Setup',
   include    => 'Include',
   exclude    => 'Exclude',
   header     => 'Header',
   body       => 'Body',
   attfilename=> 'Attachment Filename',
   enable     => 'Enable',
   disable    => 'Disable',
   read       => 'Read',
   yourmsg    => 'Your message',
   delivered  => 'Delivered',
   wasreadon1 => 'was read on',
   wasreadon2 => '.',
   search     => 'Search'
   );

%lang_err = (
            has_illegal_chars => 'имеет недопустимые символы!',
            couldnt_open      => 'Не могу открыть',
            couldnt_locksh    => 'Couldn\'t get read lock on',
            couldnt_lock      => 'Не могу создать лок файл в ',
            couldnt_seek      => 'Не могу просмотреть начало ',
            couldnt_close     => 'Не могу закрыть',
            norootlogin       => 'Вход ROOTа закрыт для обеспечения безопасности.',
            shouldnt_move_here=> 'Вы не можете переместить сообщение здесь!',
            destination_folder=> 'Папка назначения',
            doesnt_exist      => 'не создан!',
            foldername_long   => 'Имя папки не может содержать более 16 символов!',
            folder_with_name  => 'Папка с именем',
            already_exists    => 'уже существует!',
            cant_create_folder=> 'Не могу создать папку!',
            abook_invalid     => 'Извините, этот файл не может быть экспортирован из формата Microsoft Outlook Express 5 в CSV формат.  Убедитесь, открыв этот файл в текстовом редакторе, что первая строка начинается со слов "Name,E-mail Address", затем вернитесь',
            back              => 'назад',
            tryagain          => 'и попробуйте еще раз.',
            abook_toobig      => 'Извините, превышение размера адресной книги.',
            cant_create_dir   => 'Не могу создать вашу пользовательскую директорию!',
            folder_hitquota   => 'Извините, вы израсходовали доступный вам объем, и больше письма не смогут сохраняться в ваших папках. Вы не можете переместить сообщения в папку ,кроме как в КОРЗИНУ, где их можно удалить.  Вернитесь назад, удалите некоторые сообщения или очистите вашу КОРЗИНУ, и попробуйте еще раз.',
            att_overlimit     => 'Извините, ваше вложение превышает разрешенный размер, в',
            inv_sessid        => 'Your request didn\'t contain the proper session ID cookie -- access denied!',
            user_not_exist    => 'user does not exist',
            password_error    => 'wrong password',
            network_server_error => 'network server error'
            );

1;
