#!/usr/bin/perl -T

# Slovak translation by lubos klokner, lubos@klokner.sk, 2002-JUL-11
# charset: iso-8859-2

%lang_folders =
   (
   INBOX => 'PRIJATÉ',
   'saved-messages' => 'ULO®ENÉ',
   'sent-mail'      => 'ODOSLANÉ',
   'saved-drafts'   => 'KONCEPT',
   'mail-trash'     => 'KÔ©',
   'all'            => 'V¹etko',
   DELETE => '--ZMAZA«--'
   );

%lang_sortlabels =
   (
   status      => 'Stav (Nepreèítané prvé)',
   date        => 'Dátum (Najnov¹ie prvé)',
   date_rev    => 'Dátum (Najstar¹ie prvé)',
   sender      => 'Odosielateµ (Najnov¹ie prvé)',
   sender_rev  => 'Odosielateµ (Najstar¹ie prvé)',
   subject     => 'Predmet (Najnov¹ie prvé)',
   subject_rev => 'Predmet (Najstar¹ie prvé)',
   size        => 'Veµkos» (Najväè¹ie prvé)',
   size_rev    => 'Veµkos» (Najmen¹ie prvé)'
   );

%lang_prioritylabels =
   (
   normal      => 'Normálna',
   urgent      => 'Urgentné',
   'non-urgent'=> 'Neurgentné'
   );

%lang_withoriglabels =
   (
   at_beginning => 'na zaèiatku',
   at_end      => 'na konci',
   none        => 'nikde'
   );

%lang_receiptlabels =
   (
   ask => 'Spıta» sa na potvrdenie',
   yes => 'Áno',
   no  => 'Nie'
   );

%lang_timelabels =
   (
     10 => '10 minút',
     30 => '30 minút',
     60 => '60 minút',
    120 => '2 hodiny',
    180 => '3 hodiny',
    360 => '6 hodín',
    720 => '12 hodín',
   1440 => '24 hodín'
   );

%lang_advsearchlabels =
   (
   contains    => 'obsahuje',
   notcontains => 'neobsahuje',
   is          => 'je',
   isnot       => 'nieje',
   startswith  => 'zaèína s',
   endswith    => 'konèí s',
   regexp      => 'spåòa regulárny vıraz',
   );

%lang_calendar = 
   (
   yearview  => 'Roènı prehµad',
   monthview => 'Mesaènı prehµad',
   weekview  => 'Tı¾dennı prehµad',
   dayview   => 'Dennı prehµad'
   );

%lang_month =
   (
   1  => 'Január',
   2  => 'Február',
   3  => 'Marec',
   4  => 'Apríl',
   5  => 'Máj',
   6  => 'Jún',
   7  => 'Júl',
   8  => 'August',
   9  => 'September',
   10 => 'Október',
   11 => 'November',
   12 => 'December'
   );

%lang_wday =
   (
   0 => 'Nedeµa',
   1 => 'Pondelok',
   2 => 'Útorok',
   3 => 'Streda',
   4 => '©tvrtok',
   5 => 'Piatok',
   6 => 'Sobota'
   );

%lang_wday_abbrev =
   (
   week => 'tı¾deò',
   0 => 'N',
   1 => 'P',
   2 => 'U',
   3 => 'S',
   4 => '©',
   5 => 'P',
   6 => 'S'
   );

%lang_order =
   (
   1 => 'prvı',
   2 => 'druhı',
   3 => 'tretí',
   4 => '¹tvrtı',
   5 => 'poslednı'
   );

%lang_text =
   (
   login      => 'Prihlási»',
   clear      => 'Zmaza»',
   point      => 'Bod(ov)',
   pixel      => 'Pixel(ov)',
   changepwd  => 'Zmeni» heslo',
   viewhistory=> 'Prezrie» históriu',
   of         => 'z',
   messages   => 'správ',
   unread     => 'nepreèítanıch',
   nomessages => '®iadne správy',
   composenew => 'Napísa» novú správu',
   refresh    => 'Obnovi»',
   userprefs  => 'U¾ívateµské nastavenia',
   addressbook=> 'Adresár',
   folders    => 'Katalógy',
   emptytrash => 'Vysypa» kô¹',
   totrash    => 'Presunú» do ko¹a',
   forever    => 'Nav¾dy',
   userdef    => 'Vlastné',
   logout     => 'Odhlási»',
   page       => 'Stránka',
   msgcopyconf=> '\'Chcete naozaj kopírova» vybranú(é) správu(y)?\'',
   copy       => 'Kopírova»',
   msgmoveconf=> '\'Chcete naozaj presunú» vybranú(é) správu(y)?\'',
   move       => 'Presunú»',
   markasread => 'Oznaèi» ako preèítané',
   markasunread => 'Oznaèi» ako nepreèítané',
   dateformat => 'Formát dátumu',
   date       => 'Dátum',
   recipient  => 'Príjemca',
   sender     => 'Odosielateµ',
   subject    => 'Predmet',
   thread     => 'Diskusia',
   size       => 'Veµkos»',
   backto     => 'Spä»',
   reply      => 'Odpoveda»',
   replyall   => 'Odpoveda» v¹etkım',
   forward    => 'Posla» ïalej',
   forwardasatt=>'Posla» ïalej ako prílohu',
   printfriendly=> 'Verzia pre tlaè',
   from       => 'Od',
   replyto    => 'Odpoveda»',
   to         => 'Komu',
   cc         => 'Kópia',
   bcc        => 'Skrytá kópia',
   simplehead => 'Jednoduché záhlavie',
   allhead    => 'Kompletné záhlavie',
   simpleattmode => 'Jednoduché prílohy',
   allattmode    => 'V¹etky prílohy',
   attachment => 'Príloha',
   type       => 'Typ',
   filename   => 'Meno súboru',
   encoding   => 'Kódovanie',
   description=> 'Description',
   download   => 'Ulo¾i» do súboru',
   thisispartialmsg => 'Toto je èiastková správa.',
   msgrebuild => 'Správa bola prestavaná',
   editdraft  => 'Upravi» koncept',
   savedraft  => 'Ulo¾i» koncept',
   send       => 'Odosla»',
   about      => 'O aplikácii',
   close      => 'Zatvori»',
   cancel     => 'Zru¹i»',
   continue   => 'Pokraèova»',
   loginagain => 'Znovu prihlási»',
   exit       => 'Koniec',
   for        => 'pre',
   yourname   => 'Va¹e Meno',
   save       => 'Ulo¾i»',
   add        => 'Prida»',
   folderrenprop => '\'Zadajte prosím novı názov pre tento katalóg\'',
   rename     => 'Premenova»',
   folderdelconf => '\'Chcete naozaj zmaza» tento katalóg a celı jeho obsah?\'',
   markread   => 'Oznaèi» ako preèítané',
   foldermarkreadconf => '\'Chcete naozaj oznaèi» v¹etky správy v tomto adresári ako prèítené?\'',
   chkindex   => 'Skontrolova» index',
   folderchkindexconf => '\'Chcete naozaj skontrolova» index tohoto katalógu?\'',
   reindex    => 'Reindexova»',
   folderreindexconf => '\'Chcete naozaj reindexova» tento katalóg?\'',
   total      => 'Celkovo',
   delete     => 'Zmaza»',
   reserve    => 'Rezervova»',
   clearadd   => 'Zmaza» v¹etky adresy',
   importadd  => 'Import adries',
   exportadd  => 'Export adries',
   import     => 'Import',
   addmod     => 'Prida»/Zmeni»',
   modify     => 'Zmeni»',
   abooktitle => 'Adresár',
   abook      => 'Adresár',
   name       => 'Meno',
   email      => 'E-mail',
   note       => 'Poznámka',
   group      => 'Skupina',
   quota_hit  => 'Dosiahnutı limit (quota)',
   usage      => 'Vyu¾itie',
   tzmap      => 'Svetová mapa èasovıch zón',
   editfroms  => 'Upravi» osobné e-mail adresy',
   pop3book   => 'POP3 nastavenia',
   retr_pop3s => 'Prija» POP3 po¹tu',
   filterbook => 'Nastavenie e-mail filtra',
   include    => 'Obsahuje',
   exclude    => 'Neobsahuje',
   smtprelay  => 'SMTP Relay',
   header     => 'Hlavièka',
   body       => 'Telo',
   attfilename=> 'Prilo¾enı súbor',
   all        => 'V¹etko',
   enable     => 'Zapnuté',
   disable    => 'Vypnuté',
   filtered   => 'Filtrované',
   blockrelay => 'Blokova» SMTP Relay',
   blockemail => 'Blokova» e-mail',
   read       => 'Preèítané',
   yourmsg    => 'Va¹a správa',
   delivered  => 'Doruèené',
   wasreadon1 => 'bolo preèítané',
   wasreadon2 => '.',
   globaladdressbook => 'Globálny adresár',
   globalfilterrule => 'Globálne pravidlá pre filtrovanie',
   readonly   => 'Iba na èítanie',
   textcontent=> 'Textovı obsah',
   search     => 'Hµada»',
   advsearch  => 'Roz¹írené vyhµadávanie',
   folder     => 'Katalóg',
   nofoldersel=> 'Nebol vybranı ¾iadny katalóg',
   showall    => 'Zobrazi» v¹etko',
   spellcheck => 'Skontrolova» pravopis',
   checkagain => 'Skontrolova» znovu',
   finishchecking => 'Ukonèi» kontrolu',
   manuallyfix=> 'Ruène upravi»',
   calendar   => 'Kalendár',
   am         => 'doobeda',
   pm         => 'poobede',
   calfmt_year          => 'Rok @@@YEAR@@@',
   calfmt_yearmonth     => '@@@MONTH_STR@@@ @@@YEAR@@@',
   calfmt_yearmonthday  => '@@@MONTH_STR@@@ @@@DAY@@@ @@@YEAR@@@',
   calfmt_yearmonthdaywday => '@@@MONTH_STR@@@ @@@DAY@@@ @@@YEAR@@@ @@@WEEKDAY_STR@@@',
   calfmt_hourminampm => '@@@HOURMIN@@@ @@@AMPM@@@',
   none       => '¾iadny',
   moreitems  => 'viac polo¾iek',
   multieditconf => 'Táto polo¾ka bola pridaná pre viac dátumov.\\nÚprava zmení hodnoty pre v¹etky dátumi.\\nPokraèova» s úpravou?',
   multidelconf  => 'Táto polo¾ka bola pridaná pre viac dátumov.\\nVymazanie zma¾e hodnoty pre v¹etky dátumi.\\nPokraèova» s mazaním?',
   ed         => 'Upravi»',
   del        => 'Zmaza»',
   noitemforthisday => '®iadne polo¾ky pre tento deò',
   today_only               => 'Iba dne¹nı dátum',
   the_wday_of_thismonth    => '',
   the_wday_of_thismonth2   => 'v mesiaci',
   every_wday_of_thismonth  => 'ka¾dı',
   every_wday_of_thismonth2 => 'tento mesiac'
   );

%lang_err =
   (
   has_illegal_chars => 'má nepovolené znaky!',
   couldnt_open      => 'Nedá sa otvori»',
   couldnt_locksh    => 'Nedá sa uzamknú» na èítanie',
   couldnt_lock      => 'Nedá sa uzamknú»',
   couldnt_seek      => 'Nedá sa presunú» na zaèiatok',
   couldnt_close     => 'Nedá sa zavrie»',
   disallowed_pop3   => 'Zakázanı POP3 server',
   disallowed_client => 'Nemáte povolenie pripája» sa z tohto poèítaèa',
   disallowed_receiverdomain => 'Nemáte povolenie odosiela» po¹tu na túto adresu',
   norootlogin       => 'Prepáète, prístup administrátora je z bezpeènostnıch dôvodov blokovanı.',
   shouldnt_move_here=> 'Sem by ste sa nemali pokú¹a» presunú» správu!',
   destination_folder=> 'Cieµovı katalóg',
   doesnt_exist      => 'neexistuje!',
   foldername_long   => 'Meno katalógu nemô¾e presiahnu» 16 znakov!',
   folder_with_name  => 'Katalóg s tımto názvom',
   already_exists    => 'u¾ existuje!',
   cant_create_folder=> 'Nedá sa vytvori» katalóg!',
   under_indexing    => 'sa e¹te indexuje, skúste to prosím neskôr',
   abook_invalid     => 'Prepáète, ale tento súbor nevyzerá ako adresár exportovanı z Microsoft Outlook Express 5 v CVS formáte. Uistite sa o tom prezretím v textovom editori. Prvı riadok by mal zaèína» "Name,E-mail Address", potom pokraèujte.',
   back              => 'spä»',
   tryagain          => 'a skúste znova.',
   abook_toobig      => 'Prepáète, toto by presiahlo veµkostnı limit pre Vá¹ adresár. Prosím pokraèujte.',
   cant_create_dir   => 'Nadá sa vytvori» Vá¹ pou¾ívateµskı adresár!',
   folder_hitquota   => 'Prepáète, dosiahli ste Vá¹ limit (quotu) a u¾ ¾iadna z Va¹ích správ nemô¾e by» ulo¾ená do ¾iadneho katalógu. Nebudete môc» presunú» správu do iného katalógu okrem KO©A, kde mô¾e by» zmazaná. Vrá»te sa a zma¾te niektoré správy alebo vysypte KÔ© a skúste znovu.',
   att_overlimit     => 'Prepáète, Va¹a príloha presiahla veµkostnı limit, ktorı je',
   inv_msg_op        => 'Neplatná operácia pre správu',
   inv_sessid        => 'Va¹a po¾iadavka neobsahuje korektné ID sedenia -- prístup zamietnutı!',
   no_endpart        => 'Koncová èas» chıba',
   part_missing      => 'Niektoré èasti chıbajú',
   rebuild_fmterr    => 'Chybnı formát novej správy',
   rebuild_sizeerr   => 'Chybná veµkos» novej správy',
   user_not_exist    => 'pou¾ívateµ neexistuje',
   func_notsupported => 'funkcia nieje podporovaná',
   auth_syserr       => 'systémová chyba pri overovaní',
   param_fmterr      => 'chybnı formát parametra',
   pwd_incorrect     => 'nesprávne heslo',
   network_server_error => 'chyba sie»ového servera',
   sendmail_error    => 'Prepáète, nastal problém pri posielaní Va¹ej správy. Kliknite prosím vo Va¹om prehliadaèi na tlaèidlo Spä», skontrolujte Va¹u správu a skúste to znovu.',
   at_char_not_allowed => 'Znak @ nie je povolenı v tomto políèku. Kliknite prosím na tlaèítko Spä» vo Va¹om prehliadaèi a skúste to znovu.',
   badnum_in_days => 'zlé èíslo v políèku nasledujúcich dní'
   );

1;
