#!/usr/bin/perl

# Swedish translation by Goran Jartin, tryfan.AT.telia.com
# charset: iso-8859-1

%lang_folders =
   (
   INBOX => 'INKORG',
   'saved-messages' => 'SPARAT',
   'sent-mail'      => 'SKICKAT',
   'saved-drafts'   => 'UTKAST',
   'mail-trash'     => 'PAPPERSKORG',
   DELETE => '--RADERA--'
   );

%lang_sortlabels =
   (
   status      => 'Status (Olästa först)',
   date        => 'Datum (Nyaste först)',
   date_rev    => 'Datum (Äldsta först)',
   sender      => 'Avsändare (Nyaste först)',
   sender_rev  => 'Avsändare (Äldsta först)',
   subject     => 'Ämne (Nyaste först)',
   subject_rev => 'Ämne (Äldsta först)',
   size        => 'Storlek (Största först)',
   size_rev    => 'Storlek (Minsta först)'
   );

%lang_prioritylabels =
   (
   normal      => 'Normal',
   urgent      => 'Urgent',
   'non-urgent'=> 'Non-Urgent'
   );

%lang_withoriglabels =
   (
   at_beginning => 'at Beginning',
   at_end      => 'at End',
   none        => 'None'
   );

%lang_receiptlabels =
   (
   ask => 'Ask to confirm',
   yes => 'Yes',
   no  => 'No'
   );

%lang_positionlabels =
   (
   before => 'Before mail edit area',
   after => 'After mail edit area',
   both  => 'Before and after mail edit area'
   );

%lang_timelabels =
   (
      3 => '3 minutes',
      5 => '5 minutes',
     10 => '10 minutes',
     20 => '20 minutes',
     30 => '30 minutes',
     60 => '60 minutes',
    120 => '2 hours',
    180 => '3 hours',
    360 => '6 hours',
    720 => '12 hours',
   1440 => '24 hours'
   );

%lang_advsearchlabels =
   (
   contains    => 'contains',
   notcontains => 'does not contain',
   is          => 'is',
   isnot       => 'is not',
   startswith  => 'starts with',
   endswith    => 'ends with',
   regexp      => 'matches regexp',
   );

%lang_calendar = 
   (
   yearview  => 'Yearview',
   monthview => 'Monthview',
   weekview  => 'Weekview',
   dayview   => 'Dayview',
   listview   => 'Listview'
   );

%lang_month =
   (
   1  => 'January',
   2  => 'February',
   3  => 'March',
   4  => 'April',
   5  => 'May',
   6  => 'June',
   7  => 'July',
   8  => 'August',
   9  => 'September',
   10 => 'October',
   11 => 'November',
   12 => 'December'
   );

%lang_wday =
   (
   0 => 'Sunday',
   1 => 'Monday',
   2 => 'Tuesday',
   3 => 'Wednesday',
   4 => 'Thursday',
   5 => 'Friday',
   6 => 'Saturday'
   );

%lang_wday_abbrev =
   (
   week => 'WK',
   0 => 'S',
   1 => 'M',
   2 => 'T',
   3 => 'W',
   4 => 'T',
   5 => 'F',
   6 => 'S'
   );

%lang_order =
   (
   1 => '1st',
   2 => '2nd',
   3 => '3rd',
   4 => '4th',
   5 => 'last'
   );

%lang_text =
   (
   login      => 'Logga in',
   clear      => 'Rensa',
   point      => 'Point',
   pixel      => 'Pixel',
   changepwd  => 'Change Password',
   viewhistory=> 'View History',
   of         => 'av',
   messages   => 'meddelanden',
   unread     => 'oläst',
   nomessages => 'Inga meddelanden',
   inmessages => 'Incoming msgs',
   composenew => 'Skriv nytt meddelande',
   refresh    => 'Uppdatera',
   userprefs  => 'Användarinställningar',
   addressbook=> 'Adressbok',
   folders    => 'Mappar',
   emptytrash => 'Töm papperskorgen',
   totrash    => 'Move to Trash',
   forever    => 'Tills vidare',
   delatlogout=> 'Delete at Logout',
   userdef    => 'User Defined',
   logout     => 'Logga ut',
   page       => 'Sida',
   msgcopyconf=> '\'Är du säker på att du vill kopiera de markerade meddelandena?\'',
   copy       => 'Kopiera',
   msgmoveconf=> '\'Är du säker på att du vill flytta de markerade meddelandena?\'',
   move       => 'Flytta',
   markasread => 'Mark as read',
   markasunread => 'Mark as unread',
   dateformat => 'Datum format',
   date       => 'Datum',
   recipient  => 'Mottagare',
   sender     => 'Avsändare',
   subject    => 'Ämne',
   thread     => 'Thread',
   size       => 'Storlek',
   backto     => 'Tillbaka till',
   reply      => 'Svara',
   replyall   => 'Svara alla',
   forward    => 'Viderebefordra',
   forwardasatt=>'Vidarebefordra som bilaga',
   printfriendly=> 'Print friendly',
   from       => 'Från',
   replyto    => 'Svara till',
   to         => 'Till',
   cc         => 'Kopia',
   bcc        => 'Blindkopia',
   simplehead => 'Enkla meddelandehuvuden',
   allhead    => 'Alla meddelandehuvuden',
   simpleattmode => 'Enkla bilagor',
   allattmode    => 'Alla bilagor',
   attachment => 'Bifoga',
   type       => 'Typ',
   filename   => 'Filnamn',
   encoding   => 'Kodning',
   description=> 'Description',
   download   => 'Lagra',
   charset    => 'Charset',
   samecharset=> 'The same as composing charset',
   thisispartialmsg => 'This is a partial message.',
   msgrebuild => 'Message Rebuild',
   editdraft  => 'Redigera utkast',
   savedraft  => 'Spara utkast',
   send       => 'Skicka',
   about      => 'About',
   close      => 'Close',
   cancel     => 'Avbryt',
   continue   => 'Fortsätt',
   loginagain => 'Login again',
   exit       => 'Exit',
   for        => 'FÖR',
   yourname   => 'Ditt namn',
   save       => 'Lagra',
   add        => 'Lägg till',
   folderrenprop => '\'Var snäll och ange ett namn på den här mappen\'',
   rename     => 'Byt namn',
   folderdelconf => '\'Är du säker på att du vill radera mappen och allt innehåll?\'',
   markread   => 'MarkRead',
   foldermarkreadconf => '\'Are you going to mark read on all messages in this folder?\'',
   chkindex   => 'CheckIndex',
   folderchkindexconf => '\'Are you going to check the index of this folder?\'',
   reindex    => 'ReIndex',
   folderreindexconf => '\'Are you sure you want to reindex this folder?\'',
   total      => 'Totalt',
   delete     => 'Ta bort',
   reserve    => 'Reserv',
   clearadd   => 'Ta bort alla adresser',
   importadd  => 'Importera adresser',
   exportadd  => 'Exportera adresser',
   import     => 'Importera',
   addmod     => 'Lägg till / Ändra',
   modify     => 'Ändra',
   abooktitle => 'Adressbok',
   abook      => 'ADRESSBOK',
   name       => 'Name',
   email      => 'Email',
   note       => 'Note',
   group      => 'Grupp',
   quota_hit  => 'Ditt lagringsutrymme är slut!',
   usage      => 'Använt',
   tzmap      => 'World timezone map',
   testsound  => 'Test sound',
   editfroms  => 'Edit personal email addresses',
   pop3book   => 'POP3 Inställningar',
   retr_pop3s => 'Hämta post från POP3-konto',
   filterbook => 'Filterinställningar',
   include    => 'Inkludera',
   exclude    => 'Exkludera',
   smtprelay  => 'SMTP Relay',
   header     => 'Huvud',
   body       => 'Meddelandetext',
   attfilename=> 'Bifogad fil',
   all        => 'Alla',
   enable     => 'Aktivera',
   disable    => 'Avaktivera',
   filtered   => 'Filtered',
   blockrelay => 'Blockera SMTP Relay',
   blockemail => 'Blockera email',
   read       => 'Läst',
   yourmsg    => 'Ditt meddelande',
   delivered  => 'levererades',
   wasreadon1 => 'lästes den',
   wasreadon2 => '.',
   globaladdressbook => 'Global adressbok',
   globalfilterrule => 'Globala filterregler',
   readonly   => 'Skrivskyddat',
   textcontent=> 'Textinnehåll',
   search     => 'Sök',
   advsearch  => 'Advanced search',
   folder     => 'Folder',
   nofoldersel=> 'No Folder selected',
   showall    => 'Show All',
   spellcheck => 'Stavningskontroll',
   checkagain => 'Kontrollera igen',
   finishchecking => 'Avsluta kontroll',
   manuallyfix=> 'Fixa manuellt',
   editstat   => 'Edit Stationery',
   savestat   => 'Save Stationery',
   clearstat  => 'Clear All Stationery',
   selectstat => '-- Select Stationery for Reply --',
   calendar   => 'Calendar',
   am         => 'am',
   pm         => 'pm',
   calfmt_year          => 'Year @@@YEAR@@@',
   calfmt_yearmonth     => '@@@MONTH_STR@@@ @@@YEAR@@@',
   calfmt_yearmonthday  => '@@@MONTH_STR@@@ @@@DAY@@@ @@@YEAR@@@',
   calfmt_yearmonthdaywday => '@@@MONTH_STR@@@ @@@DAY@@@ @@@YEAR@@@ @@@WEEKDAY_STR@@@',
   calfmt_hourminampm => '@@@HOURMIN@@@ @@@AMPM@@@',
   none       => 'None',
   moreitems  => 'more items',
   multieditconf => 'This item was added for multiple dates.\\nEditing it will change the item for all dates.\\nContinue with Edit?',
   multidelconf  => 'This item was added for multiple dates.\\nDeleting it will delete the item for all dates.\\nContinue with Delete?',
   ed         => 'Ed',
   del        => 'Del',
   noitemforthisday => 'No items for this day',
   today_only               => 'Today\'s date only',
   the_wday_of_thismonth    => 'The @@@ORDER@@@ @@@WDAY@@@ of the month',
   every_wday_of_thismonth  => 'Every @@@WDAY@@@ this month'
   );

%lang_err =
   (
   has_illegal_chars => 'innehåller otillåtna tecken!',
   couldnt_open      => 'Kunde inte öppna',
   couldnt_locksh    => 'Kunde inte låsa',
   couldnt_lock      => 'Kunde inte skriva till',
   couldnt_seek      => 'Kunde inte hitta början på',
   couldnt_close     => 'Kunde inte stänga',
   couldnt_updatedb  => 'Couldn\'t update index db ',
   disallowed_pop3   => 'Disallowed POP3 server',
   disallowed_client => 'You are not allowed to connect from this client',
   disallowed_receiverdomain => 'You are not allowed to send message to this email address',
   norootlogin       => 'Beklagar, root kan inte logga in av säkerhetsskäl.',
   shouldnt_move_here=> 'Du bör inte flytta meddelanden till den här mappen!',
   destination_folder=> 'Målmapp',
   doesnt_exist      => 'existerar inte!',
   foldername_long   => 'Mappnamnet får inte vara längre än 16 tecken!',
   folder_with_name  => 'En mapp med namnet',
   already_exists    => 'existerar redan!',
   cant_create_folder=> 'Kan inte skapa mappen!',
   under_indexing    => 'sorteras fortfarande. Försök senare',
   abook_invalid     => 'Beklagar, den här filen ser inte ut som en adressbok som exporterats från Microsoft Outlook Express 5 i CVS-format. Forsäkra dig om att filen startar med:"Name,E-mail Address", och gå',
   back              => 'tillbaka',
   tryagain          => 'och försök på nytt.',
   abook_toobig      => 'Beklagar, du överstiger den tillåtna storleken på din adressbok. Gå',
   cant_create_dir   => 'Kunde inte skapa din användarkatalog!',
   folder_hitquota   => 'Beklagar, du har överskridit det tillåtna lagringsutrymmet för dina mappar. Du kan nu bara flytta meddelanden till papperskorgen, där de kommer att raderas automatiskt. Gå tillbaka och radera några meddelanden eller töm papperskorgen, och försök igen.',
   folder_cutdone    => 'Warning, since the folderquota limit(@@@FOLDERQUOTA@@@) were hit, oldest messages in folders have been removed automatcially',
   att_overlimit     => 'Beklagar, du har överskridit den tillåtna storleken för bilagor. Bilagorna får inte omfatta mer än',
   inv_msg_op        => 'Otillåten operation',
   inv_sessid        => 'Din begäran saknade rätt cookie. Operationen medges inte!',
   no_endpart        => 'End part not found',
   part_missing      => 'Some part was missing',
   rebuild_fmterr    => 'New message format error',
   rebuild_sizeerr   => 'New message size mismatch',
   user_not_exist    => 'Användaren finns inte',
   func_notsupported => 'function not supported',
   auth_syserr       => 'authentication system error',
   param_fmterr      => 'parameter format error',
   pwd_incorrect     => 'Password incorrect',
   pwd_tooshort      => 'Password too short (minimum length @@@PASSWDMINLEN@@@)',
   pwd_toosimple     => 'Password too simple (both alphabet and digit are required)',
   network_server_error => 'Nätverksfel',
   sendmail_error    => 'Beklagar, det uppstod ett problem med att skicka ditt meddelande.  Klicka på Back i din webbläsare, kontrollera meddelandet och försök igen.',
   at_char_not_allowed => 'The @ character is not allowed in this field.  Press browser back button and try again',
   badnum_in_days => 'bad number in consecutive days field'
   );

1;
