#!/usr/bin/perl -T

# Turkish translation by Erdinc Guler, eguler.AT.aegee.metu.edu.tr
# charset: iso-8859-9

%lang_folders =
   (
   INBOX => 'Gelen Kutusu',
   'saved-messages' => 'Saklý',
   'sent-mail'      => 'Gönderilmiþ',
   'saved-drafts'   => 'Taslak',
   'mail-trash'     => 'Çöp Kutusu',
   'all'            => 'All',
   DELETE => '--SÝLÝN--'
   );

%lang_sortlabels =
   (
   status      => 'Durum (Okunmamýþ Önce)',
   date        => 'Tarih (En Yeni Önce)',
   date_rev    => 'Tarih (En Eski Önce)',
   sender      => 'Gönderen (En Yeni Önce)',
   sender_rev  => 'Gönderen (En Eski Önce)',
   subject     => 'Konu (En YEni Önce)',
   subject_rev => 'Konu (En Eski Önce)',
   size        => 'Boyut (En Büyük Önce)',
   size_rev    => 'Boyut (En Küçük Önce)'
   );

%lang_prioritylabels =
   (
   normal      => 'Normal',
   urgent      => 'Acil',
   'non-urgent'=> 'Acil-Deðil'
   );

%lang_withoriglabels =
   (
   at_beginning => 'Baþlangýçta',
   at_end      => 'Sonunda',
   none        => 'Hiçbiri'
   );

%lang_receiptlabels =
   (
   ask => 'Onay iste',
   yes => 'Evet',
   no  => 'Hayýr'
   );

%lang_timelabels =
   (
     10 => '10 minutes',
     30 => '30 minutes',
     60 => '60 minutes',
    120 => '2 hours',
    180 => '3 hours',
    360 => '6 hours',
    720 => '12 hours',
   1440 => '24 hours'
   );

%lang_advsearchlabels =
   (
   contains    => 'contains',
   notcontains => 'does not contain',
   is          => 'is',
   isnot       => 'is not',
   startswith  => 'starts with',
   endswith    => 'ends with',
   regexp      => 'matches regexp(insensitive)',
   );

%lang_calendar = 
   (
   yearview  => 'Yearview',
   monthview => 'Monthview',
   weekview  => 'Weekview',
   dayview   => 'Dayview'
   );

%lang_month =
   (
   1  => 'January',
   2  => 'February',
   3  => 'March',
   4  => 'April',
   5  => 'May',
   6  => 'June',
   7  => 'July',
   8  => 'August',
   9  => 'September',
   10 => 'October',
   11 => 'November',
   12 => 'December'
   );

%lang_wday =
   (
   0 => 'Sunday',
   1 => 'Monday',
   2 => 'Tuesday',
   3 => 'Wednesday',
   4 => 'Thursday',
   5 => 'Friday',
   6 => 'Saturday'
   );

%lang_wday_abbrev =
   (
   week => 'WK',
   0 => 'S',
   1 => 'M',
   2 => 'T',
   3 => 'W',
   4 => 'T',
   5 => 'F',
   6 => 'S'
   );

%lang_order =
   (
   1 => '1st',
   2 => '2nd',
   3 => '3rd',
   4 => '4th',
   5 => 'last'
   );

%lang_text =
   (
   login      => 'Gir',
   clear      => 'Temizle',
   point      => 'Point',
   pixel      => 'Pixel',
   changepwd  => 'Parolayý Deðiþtir',
   viewhistory=> 'Geçmiþi Görüntüle',
   of         => '',
   messages   => 'ileti',
   unread     => 'Okunmamýþ',
   nomessages => 'Ýleti Yok',
   composenew => 'Yeni Ýleti Oluþtur',
   refresh    => 'Yenile',
   userprefs  => 'Kullanýcý Tercihleri',
   addressbook=> 'Adres Defteri',
   folders    => 'Klasörler',
   emptytrash => 'Çöpü Boþalt',
   totrash    => 'Move to Trash',
   forever    => 'Herzaman',
   userdef    => 'Kullancý Tanýmlý',
   logout     => 'Çýkýþ',
   page       => 'Sayfa',
   msgcopyconf=> '\'Seçili iletiy(ler)i kopyalamak istediðinize emin misiniz ?\'',
   copy       => 'Kopyala',
   msgmoveconf=> '\'Seçili iletileri göndermek istediðinize emin misiniz?\'',
   move       => 'Gönder',
   markasread => 'Okumuþ Olarak Ýþaretle',
   markasunread => 'Okunmamýþ Olarak Ýþaretle',
   dateformat => 'Tarih Biçemi',
   date       => 'Tarih',
   recipient  => 'Alýcý',
   sender     => 'Gönderen',
   subject    => 'Konu',
   thread     => 'Atý',
   size       => 'Boyut',
   backto     => 'Geri',
   reply      => 'Cevap Ver',
   replyall   => 'Herkese Cevap Ver',
   forward    => 'Aktar',
   forwardasatt=>'Ek Dosyasý Olarak Aktar',
   printfriendly=> 'Yazýcý Dostu',
   from       => 'Kimden',
   replyto    => 'Cevap-Ver',
   to         => 'Kime',
   cc         => 'KK',
   bcc        => 'GKK',
   simplehead => 'Basit Baþlýk',
   allhead    => 'Tüm Baþlýk',
   simpleattmode => 'Basit Ek Dosyasý',
   allattmode    => 'Tüm Ek Dosyasý',
   attachment => 'Ek Dosyasý',
   type       => 'Tip',
   filename   => 'DosyaAdý',
   encoding   => 'Kodlama',
   description=> 'Taným',
   download   => 'Ýndir',
   thisispartialmsg => 'Bu kýsmi bir ileti',
   msgrebuild => 'Ýletiyi yeniden yapýlandýr',
   editdraft  => 'Taslaðý Düzenle',
   savedraft  => 'Taslaðý Kaydet',
   send       => 'Gönder',
   about      => 'About',
   close      => 'Close',
   cancel     => 'Ýptal',
   continue   => 'Devam',
   loginagain => 'Yeniden Gir',
   exit       => 'Çýkýþ',
   for        => 'için',
   yourname   => 'Ýsminiz',
   save       => 'Kaydet',
   add        => 'Ekle',
   folderrenprop => '\'Bu klasör için lütfen yeni bir isim giriniz\'',
   rename     => 'Yeniden Ýsimlendir',
   folderdelconf => '\'Bu klasörü içindekilerle beraber silmek istediðinize emin misiniz?\'',
   markread   => 'MarkRead',
   foldermarkreadconf => '\'Are you going to mark read on all messages in this folder?\'',
   chkindex   => 'ÝndeksKontrol',
   folderchkindexconf => '\'Bu klasörün indeksine bakmak istediðinize emin misiniz?\'',
   reindex    => 'YenidenÝndeksle',
   folderreindexconf => '\'Bu klasörü yeniden indekslemek istediðinize emin misiniz?\'',
   total      => 'Toplam',
   delete     => 'Sil',
   reserve    => 'Rezerve',
   clearadd   => 'Tüm adresleri sil',
   importadd  => 'Adres Al',
   exportadd  => 'Adres Ver',
   import     => 'Al',
   addmod     => 'Ekle/Deðiþtir',
   modify     => 'Deðiþtir',
   abooktitle => 'Adres Defteri',
   abook      => 'ADRES DEFTERÝ',
   name       => 'Ýsim',
   email      => 'Eposta',
   note       => 'Not',
   group      => 'Grup',
   quota_hit  => 'KOTA SINIRINA ULAÞILDI',
   usage      => 'Kullaným',
   tzmap      => 'World timezone map',
   editfroms  => 'Kiþisel eposta adreslerini düzenle',
   pop3book   => 'POP3 Kurulum',
   retr_pop3s => 'POP3 epostalarýný al',
   filterbook => 'Eposta filitre defteri',
   include    => 'Dahil Et',
   exclude    => 'Hariç Tut',
   smtprelay  => 'SMTP Relay',
   header     => 'Baþlýk',
   body       => 'Gövde',
   attfilename=> 'EkDosyaAdý',
   all        => 'Hepsi',
   enable     => 'Etkinleþtir',
   disable    => 'Engelle',
   filtered   => 'Filitrelenmiþ',
   blockrelay => 'SMTP Relay Engelle',
   blockemail => 'eposta engelle',
   read       => 'Oku',
   yourmsg    => 'Ýletiniz',
   delivered  => 'Gönderildi',
   wasreadon1 => 'okundu',
   wasreadon2 => '.',
   globaladdressbook => 'Genel Adres Defteri',
   globalfilterrule => 'Genel Filitre Kuralý',
   readonly   => 'SaltOkunur',
   textcontent=> 'MetinÝçeriði',
   search     => 'Ara',
   advsearch  => 'Advanced search',
   folder     => 'Folder',
   nofoldersel=> 'No Folder selected',
   showall    => 'Show All',
   spellcheck => 'Yazým Kontrolü',
   checkagain => 'Tekrar Kontrol Edin',
   finishchecking => 'Kontrolü Bitir',
   manuallyfix=> 'Manuel Düzelt',
   calendar   => 'Calendar',
   am         => 'am',
   pm         => 'pm',
   calfmt_year          => 'Year @@@YEAR@@@',
   calfmt_yearmonth     => '@@@MONTH_STR@@@ @@@YEAR@@@',
   calfmt_yearmonthday  => '@@@MONTH_STR@@@ @@@DAY@@@ @@@YEAR@@@',
   calfmt_yearmonthdaywday => '@@@MONTH_STR@@@ @@@DAY@@@ @@@YEAR@@@ @@@WEEKDAY_STR@@@',
   calfmt_hourminampm => '@@@HOURMIN@@@ @@@AMPM@@@',
   none       => 'None',
   moreitems  => 'more items',
   multieditconf => 'This item was added for multiple dates.\\nEditing it will change the item for all dates.\\nContinue with Edit?',
   multidelconf  => 'This item was added for multiple dates.\\nDeleting it will delete the item for all dates.\\nContinue with Delete?',
   ed         => 'Ed',
   del        => 'Del',
   noitemforthisday => 'No items for this day',
   today_only               => 'Today\'s date only',
   the_wday_of_thismonth    => 'The',
   the_wday_of_thismonth2   => 'of the month',
   every_wday_of_thismonth  => 'Every',
   every_wday_of_thismonth2 => 'this month'
   );

%lang_err =
   (
   has_illegal_chars => 'anlamsýz karakterler var!',
   couldnt_open      => 'Açamadý',
   couldnt_locksh    => 'Okuma kilidi açýlamadý',
   couldnt_lock      => 'Yazma kilidi açýlamadý',
   couldnt_seek      => 'Baþlangýca kadar aranamadý',
   couldnt_close     => 'Kapatamadý',
   disallowed_pop3   => 'Engellenmiþ POP3 sunucusu',
   disallowed_client => 'Buradan baðlantýnýz engellendi',
   disallowed_receiverdomain => 'Bu eposta adresine ileti göndermeniz engellenmiþtir',
   norootlogin       => 'Güvenlik nedeniyle root giriþi engellenmiþtir.',
   shouldnt_move_here=> 'Ýletiyi buraya katdetmemelisiniz!',
   destination_folder=> 'Hedef klasör',
   doesnt_exist      => 'yok!',
   foldername_long   => 'Klasör ismi 16 karakterden uzun olamaz!',
   folder_with_name  => 'Klasör',
   already_exists    => 'zaten var!',
   cant_create_folder=> 'Klasör oluþturamýyor!',
   under_indexing    => 'hala indeksleme devam ediyor,daha sonra tekrar deneyiniz',
   abook_invalid     => 'Bu dosya geçerli Outlook Express 5 CSV formatýnda deðil. Lütfen metin düzenleyiciniz ile kontrol edip "Ýsim,Eposta" bilgileriyle baþladýðýna emin olunuz!',
   back              => 'geri',
   tryagain          => 've tekrar deneyiniz.',
   abook_toobig      => 'Adres defterinizin sýnýrda olduðu için bu deðer girilemiyor',
   cant_create_dir   => 'Kullanýcý klasörünüz oluþturulamýyor!',
   folder_hitquota   => 'Kota sýnýrýný doldurnuz ve bu yüzden yeni iletiler kaydedilemiyor.Lütfen "Çöp Kutusu"nu boþaltýn veya iletilerinizin bir kýsmýný siliniz.',
   att_overlimit     => 'Ek dosyasý sýnýrýný aþtýnýz,dosyanýzýn boyutu',
   inv_msg_op        => 'Ýleti için geçersiz iþlem',
   inv_sessid        => 'Ýsteðiniz geçerli bir sezon numrasý veya çerez içermemektedir.--erþim engellendi!',
   no_endpart        => 'Son kýsým bulunamadý',
   part_missing      => 'Bazý kýsýmlar eksik',
   rebuild_fmterr    => 'Yeni ileti biçem hatasý',
   rebuild_sizeerr   => 'Yeni ileti boyut uyumsuzluðu',
   user_not_exist    => 'kullanýcý bulunamdý',
   func_notsupported => 'iþlem desteklenmiyor',
   auth_syserr       => 'onaylama sistem hatasý',
   param_fmterr      => 'parametre biçem hatasý',
   pwd_incorrect     => 'hatalý parola',
   network_server_error => 'að sunucu hatasý',
   sendmail_error    => 'Ýleti gönderimi sýrasýnda hata oluþtu. Tarayýcýnýzýn Geri tuþuna basýn,iletinizi kontrol edip tekrar deneyiniz.',
   at_char_not_allowed => 'The @ character is not allowed in this field.  Press browser back button and try again',
   badnum_in_days => 'bad number in consecutive days field'
   );

1;
